export const offlineExamsData = {
    "Type 1": {
        aionian: {
            "Do Alto Up":
                "IgYAwgggzAAAgDGANhyAgaBAM0EMA2ALgPYwDEACIjAKRWIBk9MA5M3dQBTNvUePtmAEmaVECNACNcAZxmJmMRcupLVK6hoXqd8NAGViABwB0aAEKyTAAjABTfHckAnXITsATazMLOArgDmAY7ehLjOhACWAHYBALQALADsAKy2Dk6u7h5xPv5BjrlhETHxySkAMaowAP-IdgBMAEsAQ0A__",
            "Do Alto Down":
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PXuE0BDMngD2MADjMAeMwD4zAASTmAQnmLas2lNoBcZuMRw0AZSEAHAHRoAQnwDO5uWCIUSBPniIATObcIBXAHMAih88PgI8AEsAOwCAWgAWAHYAVkdnUjcPTzjfAkDgolywiJj45JSAGPoYAH.EIgAmACWEoA__",
            soprano:
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PXuE0SBDAM6CYAHGYA8ZgHxmAAknMAhPMW1ZtKbQC4zcYjhoAygHsADgDo0AISEW5YIhRIF-eIgBM5gwgFcA5v4U3nj8BHgAlgB2.gC0ACwA7ACsDk6kru4esT4EAUFEOaHh0XFJyQAx9DAAoFE1RABMAIsA90A_",
            "Tenor Up":
                "IgYAwgggzAAAgDGANhyAgaBAMCgAXAUwDsB7AJxgGIAERGAUlsQDImYByNxugCjc7rcWXNgBI2NRAjQAjAIYBnBYjYxV6ums0a6OldoPw0AZRIAHAHRoAQoosACMAQA2BGWTmEAJvYV4yAK4A5kGuvnhyZHgAlkRBALQALADsAKyOLm4e3vF-gSGuuRFRsQkpqQAxmjAA.4gEAEwASwArQA_",
            "Tenor Down":
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PXuEBQPIgDsA9gRgAcZgDxmAfGYACacwCEi5bXm0ZtALjNJiOGgDKwgA4A6NACEAhgGdLCsEQokCdgQBMFDwgCuAOZBFH54dgR4AJaCQQC0ACwA7ACsLm6knj7x.gTBoUS5EVGxCSmpADH0MAD.iEQATABLACRAA",
            bass: "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyJgCoAERGAGjsQFpmYA6dp-gena70erbuwDU7WogRoSAQwDOCxOxir19NZo30dK7QfhoAygHsADhzQAhRRwAEYIhRIE5eIgBN7CwgFcAcwCKHzw5AjwASwA7AJYAFgB2AFZHZ1I3D08WXwJA4KIcsIiYuKTkgBjNGAB.xCIAJgAlgAygA_",
        },
        lydian: {
            "Do Alto Down":
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PX440BDMngD2MAPjMABMwCEzcbQB4c5gGJmAImW0ptefDQBlIQAcAdGgBCfAM6mJYIhRIE-eIgBMJ1wgFcA5n4UXnh8BHgAlgB2fgC0ACwA7ACs9o6kLm7uMd4E.oFE2SFhUbGJSQAx9DAA.4hEAEwAPgA8QA___",
            "Do Alto Up":
                "IgYAwgggzAAAgDGANhyAgaBAM0EMA2ALgPYwBkACIjAORWIAU95zApM5dQFTMCUHzOtU7w4aAEa4AzlMTMY8xdQXKl1NXNWIxAZWIAHAHRoAQtMMACMAFN818QCdchawBMLUwg4CuAc192HoS4DoQAlgB2vgC0ACwA7ACsVrb2Ti6u0Z4-.nZZwaGRMQmJADHKMAD.iNYATAB-AOdAA_",
            soprano:
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PX440SBDAM6CYAfGYACZgEJm42gDw5zAMTMARMtpTa8-GgDKAewAOAOjQAhIWYlgiFEgX54iAEwmDCAVwDmvik88fgI8AEsAO18AWgAWAHYAVjsHUmdXN2ivAj8Aoizg0MiYhMSAGPoYAH.EIgAmAG8Ad6A_",
            "Tenor Down":
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PX44BQPIgDsA9gRgB8ZgAJmAQmaTaAPAXMAxMwBEq2jNqL4aAMrCADgDo0AIQCGAZ3NSwRCiQI2BAEyl3CAVwBzAIofPBsCPABLQQCAWgAWAHYAVicXUncvWN8CQOCibLCI6Lik5IAY-hgAf8QiACYAHwBYIA___",
            "Tenor Up":
                "IgYAwgggzAAAgDGANhyAgaBAMCgAXAUwDsB7AJxgDIAERGAclsQAomq2BSNmugKjYCU3Nozo94cNACMAhgGc5iNjGWq6K9WrpalmxJIDKJAA4A6NACF5pgARgCAGwJSyMwgBMbcvGQCuAc38nLzwZMjwASyJ.AFoAFgB2AFY7R2dXDxjvP0CnLNDwqNjEpIAY9RgAf8QCACYAPwBfoA_",
            bass: "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyJgDIAERGAcjsQApnr2BSd2-gKnYBKHuyb1e8OGhIBDAM5zE7GMtX0V6tfS1LNiKQGUA9gAcAdGgBC8swAIwRCiQIy8RACa25hAK4BzPwovPBkCPABLADs.AFoAFgB2AFZ7R1IXN3cY7wJ.QKJskLCo2MSkgBj1GAB.xCIAJgA.AAWgA__",
        },
        phrygian: {
            "Tenor Up":
                "IgYAwgggzAAAgDGANhyAgaBAMCgAXAUwDsB7AJxgFIAERGAYlsQBImG2BCNgCjYHI2NOgDJBTOHDQAjAIYBnOYjYxlquivVq6WpYkkBlEgAcAdGgBC8kwAIwBADYEpZGYQAm1uXjIBXAOZ-jp54MmR4AJZEfgC0ACwA7ACstg5OLu7RXr4BjpkhYZExCYkAMeowAP-IBABMAN70QA___",
            "Do Alto Up":
                "IgYAwgggzAAAgDGANhyAgaBAM0EMA2ALgPYwCkACIjAMRWIAk9tzAhMwBTMDkzl1AMj704cNACNcAZymJmMeYuoLlS6mrmIxAZWIAHAHRoAQtIMACMAFN8V8QCdchKwBNzUwvYCuAcx-33Qlx7QgBLADsfAFoAFgB2AFZLGztHZxcoj28.W0ygkIjo-ISAGOUYAH.EKwAmAG8AaCA___",
            "Tenor Down":
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3P4YBQPIgHYB7AjAB4zADjMAuFOYAsZgEJmAAmYTaAfE2M4aAMpCADgDo0AIQCGAZzNqwRCiQLX-AEzW3CAVwDm.hTeeNYEeACWAv4AtAAsAOwArI7OpG6eMT4EAUFEWaHhUbGJSQAx9DAA.4hEAEwAXgDwQA",
            soprano:
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3P4Y0SBDAM4CYAPGYAcZgFwJzAFjMAhMwAEzMbQD46xnDQBlAPYAHAHRoAQoNMqwRCiQJ88RACYqBhAK4BzHxQ88PgI8AEsAOx8AWgAWAHYAVlt7UicXVyjPAl9.IkygkIjo-ISAGPoYAH.EIgAmAE8AY6A__",
            "Do Alto Down":
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3P4Y0BDMvAHsYAPGYAcZgFwJzAFjMAhMwAEzMbQD46xnDQBlQQAcAdGgBCvAM4mVYIhRIFeeIgBMVVwgFcA5r4pPPF4CPABLADtfAFoAFgB2AFY7B1JnVzdorwI.AKIs4NDImITEgBj6GAB.xCIAJgAvTSA__",
            bass: "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyJgBoAERGAKjsQGpnH2AKdgenYDp2tegFohzOHDQkAhgGc5idjGWr6K9WvpaliKQGUA9gAd-aAELz-AAjBEKJAjLxEAJtbmEArgHMfFDzwZAjwASwA7HxEAFgB2AFZbe1InF1cRTwJffyIMoJCIqLj4gBj1GAB.xCIAJgAvAEmgA__",
        },
        dorian: {
            "Tenor Down":
                "IgYAwgggzAAAgDGANhyAgaBAAoAYAFwCcBTAIwBtjEAERGumWup-5hlx9rt-GAUHzEAdgHtCMALgsA-CwB4LKXQAEMlgEIWqurLoK6S-GgDKIgA4A6NACEAhgGcLysMUqlCtwQBNl9ogFcAc0DKX3xbQnwASyFAgFoAFgB2AFZnVzIPbzi.QiCQ4hzwyJj45JSAGIYYAH.EYgAmfABnoA___",
            bass: "IgYAwgggzAAAgDGANhyAgaBAAoAYAFwCcBTAIwBtiYBqABERgFp7EAaFmjgOg-YYHpuvDuwZ1ECNKQCGAZ1mIOMJSobK1qhpsUaJaAMoB7AA5c0AITlcABGGKVShafmIATa7KIBXAOY.KHvjShPgAlgB2PowALADsAKy29mROLq6MnoS-.sQZQSERUXHxADFqMAD.iMQATABuAHxAA__",
            "Tenor Up":
                "IgYAwgggzAAAgDGANhyAgaBAAoAoAFwFMA7AewCcYASABERgDI7EBSZ69gcnafoAouPdm3q1ECNACMAhgGdZidjCUr6ytavqbFG8WgDKpAA4A6NACE5JgARhCAG0KTy0ogBNrs.OQCuAcz9HT3xpcnwAS2I.AFoAFgB2AFZbBycXd2ivXwDHTJCwyJiExIAYtRgAf8RCACYANwBVoA__",
            soprano:
                "IgYAwgggzAAAgDGANhyAgaBAAoAYAFwCcBTAIwBtjEAERGumWup-5hlx9rt-GNUgIYBnITAC4LAPgsAeCwl0ABFJYBCFsrrS6cugvhoAygHsADgDo0AIWHnFYYpVKEB-YgBNFQogFcA5n6UXvgChPgAlgB2fgC0ACwA7ACs9o5kLm7uMd6E.oHE2SFhUbGJSQAxDDAAoJHVAI4I2O4AywDnbUA__",
            "Do Alto Down":
                "IgYAwgggzAAAgDGANhyAgaBAAoAYAFwCcBTAIwBtjEAERGumWup-5hlx9rt-GNAQ3L4A9jAC4LAPgsAeCwl0ABFJYBCFsrrS6cugvhoAysIAOAOjQAhfgGczisMUqlC.fMQAmim0QCuAc39Kb3x-QnwASwA7fwBaABYAdgBWBycyV3cPWJ9CAKDiHNDw6Lik5IAYhhgAf8RiACZfADCgA___",
            "Do Alto Up":
                "IgYAwgggzAAAgDGANhyAgaBAAoNBDAGwBcB7GAEgAREYAyaxAUgYpYHIX6aAKdzl5jSqIEaAEZ4AzpMQsYchTXlLFNVbJUi0AZRIAHAHRoAQlIMACMAFMCVsQCc8RKwBNzkovYCuAcx-33Ijx7IgBLADsfAFoAFgB2AFZLGztHZxcoj28.W0ygkIjo-ISAGKUabCsAJgA3AEKgA_",
        },
        locrian: {
            "Do Alto Up":
                "IgYAwgggzAAAgDGANhyAgaBAM0EMA2ALgPYwCUACIjANRWIBU95zAFM09ZdZ4nT827wcAI1wBncYmYwZc6rIXzqy6UsRw0AZWIAHAHRoAQhP0ACMAFN8lkQCdchSwBMz4wnYCuAc2823hLh2hACWAHbeALQALADsAKwW1rYOTs6R7l6-NhmBweFRcfEAMQowAP-IlgBMAGMA50A_",
            bass: "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyJgEoAERGAajsQCpnr2AKdt-2-3oiYD2.eDDQkAhgGcZidjEXL6S1SvoaF6xHDQBlAPYAHAHRoAQrNMACMEQokCUvEQAmNmYQCuAc18UnnhSBHgAlgB2vgC0ACwA7ACsdg6kzq5u0V4EfgFEWcGhkTEJiQAxquIwRABMAGMAk0A___",
            "Tenor Down":
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PX4YBQPIgDsA9gRgBsZgFxmAHGaTaALDkLVtGbXm1F8NAGVhABwB0aAEIBDAM4mABGCIUSBSwIAmd64QCuAcz8KLzxLAjwAS0E.AFoAFgB2AFYHJ1JXD2jvAn9AokyQsMiYhMSAGPoYAH.EIgAmADGAcSA__",
            "Tenor Up":
                "IgYAwgggzAAAgDGANhyAgaBAMCgAXAUwDsB7AJxgEoAERGAalsQComq2AKN1umunxI35s-8GGgBGAQwDOMxGxiLldJapV0NC9YjhoAyiQAOAOjQAhWSYAEYAgBsCEslMIATazLxkArgHM.R088KTI8AEsiPwBaABYAdgBWWwcnF3dor18Ax0yQsMiYhMSAGNUYAH.EAgAmAHHMIA",
            "Do Alto Down":
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PX4Y0BDMngD2MANjMAuMwA4zcbQBYMuctpTas2vPhoAykIAOAOjQAhPgGcjAAjBEKJAnzxEAJtYuEArgHMfFDzw-AjwASwA7HwBaABYAdgBWW3tSJxdXKM8CX38iTKCQiOj4hIAY-hgAf8QiACYAMYBtIA__",
            soprano:
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PX4Y0SBDAM6CYAbGYBcZgBxm42gCwZc5bSm1ZtefDQBlAPYAHAHRoAQkOMACMEQokC.PEQAmVwYQCuAc28V3ePwEeACWAHbeALQALADsAKw2dqSOzi6RHgQ-fkQZgcHhUXHxADH0MAD.iEQATABjAP5AA___",
        },
        aeolian: {
            soprano:
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PXuE0SBDAM6CYALGYAcZgGxmAXEkz5zAHjLaU2rNrjEcNAGUA9gAcAdGgBCQswAIwRCiQL88RACa3BhAK4BzPwovPH4CPABLADs.AFoAFgB2AFZ7R1IXN3cY7wJ.QKJskLCo2MSkgBj6GAB.xCIAJgBlnyA_",
            "Tenor Up":
                "IgYAwgggzAAAgDGANhyAgaBAMCgAXAUwDsB7AJxgAoAERGAKlsQEomYBqNxu1uzugDRt-ibizY1ECNACMAhgGcFiNjFXq6azRro6V2g.DQBlEgAcAdGgBCiiwAIwBADYEZZOYQAm9hXjIArgDmQa6-eHJkeACWREEAtAAsAOwArI4ubh7e8X6BIa65EVGxCSmpADGaMAD.iAQATAArAAZAA_",
            bass: "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyJgAoAERGAKjsQEpmYBqdp-t-r-gBp2AxD1btaiBGhIBDAM4LE7GKvX01mjfR0rtB-GgDKAewAOAOjQAhRZYAEYIhRIE5eIgBMHCwgFcAc0CKXzw5AjwASwA7QIBaABYAdgBWJxdSd08veL8CIJCiPPDI2ISU1IAYzXoACCIAJgAVjiA__",
            "Do Alto Down":
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PXuE0BDMngD2MAFjMAOMwDYzALiSZ85gDxltKbVm1xiOGgDKQgA4A6NACE-AZ1MACMEQokCfPEQAmd64QCuAc38Kbzw-AjwASwA7fwBaABYAdgBWBydSV3cPWJ8CAKCiHNDw6Lik5IAY-hgAf8QiACYAZYBKoA__",
            "Tenor Down":
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PXuEBQPIgDsA9gRgAsZgBxmAbGYBcaXMXMAeKtoza82pMRw0AZWEAHAHRoAQgEMAzuYAEYIhRIEbAgCaO7hAK4A5oEUvng2BHgAloKBALQALADsAKzOrqQe3nF-BEEhRDnhkTHxySkAMfQwAP-IRABMAMsAyUA__",
            "Do Alto Up":
                "IgYAwgggzAAAgDGANhyAgaBAM0EMA2ALgPYwAUACIjAFRWICU9MA1M3dU9W9QDTM9EHRs0qIEaAEa4AzjMTMYi5dSWqV1DQvU74aAMrEADgDo0AIVkmABGACm-O5IBOuQnYAm1mYWcBXAHMAx29CXGdCAEsAOwCAWgAWAHYAVlsHJ1d3DziffyDHXLCImPjklIAY1RgAf8Q7ACYAFbAgA___",
        },
        mixolydian: {
            "Do Alto Down":
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PXuWWE0AhmTwB7GAExmAHGYBsZpNozaAPGYB8ZgAJma2jtoBcOcwBYCxnDQBlEQAcAdGgBCAgM4OtYIhRIEBeEQAJlpuhACuAOaRFKF4AgR4AJYAdpEAtAAsAOwArF4-pP6BQelhBFExRGXxiakZObkAMfQwAP-IRABMAJEAvEA_",
            "Tenor Up":
                "IgYAwgggzAAAgDGANhyAgaBAMCgAXAUwDsB7AJxgAIAERGAYlsQCImq3G6BSNgMjYDkbHnSF0AJG1Z0AhGxqIEaAEYBDAM7rEbGDr11dB.XWPaj5kxbhoAyiQAOAOjQAhDY8pgCAGwLKyqoQAJpTqeGQArgDmUb6heKpkeACWRFEAtAAsAOwArJ4-fgHB6WGRMb6lCUmpGTm5ADEGdACwBABMAFEAnkA",
            "Tenor Down":
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PXuWWEBQPEQB2AewIwAmMwA4zANjNptObQB4zAPjMABMw209tALgLmALCWM4aAMqiADgDo0AIQCGAZyc6wRCiQE7kIAJjqehACuAObRFOF47gR4AJbC0QC0ACwA7ACsvv6kQaEZEQQxcURliclpmbl5ADH0MAD.iEQATACRAGZAA",
            bass: "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyJgHIAERGAKjsQEpnr2n6AadgWnYA6dr3rD6AanZt6ACna1ECNCQCGAZ3WJ2MHXvq6D--se1HzJi3DQBlAPYAHQWgBCGwQAIwRCiQKq8IgATD3VCAFcAc0iKULxVAjwASwA7SL4AFgB2AFYvH1J.QKC-MIIomKJS-MTU9OycgBiDGAB.xCIAJgAogFwgA_",
            soprano:
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PXuWWE0SAQwDOwmAExmAHGYBsZpNozaAPGYB8ZgAJma2jtoBcOcwBYCxnDQBlAPYAHAHRoAQiMdawRCiQKC8RAAmWsKEAK4A5hEUIXiCBHgAlgB2EQC0ACwA7ACsnt6kfgGBaaEEkdFEpXEJKenZOQAx9LQAsEQATACRUkA_",
            "Do Alto Up":
                "IgYAwgggzAAAgDGANhyAgaBAM0EMA2ALgPYwDkACIjAFRWICU95zd1ANMwLTMB0znav2oBqZk2oAKZpUQI0AI1wBnZYmYwNW6pp3bq-9XuMGTcNAGViAB15oAQit4ACMAFN8bhQCdchNwAmzsqE3gCuAOYRnsGEuN6EAJYAdhFcACwA7ACsrh5evv4BXCHhUZ4lcQkpaVnZADE6MAD.iG4ATABRAPxAA",
        },
    },
    "Type 2": {
        aionian: {
            "Do Alto Up":
                "IgYAwgggzAAAgDGANhyAgaBAM0EMA2ALgPYwDEACIjAKRWIBk9MA5M3dQBTNvUePtmAEmaVECNACNcAZxmJmMRcupLVK6hoXqd8NAGViABwB0aAEKyTAAjABTfHckAnXITsATazMLOArgDmAY7ehLjOhACWAHYBALQALADsAKy2Dk6u7h5xPv5BjrlhETHxySkAMaowAP-IdgBMAEsAQ0A__",
            "Do Alto Down":
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PXuE0BDMngD2MADjMAeMwD4zAASTmAQnmLas2lNoBcZuMRw0AZSEAHAHRoAQnwDO5uWCIUSBPniIATObcIBXAHMAih88PgI8AEsAOwCAWgAWAHYAVkdnUjcPTzjfAkDgolywiJj45JSAGPoYAH.EIgAmACWEoA__",
            soprano:
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PXuE0SBDAM6CYAHGYA8ZgHxmAAknMAhPMW1ZtKbQC4zcYjhoAygHsADgDo0AISEW5YIhRIF-eIgBM5gwgFcA5v4U3nj8BHgAlgB2.gC0ACwA7ACsDk6kru4esT4EAUFEOaHh0XFJyQAx9DAAoFE1RABMAIsA90A_",
            "Tenor Up":
                "IgYAwgggzAAAgDGANhyAgaBAMCgAXAUwDsB7AJxgGIAERGAUlsQDImYByNxugCjc7rcWXNgBI2NRAjQAjAIYBnBYjYxV6ums0a6OldoPw0AZRIAHAHRoAQoosACMAQA2BGWTmEAJvYV4yAK4A5kGuvnhyZHgAlkRBALQALADsAKyOLm4e3vF-gSGuuRFRsQkpqQAxmjAA.4gEAEwASwArQA_",
            "Tenor Down":
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PXuEBQPIgDsA9gRgAcZgDxmAfGYACacwCEi5bXm0ZtALjNJiOGgDKwgA4A6NACEAhgGdLCsEQokCdgQBMFDwgCuAOZBFH54dgR4AJaCQQC0ACwA7ACsLm6knj7x.gTBoUS5EVGxCSmpADH0MAD.iEQATABLACRAA",
            bass: "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyJgCoAERGAGjsQFpmYA6dp-gena70erbuwDU7WogRoSAQwDOCxOxir19NZo30dK7QfhoAygHsADhzQAhRRwAEYIhRIE5eIgBN7CwgFcAcwCKHzw5AjwASwA7AJYAFgB2AFZHZ1I3D08WXwJA4KIcsIiYuKTkgBjNGAB.xCIAJgAlgAygA_",
        },
        lydian: {
            "Do Alto Down":
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PX440BDMngD2MAPjMABMwCEzcbQB4c5gGJmAImW0ptefDQBlIQAcAdGgBCfAM6mJYIhRIE-eIgBMJ1wgFcA5n4UXnh8BHgAlgB2fgC0ACwA7ACs9o6kLm7uMd4E.oFE2SFhUbGJSQAx9DAA.4hEAEwAPgA8QA___",
            "Do Alto Up":
                "IgYAwgggzAAAgDGANhyAgaBAM0EMA2ALgPYwBkACIjAORWIAU95zApM5dQFTMCUHzOtU7w4aAEa4AzlMTMY8xdQXKl1NXNWIxAZWIAHAHRoAQtMMACMAFN818QCdchawBMLUwg4CuAc192HoS4DoQAlgB2vgC0ACwA7ACsVrb2Ti6u0Z4-.nZZwaGRMQmJADHKMAD.iNYATAB-AOdAA_",
            soprano:
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PX440SBDAM6CYAfGYACZgEJm42gDw5zAMTMARMtpTa8-GgDKAewAOAOjQAhIWYlgiFEgX54iAEwmDCAVwDmvik88fgI8AEsAO18AWgAWAHYAVjsHUmdXN2ivAj8Aoizg0MiYhMSAGPoYAH.EIgAmAG8Ad6A_",
            "Tenor Down":
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PX44BQPIgDsA9gRgB8ZgAJmAQmaTaAPAXMAxMwBEq2jNqL4aAMrCADgDo0AIQCGAZ3NSwRCiQI2BAEyl3CAVwBzAIofPBsCPABLQQCAWgAWAHYAVicXUncvWN8CQOCibLCI6Lik5IAY-hgAf8QiACYAHwBYIA___",
            "Tenor Up":
                "IgYAwgggzAAAgDGANhyAgaBAMCgAXAUwDsB7AJxgDIAERGAclsQAomq2BSNmugKjYCU3Nozo94cNACMAhgGc5iNjGWq6K9WrpalmxJIDKJAA4A6NACF5pgARgCAGwJSyMwgBMbcvGQCuAc38nLzwZMjwASyJ.AFoAFgB2AFY7R2dXDxjvP0CnLNDwqNjEpIAY9RgAf8QCACYAPwBfoA_",
            bass: "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyJgDIAERGAcjsQApnr2BSd2-gKnYBKHuyb1e8OGhIBDAM5zE7GMtX0V6tfS1LNiKQGUA9gAcAdGgBC8swAIwRCiQIy8RACa25hAK4BzPwovPBkCPABLADs.AFoAFgB2AFZ7R1IXN3cY7wJ.QKJskLCo2MSkgBj1GAB.xCIAJgA.AAWgA__",
        },
        phrygian: {
            "Tenor Up":
                "IgYAwgggzAAAgDGANhyAgaBAMCgAXAUwDsB7AJxgFIAERGAYlsQBImG2BCNgCjYHI2NOgDJBTOHDQAjAIYBnOYjYxlquivVq6WpYkkBlEgAcAdGgBC8kwAIwBADYEpZGYQAm1uXjIBXAOZ-jp54MmR4AJZEfgC0ACwA7ACstg5OLu7RXr4BjpkhYZExCYkAMeowAP-IBABMAN70QA___",
            "Do Alto Up":
                "IgYAwgggzAAAgDGANhyAgaBAM0EMA2ALgPYwCkACIjAMRWIAk9tzAhMwBTMDkzl1AMj704cNACNcAZymJmMeYuoLlS6mrmIxAZWIAHAHRoAQtIMACMAFN8V8QCdchKwBNzUwvYCuAcx-33Qlx7QgBLADsfAFoAFgB2AFZLGztHZxcoj28.W0ygkIjo-ISAGOUYAH.EKwAmAG8AaCA___",
            "Tenor Down":
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3P4YBQPIgHYB7AjAB4zADjMAuFOYAsZgEJmAAmYTaAfE2M4aAMpCADgDo0AIQCGAZzNqwRCiQLX-AEzW3CAVwDm.hTeeNYEeACWAv4AtAAsAOwArI7OpG6eMT4EAUFEWaHhUbGJSQAx9DAA.4hEAEwAXgDwQA",
            soprano:
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3P4Y0SBDAM4CYAPGYAcZgFwJzAFjMAhMwAEzMbQD46xnDQBlAPYAHAHRoAQoNMqwRCiQJ88RACYqBhAK4BzHxQ88PgI8AEsAOx8AWgAWAHYAVlt7UicXVyjPAl9.IkygkIjo-ISAGPoYAH.EIgAmAE8AY6A__",
            "Do Alto Down":
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3P4Y0BDMvAHsYAPGYAcZgFwJzAFjMAhMwAEzMbQD46xnDQBlQQAcAdGgBCvAM4mVYIhRIFeeIgBMVVwgFcA5r4pPPF4CPABLADtfAFoAFgB2AFY7B1JnVzdorwI.AKIs4NDImITEgBj6GAB.xCIAJgAvTSA__",
            bass: "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyJgBoAERGAKjsQGpnH2AKdgenYDp2tegFohzOHDQkAhgGc5idjGWr6K9WvpaliKQGUA9gAd-aAELz-AAjBEKJAjLxEAJtbmEArgHMfFDzwZAjwASwA7HxEAFgB2AFZbe1InF1cRTwJffyIMoJCIqLj4gBj1GAB.xCIAJgAvAEmgA__",
        },
        dorian: {
            "Tenor Down":
                "IgYAwgggzAAAgDGANhyAgaBAAoAYAFwCcBTAIwBtjEAERGumWup-5hlx9rt-GAUHzEAdgHtCMALgsA-CwB4LKXQAEMlgEIWqurLoK6S-GgDKIgA4A6NACEAhgGcLysMUqlCtwQBNl9ogFcAc0DKX3xbQnwASyFAgFoAFgB2AFZnVzIPbzi.QiCQ4hzwyJj45JSAGIYYAH.EYgAmfABnoA___",
            bass: "IgYAwgggzAAAgDGANhyAgaBAAoAYAFwCcBTAIwBtiYBqABERgFp7EAaFmjgOg-YYHpuvDuwZ1ECNKQCGAZ1mIOMJSobK1qhpsUaJaAMoB7AA5c0AITlcABGGKVShafmIATa7KIBXAOY.KHvjShPgAlgB2PowALADsAKy29mROLq6MnoS-.sQZQSERUXHxADFqMAD.iMQATABuAHxAA__",
            "Tenor Up":
                "IgYAwgggzAAAgDGANhyAgaBAAoAoAFwFMA7AewCcYASABERgDI7EBSZ69gcnafoAouPdm3q1ECNACMAhgGdZidjCUr6ytavqbFG8WgDKpAA4A6NACE5JgARhCAG0KTy0ogBNrs.OQCuAcz9HT3xpcnwAS2I.AFoAFgB2AFZbBycXd2ivXwDHTJCwyJiExIAYtRgAf8RCACYANwBVoA__",
            soprano:
                "IgYAwgggzAAAgDGANhyAgaBAAoAYAFwCcBTAIwBtjEAERGumWup-5hlx9rt-GNUgIYBnITAC4LAPgsAeCwl0ABFJYBCFsrrS6cugvhoAygHsADgDo0AIWHnFYYpVKEB-YgBNFQogFcA5n6UXvgChPgAlgB2fgC0ACwA7ACs9o5kLm7uMd6E.oHE2SFhUbGJSQAxDDAAoJHVAI4I2O4AywDnbUA__",
            "Do Alto Down":
                "IgYAwgggzAAAgDGANhyAgaBAAoAYAFwCcBTAIwBtjEAERGumWup-5hlx9rt-GNAQ3L4A9jAC4LAPgsAeCwl0ABFJYBCFsrrS6cugvhoAysIAOAOjQAhfgGczisMUqlC.fMQAmim0QCuAc39Kb3x-QnwASwA7fwBaABYAdgBWBycyV3cPWJ9CAKDiHNDw6Lik5IAYhhgAf8RiACZfADCgA___",
            "Do Alto Up":
                "IgYAwgggzAAAgDGANhyAgaBAAoNBDAGwBcB7GAEgAREYAyaxAUgYpYHIX6aAKdzl5jSqIEaAEZ4AzpMQsYchTXlLFNVbJUi0AZRIAHAHRoAQlIMACMAFMCVsQCc8RKwBNzkovYCuAcx-33Ijx7IgBLADsfAFoAFgB2AFZLGztHZxcoj28.W0ygkIjo-ISAGKUabCsAJgA3AEKgA_",
        },
        locrian: {
            "Do Alto Up":
                "IgYAwgggzAAAgDGANhyAgaBAM0EMA2ALgPYwCUACIjANRWIBU95zAFM09ZdZ4nT827wcAI1wBncYmYwZc6rIXzqy6UsRw0AZWIAHAHRoAQhP0ACMAFN8lkQCdchSwBMz4wnYCuAc2823hLh2hACWAHbeALQALADsAKwW1rYOTs6R7l6-NhmBweFRcfEAMQowAP-IlgBMAGMA50A_",
            bass: "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyJgEoAERGAajsQCpnr2AKdt-2-3oiYD2.eDDQkAhgGcZidjEXL6S1SvoaF6xHDQBlAPYAHAHRoAQrNMACMEQokCUvEQAmNmYQCuAc18UnnhSBHgAlgB2vgC0ACwA7ACsdg6kzq5u0V4EfgFEWcGhkTEJiQAxquIwRABMAGMAk0A___",
            "Tenor Down":
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PX4YBQPIgDsA9gRgBsZgFxmAHGaTaALDkLVtGbXm1F8NAGVhABwB0aAEIBDAM4mABGCIUSBSwIAmd64QCuAcz8KLzxLAjwAS0E.AFoAFgB2AFYHJ1JXD2jvAn9AokyQsMiYhMSAGPoYAH.EIgAmADGAcSA__",
            "Tenor Up":
                "IgYAwgggzAAAgDGANhyAgaBAMCgAXAUwDsB7AJxgEoAERGAalsQComq2AKN1umunxI35s-8GGgBGAQwDOMxGxiLldJapV0NC9YjhoAyiQAOAOjQAhWSYAEYAgBsCEslMIATazLxkArgHM.R088KTI8AEsiPwBaABYAdgBWWwcnF3dor18Ax0yQsMiYhMSAGNUYAH.EAgAmAHHMIA",
            "Do Alto Down":
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PX4Y0BDMngD2MANjMAuMwA4zcbQBYMuctpTas2vPhoAykIAOAOjQAhPgGcjAAjBEKJAnzxEAJtYuEArgHMfFDzw-AjwASwA7HwBaABYAdgBWW3tSJxdXKM8CX38iTKCQiOj4hIAY-hgAf8QiACYAMYBtIA__",
            soprano:
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PX4Y0SBDAM6CYAbGYBcZgBxm42gCwZc5bSm1ZtefDQBlAPYAHAHRoAQkOMACMEQokC.PEQAmVwYQCuAc28V3ePwEeACWAHbeALQALADsAKw2dqSOzi6RHgQ-fkQZgcHhUXHxADH0MAD.iEQATABjAP5AA___",
        },
        aeolian: {
            soprano:
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PXuE0SBDAM6CYALGYAcZgGxmAXEkz5zAHjLaU2rNrjEcNAGUA9gAcAdGgBCQswAIwRCiQL88RACa3BhAK4BzPwovPH4CPABLADs.AFoAFgB2AFZ7R1IXN3cY7wJ.QKJskLCo2MSkgBj6GAB.xCIAJgBlnyA_",
            "Tenor Up":
                "IgYAwgggzAAAgDGANhyAgaBAMCgAXAUwDsB7AJxgAoAERGAKlsQEomYBqNxu1uzugDRt-ibizY1ECNACMAhgGcFiNjFXq6azRro6V2g.DQBlEgAcAdGgBCiiwAIwBADYEZZOYQAm9hXjIArgDmQa6-eHJkeACWREEAtAAsAOwArI4ubh7e8X6BIa65EVGxCSmpADGaMAD.iAQATAArAAZAA_",
            bass: "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyJgAoAERGAKjsQEpmYBqdp-t-r-gBp2AxD1btaiBGhIBDAM4LE7GKvX01mjfR0rtB-GgDKAewAOAOjQAhRZYAEYIhRIE5eIgBMHCwgFcAc0CKXzw5AjwASwA7QIBaABYAdgBWJxdSd08veL8CIJCiPPDI2ISU1IAYzXoACCIAJgAVjiA__",
            "Do Alto Down":
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PXuE0BDMngD2MAFjMAOMwDYzALiSZ85gDxltKbVm1xiOGgDKQgA4A6NACE-AZ1MACMEQokCfPEQAmd64QCuAc38Kbzw-AjwASwA7fwBaABYAdgBWBydSV3cPWJ8CAKCiHNDw6Lik5IAY-hgAf8QiACYAZYBKoA__",
            "Tenor Down":
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PXuEBQPIgDsA9gRgAsZgBxmAbGYBcaXMXMAeKtoza82pMRw0AZWEAHAHRoAQgEMAzuYAEYIhRIEbAgCaO7hAK4A5oEUvng2BHgAloKBALQALADsAKzOrqQe3nF-BEEhRDnhkTHxySkAMfQwAP-IRABMAMsAyUA__",
            "Do Alto Up":
                "IgYAwgggzAAAgDGANhyAgaBAM0EMA2ALgPYwAUACIjAFRWICU9MA1M3dU9W9QDTM9EHRs0qIEaAEa4AzjMTMYi5dSWqV1DQvU74aAMrEADgDo0AIVkmABGACm-O5IBOuQnYAm1mYWcBXAHMAx29CXGdCAEsAOwCAWgAWAHYAVlsHJ1d3DziffyDHXLCImPjklIAY1RgAf8Q7ACYAFbAgA___",
        },
        mixolydian: {
            "Do Alto Down":
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PXuWWE0AhmTwB7GAExmAHGYBsZpNozaAPGYB8ZgAJma2jtoBcOcwBYCxnDQBlEQAcAdGgBCAgM4OtYIhRIEBeEQAJlpuhACuAOaRFKF4AgR4AJYAdpEAtAAsAOwArF4-pP6BQelhBFExRGXxiakZObkAMfQwAP-IRABMAJEAvEA_",
            "Tenor Up":
                "IgYAwgggzAAAgDGANhyAgaBAMCgAXAUwDsB7AJxgAIAERGAYlsQCImq3G6BSNgMjYDkbHnSF0AJG1Z0AhGxqIEaAEYBDAM7rEbGDr11dB.XWPaj5kxbhoAyiQAOAOjQAhDY8pgCAGwLKyqoQAJpTqeGQArgDmUb6heKpkeACWRFEAtAAsAOwArJ4-fgHB6WGRMb6lCUmpGTm5ADEGdACwBABMAFEAnkA",
            "Tenor Down":
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PXuWWEBQPEQB2AewIwAmMwA4zANjNptObQB4zAPjMABMw209tALgLmALCWM4aAMqiADgDo0AIQCGAZyc6wRCiQE7kIAJjqehACuAObRFOF47gR4AJbC0QC0ACwA7ACsvv6kQaEZEQQxcURliclpmbl5ADH0MAD.iEQATACRAGZAA",
            bass: "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyJgHIAERGAKjsQEpnr2n6AadgWnYA6dr3rD6AanZt6ACna1ECNCQCGAZ3WJ2MHXvq6D--se1HzJi3DQBlAPYAHQWgBCGwQAIwRCiQKq8IgATD3VCAFcAc0iKULxVAjwASwA7SL4AFgB2AFYvH1J.QKC-MIIomKJS-MTU9OycgBiDGAB.xCIAJgAogFwgA_",
            soprano:
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PXuWWE0SAQwDOwmAExmAHGYBsZpNozaAPGYB8ZgAJma2jtoBcOcwBYCxnDQBlAPYAHAHRoAQiMdawRCiQKC8RAAmWsKEAK4A5hEUIXiCBHgAlgB2EQC0ACwA7ACsnt6kfgGBaaEEkdFEpXEJKenZOQAx9LQAsEQATACRUkA_",
            "Do Alto Up":
                "IgYAwgggzAAAgDGANhyAgaBAM0EMA2ALgPYwDkACIjAFRWICU95zd1ANMwLTMB0znav2oBqZk2oAKZpUQI0AI1wBnZYmYwNW6pp3bq-9XuMGTcNAGViAB15oAQit4ACMAFN8bhQCdchNwAmzsqE3gCuAOYRnsGEuN6EAJYAdhFcACwA7ACsrh5evv4BXCHhUZ4lcQkpaVnZADE6MAD.iG4ATABRAPxAA",
        },
    },
    "Type 3": {
        aionian: {
            "Do Alto Up":
                "IgYAwgggzAAAgDGANhyAgaBAM0EMA2ALgPYwDEACIjAKRWIBk9MA5M3dQBTNvUePtmAEmaVECNACNcAZxmJmMRcupLVK6hoXqd8NAGViABwB0aAEKyTAAjABTfHckAnXITsATazMLOArgDmAY7ehLjOhACWAHYBALQALADsAKy2Dk6u7h5xPv5BjrlhETHxySkAMaowAP-IdgBMAEsAQ0A__",
            "Do Alto Down":
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PXuE0BDMngD2MADjMAeMwD4zAASTmAQnmLas2lNoBcZuMRw0AZSEAHAHRoAQnwDO5uWCIUSBPniIATObcIBXAHMAih88PgI8AEsAOwCAWgAWAHYAVkdnUjcPTzjfAkDgolywiJj45JSAGPoYAH.EIgAmACWEoA__",
            soprano:
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PXuE0SBDAM6CYAHGYA8ZgHxmAAknMAhPMW1ZtKbQC4zcYjhoAygHsADgDo0AISEW5YIhRIF-eIgBM5gwgFcA5v4U3nj8BHgAlgB2.gC0ACwA7ACsDk6kru4esT4EAUFEOaHh0XFJyQAx9DAAoFE1RABMAIsA90A_",
            "Tenor Up":
                "IgYAwgggzAAAgDGANhyAgaBAMCgAXAUwDsB7AJxgGIAERGAUlsQDImYByNxugCjc7rcWXNgBI2NRAjQAjAIYBnBYjYxV6ums0a6OldoPw0AZRIAHAHRoAQoosACMAQA2BGWTmEAJvYV4yAK4A5kGuvnhyZHgAlkRBALQALADsAKyOLm4e3vF-gSGuuRFRsQkpqQAxmjAA.4gEAEwASwArQA_",
            "Tenor Down":
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PXuEBQPIgDsA9gRgAcZgDxmAfGYACacwCEi5bXm0ZtALjNJiOGgDKwgA4A6NACEAhgGdLCsEQokCdgQBMFDwgCuAOZBFH54dgR4AJaCQQC0ACwA7ACsLm6knj7x.gTBoUS5EVGxCSmpADH0MAD.iEQATABLACRAA",
            bass: "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyJgCoAERGAGjsQFpmYA6dp-gena70erbuwDU7WogRoSAQwDOCxOxir19NZo30dK7QfhoAygHsADhzQAhRRwAEYIhRIE5eIgBN7CwgFcAcwCKHzw5AjwASwA7AJYAFgB2AFZHZ1I3D08WXwJA4KIcsIiYuKTkgBjNGAB.xCIAJgAlgAygA_",
        },
        lydian: {
            "Do Alto Down":
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PX440BDMngD2MAPjMABMwCEzcbQB4c5gGJmAImW0ptefDQBlIQAcAdGgBCfAM6mJYIhRIE-eIgBMJ1wgFcA5n4UXnh8BHgAlgB2fgC0ACwA7ACs9o6kLm7uMd4E.oFE2SFhUbGJSQAx9DAA.4hEAEwAPgA8QA___",
            "Do Alto Up":
                "IgYAwgggzAAAgDGANhyAgaBAM0EMA2ALgPYwBkACIjAORWIAU95zApM5dQFTMCUHzOtU7w4aAEa4AzlMTMY8xdQXKl1NXNWIxAZWIAHAHRoAQtMMACMAFN818QCdchawBMLUwg4CuAc192HoS4DoQAlgB2vgC0ACwA7ACsVrb2Ti6u0Z4-.nZZwaGRMQmJADHKMAD.iNYATAB-AOdAA_",
            soprano:
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PX440SBDAM6CYAfGYACZgEJm42gDw5zAMTMARMtpTa8-GgDKAewAOAOjQAhIWYlgiFEgX54iAEwmDCAVwDmvik88fgI8AEsAO18AWgAWAHYAVjsHUmdXN2ivAj8Aoizg0MiYhMSAGPoYAH.EIgAmAG8Ad6A_",
            "Tenor Down":
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PX44BQPIgDsA9gRgB8ZgAJmAQmaTaAPAXMAxMwBEq2jNqL4aAMrCADgDo0AIQCGAZ3NSwRCiQI2BAEyl3CAVwBzAIofPBsCPABLQQCAWgAWAHYAVicXUncvWN8CQOCibLCI6Lik5IAY-hgAf8QiACYAHwBYIA___",
            "Tenor Up":
                "IgYAwgggzAAAgDGANhyAgaBAMCgAXAUwDsB7AJxgDIAERGAclsQAomq2BSNmugKjYCU3Nozo94cNACMAhgGc5iNjGWq6K9WrpalmxJIDKJAA4A6NACF5pgARgCAGwJSyMwgBMbcvGQCuAc38nLzwZMjwASyJ.AFoAFgB2AFY7R2dXDxjvP0CnLNDwqNjEpIAY9RgAf8QCACYAPwBfoA_",
            bass: "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyJgDIAERGAcjsQApnr2BSd2-gKnYBKHuyb1e8OGhIBDAM5zE7GMtX0V6tfS1LNiKQGUA9gAcAdGgBC8swAIwRCiQIy8RACa25hAK4BzPwovPBkCPABLADs.AFoAFgB2AFZ7R1IXN3cY7wJ.QKJskLCo2MSkgBj1GAB.xCIAJgA.AAWgA__",
        },
        phrygian: {
            "Tenor Up":
                "IgYAwgggzAAAgDGANhyAgaBAMCgAXAUwDsB7AJxgFIAERGAYlsQBImG2BCNgCjYHI2NOgDJBTOHDQAjAIYBnOYjYxlquivVq6WpYkkBlEgAcAdGgBC8kwAIwBADYEpZGYQAm1uXjIBXAOZ-jp54MmR4AJZEfgC0ACwA7ACstg5OLu7RXr4BjpkhYZExCYkAMeowAP-IBABMAN70QA___",
            "Do Alto Up":
                "IgYAwgggzAAAgDGANhyAgaBAM0EMA2ALgPYwCkACIjAMRWIAk9tzAhMwBTMDkzl1AMj704cNACNcAZymJmMeYuoLlS6mrmIxAZWIAHAHRoAQtIMACMAFN8V8QCdchKwBNzUwvYCuAcx-33Qlx7QgBLADsfAFoAFgB2AFZLGztHZxcoj28.W0ygkIjo-ISAGOUYAH.EKwAmAG8AaCA___",
            "Tenor Down":
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3P4YBQPIgHYB7AjAB4zADjMAuFOYAsZgEJmAAmYTaAfE2M4aAMpCADgDo0AIQCGAZzNqwRCiQLX-AEzW3CAVwDm.hTeeNYEeACWAv4AtAAsAOwArI7OpG6eMT4EAUFEWaHhUbGJSQAx9DAA.4hEAEwAXgDwQA",
            soprano:
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3P4Y0SBDAM4CYAPGYAcZgFwJzAFjMAhMwAEzMbQD46xnDQBlAPYAHAHRoAQoNMqwRCiQJ88RACYqBhAK4BzHxQ88PgI8AEsAOx8AWgAWAHYAVlt7UicXVyjPAl9.IkygkIjo-ISAGPoYAH.EIgAmAE8AY6A__",
            "Do Alto Down":
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3P4Y0BDMvAHsYAPGYAcZgFwJzAFjMAhMwAEzMbQD46xnDQBlQQAcAdGgBCvAM4mVYIhRIFeeIgBMVVwgFcA5r4pPPF4CPABLADtfAFoAFgB2AFY7B1JnVzdorwI.AKIs4NDImITEgBj6GAB.xCIAJgAvTSA__",
            bass: "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyJgBoAERGAKjsQGpnH2AKdgenYDp2tegFohzOHDQkAhgGc5idjGWr6K9WvpaliKQGUA9gAd-aAELz-AAjBEKJAjLxEAJtbmEArgHMfFDzwZAjwASwA7HxEAFgB2AFZbe1InF1cRTwJffyIMoJCIqLj4gBj1GAB.xCIAJgAvAEmgA__",
        },
        dorian: {
            "Tenor Down":
                "IgYAwgggzAAAgDGANhyAgaBAAoAYAFwCcBTAIwBtjEAERGumWup-5hlx9rt-GAUHzEAdgHtCMALgsA-CwB4LKXQAEMlgEIWqurLoK6S-GgDKIgA4A6NACEAhgGcLysMUqlCtwQBNl9ogFcAc0DKX3xbQnwASyFAgFoAFgB2AFZnVzIPbzi.QiCQ4hzwyJj45JSAGIYYAH.EYgAmfABnoA___",
            bass: "IgYAwgggzAAAgDGANhyAgaBAAoAYAFwCcBTAIwBtiYBqABERgFp7EAaFmjgOg-YYHpuvDuwZ1ECNKQCGAZ1mIOMJSobK1qhpsUaJaAMoB7AA5c0AITlcABGGKVShafmIATa7KIBXAOY.KHvjShPgAlgB2PowALADsAKy29mROLq6MnoS-.sQZQSERUXHxADFqMAD.iMQATABuAHxAA__",
            "Tenor Up":
                "IgYAwgggzAAAgDGANhyAgaBAAoAoAFwFMA7AewCcYASABERgDI7EBSZ69gcnafoAouPdm3q1ECNACMAhgGdZidjCUr6ytavqbFG8WgDKpAA4A6NACE5JgARhCAG0KTy0ogBNrs.OQCuAcz9HT3xpcnwAS2I.AFoAFgB2AFZbBycXd2ivXwDHTJCwyJiExIAYtRgAf8RCACYANwBVoA__",
            soprano:
                "IgYAwgggzAAAgDGANhyAgaBAAoAYAFwCcBTAIwBtjEAERGumWup-5hlx9rt-GNUgIYBnITAC4LAPgsAeCwl0ABFJYBCFsrrS6cugvhoAygHsADgDo0AIWHnFYYpVKEB-YgBNFQogFcA5n6UXvgChPgAlgB2fgC0ACwA7ACs9o5kLm7uMd6E.oHE2SFhUbGJSQAxDDAAoJHVAI4I2O4AywDnbUA__",
            "Do Alto Down":
                "IgYAwgggzAAAgDGANhyAgaBAAoAYAFwCcBTAIwBtjEAERGumWup-5hlx9rt-GNAQ3L4A9jAC4LAPgsAeCwl0ABFJYBCFsrrS6cugvhoAysIAOAOjQAhfgGczisMUqlC.fMQAmim0QCuAc39Kb3x-QnwASwA7fwBaABYAdgBWBycyV3cPWJ9CAKDiHNDw6Lik5IAYhhgAf8RiACZfADCgA___",
            "Do Alto Up":
                "IgYAwgggzAAAgDGANhyAgaBAAoNBDAGwBcB7GAEgAREYAyaxAUgYpYHIX6aAKdzl5jSqIEaAEZ4AzpMQsYchTXlLFNVbJUi0AZRIAHAHRoAQlIMACMAFMCVsQCc8RKwBNzkovYCuAcx-33Ijx7IgBLADsfAFoAFgB2AFZLGztHZxcoj28.W0ygkIjo-ISAGKUabCsAJgA3AEKgA_",
        },
        locrian: {
            "Do Alto Up":
                "IgYAwgggzAAAgDGANhyAgaBAM0EMA2ALgPYwCUACIjANRWIBU95zAFM09ZdZ4nT827wcAI1wBncYmYwZc6rIXzqy6UsRw0AZWIAHAHRoAQhP0ACMAFN8lkQCdchSwBMz4wnYCuAc2823hLh2hACWAHbeALQALADsAKwW1rYOTs6R7l6-NhmBweFRcfEAMQowAP-IlgBMAGMA50A_",
            bass: "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyJgEoAERGAajsQCpnr2AKdt-2-3oiYD2.eDDQkAhgGcZidjEXL6S1SvoaF6xHDQBlAPYAHAHRoAQrNMACMEQokCUvEQAmNmYQCuAc18UnnhSBHgAlgB2vgC0ACwA7ACsdg6kzq5u0V4EfgFEWcGhkTEJiQAxquIwRABMAGMAk0A___",
            "Tenor Down":
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PX4YBQPIgDsA9gRgBsZgFxmAHGaTaALDkLVtGbXm1F8NAGVhABwB0aAEIBDAM4mABGCIUSBSwIAmd64QCuAcz8KLzxLAjwAS0E.AFoAFgB2AFYHJ1JXD2jvAn9AokyQsMiYhMSAGPoYAH.EIgAmADGAcSA__",
            "Tenor Up":
                "IgYAwgggzAAAgDGANhyAgaBAMCgAXAUwDsB7AJxgEoAERGAalsQComq2AKN1umunxI35s-8GGgBGAQwDOMxGxiLldJapV0NC9YjhoAyiQAOAOjQAhWSYAEYAgBsCEslMIATazLxkArgHM.R088KTI8AEsiPwBaABYAdgBWWwcnF3dor18Ax0yQsMiYhMSAGNUYAH.EAgAmAHHMIA",
            "Do Alto Down":
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PX4Y0BDMngD2MANjMAuMwA4zcbQBYMuctpTas2vPhoAykIAOAOjQAhPgGcjAAjBEKJAnzxEAJtYuEArgHMfFDzw-AjwASwA7HwBaABYAdgBWW3tSJxdXKM8CX38iTKCQiOj4hIAY-hgAf8QiACYAMYBtIA__",
            soprano:
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PX4Y0SBDAM6CYAbGYBcZgBxm42gCwZc5bSm1ZtefDQBlAPYAHAHRoAQkOMACMEQokC.PEQAmVwYQCuAc28V3ePwEeACWAHbeALQALADsAKw2dqSOzi6RHgQ-fkQZgcHhUXHxADH0MAD.iEQATABjAP5AA___",
        },
        aeolian: {
            soprano:
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PXuE0SBDAM6CYALGYAcZgGxmAXEkz5zAHjLaU2rNrjEcNAGUA9gAcAdGgBCQswAIwRCiQL88RACa3BhAK4BzPwovPH4CPABLADs.AFoAFgB2AFZ7R1IXN3cY7wJ.QKJskLCo2MSkgBj6GAB.xCIAJgBlnyA_",
            "Tenor Up":
                "IgYAwgggzAAAgDGANhyAgaBAMCgAXAUwDsB7AJxgAoAERGAKlsQEomYBqNxu1uzugDRt-ibizY1ECNACMAhgGcFiNjFXq6azRro6V2g.DQBlEgAcAdGgBCiiwAIwBADYEZZOYQAm9hXjIArgDmQa6-eHJkeACWREEAtAAsAOwArI4ubh7e8X6BIa65EVGxCSmpADGaMAD.iAQATAArAAZAA_",
            bass: "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyJgAoAERGAKjsQEpmYBqdp-t-r-gBp2AxD1btaiBGhIBDAM4LE7GKvX01mjfR0rtB-GgDKAewAOAOjQAhRZYAEYIhRIE5eIgBMHCwgFcAc0CKXzw5AjwASwA7QIBaABYAdgBWJxdSd08veL8CIJCiPPDI2ISU1IAYzXoACCIAJgAVjiA__",
            "Do Alto Down":
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PXuE0BDMngD2MAFjMAOMwDYzALiSZ85gDxltKbVm1xiOGgDKQgA4A6NACE-AZ1MACMEQokCfPEQAmd64QCuAc38Kbzw-AjwASwA7fwBaABYAdgBWBydSV3cPWJ8CAKCiHNDw6Lik5IAY-hgAf8QiACYAZYBKoA__",
            "Tenor Down":
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PXuEBQPIgDsA9gRgAsZgBxmAbGYBcaXMXMAeKtoza82pMRw0AZWEAHAHRoAQgEMAzuYAEYIhRIEbAgCaO7hAK4A5oEUvng2BHgAloKBALQALADsAKzOrqQe3nF-BEEhRDnhkTHxySkAMfQwAP-IRABMAMsAyUA__",
            "Do Alto Up":
                "IgYAwgggzAAAgDGANhyAgaBAM0EMA2ALgPYwAUACIjAFRWICU9MA1M3dU9W9QDTM9EHRs0qIEaAEa4AzjMTMYi5dSWqV1DQvU74aAMrEADgDo0AIVkmABGACm-O5IBOuQnYAm1mYWcBXAHMAx29CXGdCAEsAOwCAWgAWAHYAVlsHJ1d3DziffyDHXLCImPjklIAY1RgAf8Q7ACYAFbAgA___",
        },
        mixolydian: {
            "Do Alto Down":
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PXuWWE0AhmTwB7GAExmAHGYBsZpNozaAPGYB8ZgAJma2jtoBcOcwBYCxnDQBlEQAcAdGgBCAgM4OtYIhRIEBeEQAJlpuhACuAOaRFKF4AgR4AJYAdpEAtAAsAOwArF4-pP6BQelhBFExRGXxiakZObkAMfQwAP-IRABMAJEAvEA_",
            "Tenor Up":
                "IgYAwgggzAAAgDGANhyAgaBAMCgAXAUwDsB7AJxgAIAERGAYlsQCImq3G6BSNgMjYDkbHnSF0AJG1Z0AhGxqIEaAEYBDAM7rEbGDr11dB.XWPaj5kxbhoAyiQAOAOjQAhDY8pgCAGwLKyqoQAJpTqeGQArgDmUb6heKpkeACWRFEAtAAsAOwArJ4-fgHB6WGRMb6lCUmpGTm5ADEGdACwBABMAFEAnkA",
            "Tenor Down":
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PXuWWEBQPEQB2AewIwAmMwA4zANjNptObQB4zAPjMABMw209tALgLmALCWM4aAMqiADgDo0AIQCGAZyc6wRCiQE7kIAJjqehACuAObRFOF47gR4AJbC0QC0ACwA7ACsvv6kQaEZEQQxcURliclpmbl5ADH0MAD.iEQATACRAGZAA",
            bass: "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyJgHIAERGAKjsQEpnr2n6AadgWnYA6dr3rD6AanZt6ACna1ECNCQCGAZ3WJ2MHXvq6D--se1HzJi3DQBlAPYAHQWgBCGwQAIwRCiQKq8IgATD3VCAFcAc0iKULxVAjwASwA7SL4AFgB2AFYvH1J.QKC-MIIomKJS-MTU9OycgBiDGAB.xCIAJgAogFwgA_",
            soprano:
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PXuWWE0SAQwDOwmAExmAHGYBsZpNozaAPGYB8ZgAJma2jtoBcOcwBYCxnDQBlAPYAHAHRoAQiMdawRCiQKC8RAAmWsKEAK4A5hEUIXiCBHgAlgB2EQC0ACwA7ACsnt6kfgGBaaEEkdFEpXEJKenZOQAx9LQAsEQATACRUkA_",
            "Do Alto Up":
                "IgYAwgggzAAAgDGANhyAgaBAM0EMA2ALgPYwDkACIjAFRWICU95zd1ANMwLTMB0znav2oBqZk2oAKZpUQI0AI1wBnZYmYwNW6pp3bq-9XuMGTcNAGViAB15oAQit4ACMAFN8bhQCdchNwAmzsqE3gCuAOYRnsGEuN6EAJYAdhFcACwA7ACsrh5evv4BXCHhUZ4lcQkpaVnZADE6MAD.iG4ATABRAPxAA",
        },
    },
    "Type 4": {
        aionian: {
            "Do Alto Up":
                "IgYAwgggzAAAgDGANhyAgaBAM0EMA2ALgPYwDEACIjAKRWIBk9MA5M3dQBTNvUePtmAEmaVECNACNcAZxmJmMRcupLVK6hoXqd8NAGViABwB0aAEKyTAAjABTfHckAnXITsATazMLOArgDmAY7ehLjOhACWAHYBALQALADsAKy2Dk6u7h5xPv5BjrlhETHxySkAMaowAP-IdgBMAEsAQ0A__",
            "Do Alto Down":
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PXuE0BDMngD2MADjMAeMwD4zAASTmAQnmLas2lNoBcZuMRw0AZSEAHAHRoAQnwDO5uWCIUSBPniIATObcIBXAHMAih88PgI8AEsAOwCAWgAWAHYAVkdnUjcPTzjfAkDgolywiJj45JSAGPoYAH.EIgAmACWEoA__",
            soprano:
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PXuE0SBDAM6CYAHGYA8ZgHxmAAknMAhPMW1ZtKbQC4zcYjhoAygHsADgDo0AISEW5YIhRIF-eIgBM5gwgFcA5v4U3nj8BHgAlgB2.gC0ACwA7ACsDk6kru4esT4EAUFEOaHh0XFJyQAx9DAAoFE1RABMAIsA90A_",
            "Tenor Up":
                "IgYAwgggzAAAgDGANhyAgaBAMCgAXAUwDsB7AJxgGIAERGAUlsQDImYByNxugCjc7rcWXNgBI2NRAjQAjAIYBnBYjYxV6ums0a6OldoPw0AZRIAHAHRoAQoosACMAQA2BGWTmEAJvYV4yAK4A5kGuvnhyZHgAlkRBALQALADsAKyOLm4e3vF-gSGuuRFRsQkpqQAxmjAA.4gEAEwASwArQA_",
            "Tenor Down":
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PXuEBQPIgDsA9gRgAcZgDxmAfGYACacwCEi5bXm0ZtALjNJiOGgDKwgA4A6NACEAhgGdLCsEQokCdgQBMFDwgCuAOZBFH54dgR4AJaCQQC0ACwA7ACsLm6knj7x.gTBoUS5EVGxCSmpADH0MAD.iEQATABLACRAA",
            bass: "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyJgCoAERGAGjsQFpmYA6dp-gena70erbuwDU7WogRoSAQwDOCxOxir19NZo30dK7QfhoAygHsADhzQAhRRwAEYIhRIE5eIgBN7CwgFcAcwCKHzw5AjwASwA7AJYAFgB2AFZHZ1I3D08WXwJA4KIcsIiYuKTkgBjNGAB.xCIAJgAlgAygA_",
        },
        lydian: {
            "Do Alto Down":
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PX440BDMngD2MAPjMABMwCEzcbQB4c5gGJmAImW0ptefDQBlIQAcAdGgBCfAM6mJYIhRIE-eIgBMJ1wgFcA5n4UXnh8BHgAlgB2fgC0ACwA7ACs9o6kLm7uMd4E.oFE2SFhUbGJSQAx9DAA.4hEAEwAPgA8QA___",
            "Do Alto Up":
                "IgYAwgggzAAAgDGANhyAgaBAM0EMA2ALgPYwBkACIjAORWIAU95zApM5dQFTMCUHzOtU7w4aAEa4AzlMTMY8xdQXKl1NXNWIxAZWIAHAHRoAQtMMACMAFN818QCdchawBMLUwg4CuAc192HoS4DoQAlgB2vgC0ACwA7ACsVrb2Ti6u0Z4-.nZZwaGRMQmJADHKMAD.iNYATAB-AOdAA_",
            soprano:
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PX440SBDAM6CYAfGYACZgEJm42gDw5zAMTMARMtpTa8-GgDKAewAOAOjQAhIWYlgiFEgX54iAEwmDCAVwDmvik88fgI8AEsAO18AWgAWAHYAVjsHUmdXN2ivAj8Aoizg0MiYhMSAGPoYAH.EIgAmAG8Ad6A_",
            "Tenor Down":
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PX44BQPIgDsA9gRgB8ZgAJmAQmaTaAPAXMAxMwBEq2jNqL4aAMrCADgDo0AIQCGAZ3NSwRCiQI2BAEyl3CAVwBzAIofPBsCPABLQQCAWgAWAHYAVicXUncvWN8CQOCibLCI6Lik5IAY-hgAf8QiACYAHwBYIA___",
            "Tenor Up":
                "IgYAwgggzAAAgDGANhyAgaBAMCgAXAUwDsB7AJxgDIAERGAclsQAomq2BSNmugKjYCU3Nozo94cNACMAhgGc5iNjGWq6K9WrpalmxJIDKJAA4A6NACF5pgARgCAGwJSyMwgBMbcvGQCuAc38nLzwZMjwASyJ.AFoAFgB2AFY7R2dXDxjvP0CnLNDwqNjEpIAY9RgAf8QCACYAPwBfoA_",
            bass: "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyJgDIAERGAcjsQApnr2BSd2-gKnYBKHuyb1e8OGhIBDAM5zE7GMtX0V6tfS1LNiKQGUA9gAcAdGgBC8swAIwRCiQIy8RACa25hAK4BzPwovPBkCPABLADs.AFoAFgB2AFZ7R1IXN3cY7wJ.QKJskLCo2MSkgBj1GAB.xCIAJgA.AAWgA__",
        },
        phrygian: {
            "Tenor Up":
                "IgYAwgggzAAAgDGANhyAgaBAMCgAXAUwDsB7AJxgFIAERGAYlsQBImG2BCNgCjYHI2NOgDJBTOHDQAjAIYBnOYjYxlquivVq6WpYkkBlEgAcAdGgBC8kwAIwBADYEpZGYQAm1uXjIBXAOZ-jp54MmR4AJZEfgC0ACwA7ACstg5OLu7RXr4BjpkhYZExCYkAMeowAP-IBABMAN70QA___",
            "Do Alto Up":
                "IgYAwgggzAAAgDGANhyAgaBAM0EMA2ALgPYwCkACIjAMRWIAk9tzAhMwBTMDkzl1AMj704cNACNcAZymJmMeYuoLlS6mrmIxAZWIAHAHRoAQtIMACMAFN8V8QCdchKwBNzUwvYCuAcx-33Qlx7QgBLADsfAFoAFgB2AFZLGztHZxcoj28.W0ygkIjo-ISAGOUYAH.EKwAmAG8AaCA___",
            "Tenor Down":
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3P4YBQPIgHYB7AjAB4zADjMAuFOYAsZgEJmAAmYTaAfE2M4aAMpCADgDo0AIQCGAZzNqwRCiQLX-AEzW3CAVwDm.hTeeNYEeACWAv4AtAAsAOwArI7OpG6eMT4EAUFEWaHhUbGJSQAx9DAA.4hEAEwAXgDwQA",
            soprano:
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3P4Y0SBDAM4CYAPGYAcZgFwJzAFjMAhMwAEzMbQD46xnDQBlAPYAHAHRoAQoNMqwRCiQJ88RACYqBhAK4BzHxQ88PgI8AEsAOx8AWgAWAHYAVlt7UicXVyjPAl9.IkygkIjo-ISAGPoYAH.EIgAmAE8AY6A__",
            "Do Alto Down":
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3P4Y0BDMvAHsYAPGYAcZgFwJzAFjMAhMwAEzMbQD46xnDQBlQQAcAdGgBCvAM4mVYIhRIFeeIgBMVVwgFcA5r4pPPF4CPABLADtfAFoAFgB2AFY7B1JnVzdorwI.AKIs4NDImITEgBj6GAB.xCIAJgAvTSA__",
            bass: "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyJgBoAERGAKjsQGpnH2AKdgenYDp2tegFohzOHDQkAhgGc5idjGWr6K9WvpaliKQGUA9gAd-aAELz-AAjBEKJAjLxEAJtbmEArgHMfFDzwZAjwASwA7HxEAFgB2AFZbe1InF1cRTwJffyIMoJCIqLj4gBj1GAB.xCIAJgAvAEmgA__",
        },
        dorian: {
            "Tenor Down":
                "IgYAwgggzAAAgDGANhyAgaBAAoAYAFwCcBTAIwBtjEAERGumWup-5hlx9rt-GAUHzEAdgHtCMALgsA-CwB4LKXQAEMlgEIWqurLoK6S-GgDKIgA4A6NACEAhgGcLysMUqlCtwQBNl9ogFcAc0DKX3xbQnwASyFAgFoAFgB2AFZnVzIPbzi.QiCQ4hzwyJj45JSAGIYYAH.EYgAmfABnoA___",
            bass: "IgYAwgggzAAAgDGANhyAgaBAAoAYAFwCcBTAIwBtiYBqABERgFp7EAaFmjgOg-YYHpuvDuwZ1ECNKQCGAZ1mIOMJSobK1qhpsUaJaAMoB7AA5c0AITlcABGGKVShafmIATa7KIBXAOY.KHvjShPgAlgB2PowALADsAKy29mROLq6MnoS-.sQZQSERUXHxADFqMAD.iMQATABuAHxAA__",
            "Tenor Up":
                "IgYAwgggzAAAgDGANhyAgaBAAoAoAFwFMA7AewCcYASABERgDI7EBSZ69gcnafoAouPdm3q1ECNACMAhgGdZidjCUr6ytavqbFG8WgDKpAA4A6NACE5JgARhCAG0KTy0ogBNrs.OQCuAcz9HT3xpcnwAS2I.AFoAFgB2AFZbBycXd2ivXwDHTJCwyJiExIAYtRgAf8RCACYANwBVoA__",
            soprano:
                "IgYAwgggzAAAgDGANhyAgaBAAoAYAFwCcBTAIwBtjEAERGumWup-5hlx9rt-GNUgIYBnITAC4LAPgsAeCwl0ABFJYBCFsrrS6cugvhoAygHsADgDo0AIWHnFYYpVKEB-YgBNFQogFcA5n6UXvgChPgAlgB2fgC0ACwA7ACs9o5kLm7uMd6E.oHE2SFhUbGJSQAxDDAAoJHVAI4I2O4AywDnbUA__",
            "Do Alto Down":
                "IgYAwgggzAAAgDGANhyAgaBAAoAYAFwCcBTAIwBtjEAERGumWup-5hlx9rt-GNAQ3L4A9jAC4LAPgsAeCwl0ABFJYBCFsrrS6cugvhoAysIAOAOjQAhfgGczisMUqlC.fMQAmim0QCuAc39Kb3x-QnwASwA7fwBaABYAdgBWBycyV3cPWJ9CAKDiHNDw6Lik5IAYhhgAf8RiACZfADCgA___",
            "Do Alto Up":
                "IgYAwgggzAAAgDGANhyAgaBAAoNBDAGwBcB7GAEgAREYAyaxAUgYpYHIX6aAKdzl5jSqIEaAEZ4AzpMQsYchTXlLFNVbJUi0AZRIAHAHRoAQlIMACMAFMCVsQCc8RKwBNzkovYCuAcx-33Ijx7IgBLADsfAFoAFgB2AFZLGztHZxcoj28.W0ygkIjo-ISAGKUabCsAJgA3AEKgA_",
        },
        locrian: {
            "Do Alto Up":
                "IgYAwgggzAAAgDGANhyAgaBAM0EMA2ALgPYwCUACIjANRWIBU95zAFM09ZdZ4nT827wcAI1wBncYmYwZc6rIXzqy6UsRw0AZWIAHAHRoAQhP0ACMAFN8lkQCdchSwBMz4wnYCuAc2823hLh2hACWAHbeALQALADsAKwW1rYOTs6R7l6-NhmBweFRcfEAMQowAP-IlgBMAGMA50A_",
            bass: "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyJgEoAERGAajsQCpnr2AKdt-2-3oiYD2.eDDQkAhgGcZidjEXL6S1SvoaF6xHDQBlAPYAHAHRoAQrNMACMEQokCUvEQAmNmYQCuAc18UnnhSBHgAlgB2vgC0ACwA7ACsdg6kzq5u0V4EfgFEWcGhkTEJiQAxquIwRABMAGMAk0A___",
            "Tenor Down":
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PX4YBQPIgDsA9gRgBsZgFxmAHGaTaALDkLVtGbXm1F8NAGVhABwB0aAEIBDAM4mABGCIUSBSwIAmd64QCuAcz8KLzxLAjwAS0E.AFoAFgB2AFYHJ1JXD2jvAn9AokyQsMiYhMSAGPoYAH.EIgAmADGAcSA__",
            "Tenor Up":
                "IgYAwgggzAAAgDGANhyAgaBAMCgAXAUwDsB7AJxgEoAERGAalsQComq2AKN1umunxI35s-8GGgBGAQwDOMxGxiLldJapV0NC9YjhoAyiQAOAOjQAhWSYAEYAgBsCEslMIATazLxkArgHM.R088KTI8AEsiPwBaABYAdgBWWwcnF3dor18Ax0yQsMiYhMSAGNUYAH.EAgAmAHHMIA",
            "Do Alto Down":
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PX4Y0BDMngD2MANjMAuMwA4zcbQBYMuctpTas2vPhoAykIAOAOjQAhPgGcjAAjBEKJAnzxEAJtYuEArgHMfFDzw-AjwASwA7HwBaABYAdgBWW3tSJxdXKM8CX38iTKCQiOj4hIAY-hgAf8QiACYAMYBtIA__",
            soprano:
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PX4Y0SBDAM6CYAbGYBcZgBxm42gCwZc5bSm1ZtefDQBlAPYAHAHRoAQkOMACMEQokC.PEQAmVwYQCuAc28V3ePwEeACWAHbeALQALADsAKw2dqSOzi6RHgQ-fkQZgcHhUXHxADH0MAD.iEQATABjAP5AA___",
        },
        aeolian: {
            soprano:
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PXuE0SBDAM6CYALGYAcZgGxmAXEkz5zAHjLaU2rNrjEcNAGUA9gAcAdGgBCQswAIwRCiQL88RACa3BhAK4BzPwovPH4CPABLADs.AFoAFgB2AFZ7R1IXN3cY7wJ.QKJskLCo2MSkgBj6GAB.xCIAJgBlnyA_",
            "Tenor Up":
                "IgYAwgggzAAAgDGANhyAgaBAMCgAXAUwDsB7AJxgAoAERGAKlsQEomYBqNxu1uzugDRt-ibizY1ECNACMAhgGcFiNjFXq6azRro6V2g.DQBlEgAcAdGgBCiiwAIwBADYEZZOYQAm9hXjIArgDmQa6-eHJkeACWREEAtAAsAOwArI4ubh7e8X6BIa65EVGxCSmpADGaMAD.iAQATAArAAZAA_",
            bass: "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyJgAoAERGAKjsQEpmYBqdp-t-r-gBp2AxD1btaiBGhIBDAM4LE7GKvX01mjfR0rtB-GgDKAewAOAOjQAhRZYAEYIhRIE5eIgBMHCwgFcAc0CKXzw5AjwASwA7QIBaABYAdgBWJxdSd08veL8CIJCiPPDI2ISU1IAYzXoACCIAJgAVjiA__",
            "Do Alto Down":
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PXuE0BDMngD2MAFjMAOMwDYzALiSZ85gDxltKbVm1xiOGgDKQgA4A6NACE-AZ1MACMEQokCfPEQAmd64QCuAc38Kbzw-AjwASwA7fwBaABYAdgBWBydSV3cPWJ8CAKCiHNDw6Lik5IAY-hgAf8QiACYAZYBKoA__",
            "Tenor Down":
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PXuEBQPIgDsA9gRgAsZgBxmAbGYBcaXMXMAeKtoza82pMRw0AZWEAHAHRoAQgEMAzuYAEYIhRIEbAgCaO7hAK4A5oEUvng2BHgAloKBALQALADsAKzOrqQe3nF-BEEhRDnhkTHxySkAMfQwAP-IRABMAMsAyUA__",
            "Do Alto Up":
                "IgYAwgggzAAAgDGANhyAgaBAM0EMA2ALgPYwAUACIjAFRWICU9MA1M3dU9W9QDTM9EHRs0qIEaAEa4AzjMTMYi5dSWqV1DQvU74aAMrEADgDo0AIVkmABGACm-O5IBOuQnYAm1mYWcBXAHMAx29CXGdCAEsAOwCAWgAWAHYAVlsHJ1d3DziffyDHXLCImPjklIAY1RgAf8Q7ACYAFbAgA___",
        },
        mixolydian: {
            "Do Alto Down":
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PXuWWE0AhmTwB7GAExmAHGYBsZpNozaAPGYB8ZgAJma2jtoBcOcwBYCxnDQBlEQAcAdGgBCAgM4OtYIhRIEBeEQAJlpuhACuAOaRFKF4AgR4AJYAdpEAtAAsAOwArF4-pP6BQelhBFExRGXxiakZObkAMfQwAP-IRABMAJEAvEA_",
            "Tenor Up":
                "IgYAwgggzAAAgDGANhyAgaBAMCgAXAUwDsB7AJxgAIAERGAYlsQCImq3G6BSNgMjYDkbHnSF0AJG1Z0AhGxqIEaAEYBDAM7rEbGDr11dB.XWPaj5kxbhoAyiQAOAOjQAhDY8pgCAGwLKyqoQAJpTqeGQArgDmUb6heKpkeACWRFEAtAAsAOwArJ4-fgHB6WGRMb6lCUmpGTm5ADEGdACwBABMAFEAnkA",
            "Tenor Down":
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PXuWWEBQPEQB2AewIwAmMwA4zANjNptObQB4zAPjMABMw209tALgLmALCWM4aAMqiADgDo0AIQCGAZyc6wRCiQE7kIAJjqehACuAObRFOF47gR4AJbC0QC0ACwA7ACsvv6kQaEZEQQxcURliclpmbl5ADH0MAD.iEQATACRAGZAA",
            bass: "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyJgHIAERGAKjsQEpnr2n6AadgWnYA6dr3rD6AanZt6ACna1ECNCQCGAZ3WJ2MHXvq6D--se1HzJi3DQBlAPYAHQWgBCGwQAIwRCiQKq8IgATD3VCAFcAc0iKULxVAjwASwA7SL4AFgB2AFYvH1J.QKC-MIIomKJS-MTU9OycgBiDGAB.xCIAJgAogFwgA_",
            soprano:
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PXuWWE0SAQwDOwmAExmAHGYBsZpNozaAPGYB8ZgAJma2jtoBcOcwBYCxnDQBlAPYAHAHRoAQiMdawRCiQKC8RAAmWsKEAK4A5hEUIXiCBHgAlgB2EQC0ACwA7ACsnt6kfgGBaaEEkdFEpXEJKenZOQAx9LQAsEQATACRUkA_",
            "Do Alto Up":
                "IgYAwgggzAAAgDGANhyAgaBAM0EMA2ALgPYwDkACIjAFRWICU95zd1ANMwLTMB0znav2oBqZk2oAKZpUQI0AI1wBnZYmYwNW6pp3bq-9XuMGTcNAGViAB15oAQit4ACMAFN8bhQCdchNwAmzsqE3gCuAOYRnsGEuN6EAJYAdhFcACwA7ACsrh5evv4BXCHhUZ4lcQkpaVnZADE6MAD.iG4ATABRAPxAA",
        },
    },
    "Type 5": {
        aionian: {
            "Do Alto Up":
                "IgYAwgggzAAAgDGANhyAgaBAM0EMA2ALgPYwDEACIjAKRWIBk9MA5M3dQBTNvUePtmAEmaVECNACNcAZxmJmMRcupLVK6hoXqd8NAGViABwB0aAEKyTAAjABTfHckAnXITsATazMLOArgDmAY7ehLjOhACWAHYBALQALADsAKy2Dk6u7h5xPv5BjrlhETHxySkAMaowAP-IdgBMAEsAQ0A__",
            "Do Alto Down":
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PXuE0BDMngD2MADjMAeMwD4zAASTmAQnmLas2lNoBcZuMRw0AZSEAHAHRoAQnwDO5uWCIUSBPniIATObcIBXAHMAih88PgI8AEsAOwCAWgAWAHYAVkdnUjcPTzjfAkDgolywiJj45JSAGPoYAH.EIgAmACWEoA__",
            soprano:
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PXuE0SBDAM6CYAHGYA8ZgHxmAAknMAhPMW1ZtKbQC4zcYjhoAygHsADgDo0AISEW5YIhRIF-eIgBM5gwgFcA5v4U3nj8BHgAlgB2.gC0ACwA7ACsDk6kru4esT4EAUFEOaHh0XFJyQAx9DAAoFE1RABMAIsA90A_",
            "Tenor Up":
                "IgYAwgggzAAAgDGANhyAgaBAMCgAXAUwDsB7AJxgGIAERGAUlsQDImYByNxugCjc7rcWXNgBI2NRAjQAjAIYBnBYjYxV6ums0a6OldoPw0AZRIAHAHRoAQoosACMAQA2BGWTmEAJvYV4yAK4A5kGuvnhyZHgAlkRBALQALADsAKyOLm4e3vF-gSGuuRFRsQkpqQAxmjAA.4gEAEwASwArQA_",
            "Tenor Down":
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PXuEBQPIgDsA9gRgAcZgDxmAfGYACacwCEi5bXm0ZtALjNJiOGgDKwgA4A6NACEAhgGdLCsEQokCdgQBMFDwgCuAOZBFH54dgR4AJaCQQC0ACwA7ACsLm6knj7x.gTBoUS5EVGxCSmpADH0MAD.iEQATABLACRAA",
            bass: "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyJgCoAERGAGjsQFpmYA6dp-gena70erbuwDU7WogRoSAQwDOCxOxir19NZo30dK7QfhoAygHsADhzQAhRRwAEYIhRIE5eIgBN7CwgFcAcwCKHzw5AjwASwA7AJYAFgB2AFZHZ1I3D08WXwJA4KIcsIiYuKTkgBjNGAB.xCIAJgAlgAygA_",
        },
        lydian: {
            "Do Alto Down":
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PX440BDMngD2MAPjMABMwCEzcbQB4c5gGJmAImW0ptefDQBlIQAcAdGgBCfAM6mJYIhRIE-eIgBMJ1wgFcA5n4UXnh8BHgAlgB2fgC0ACwA7ACs9o6kLm7uMd4E.oFE2SFhUbGJSQAx9DAA.4hEAEwAPgA8QA___",
            "Do Alto Up":
                "IgYAwgggzAAAgDGANhyAgaBAM0EMA2ALgPYwBkACIjAORWIAU95zApM5dQFTMCUHzOtU7w4aAEa4AzlMTMY8xdQXKl1NXNWIxAZWIAHAHRoAQtMMACMAFN818QCdchawBMLUwg4CuAc192HoS4DoQAlgB2vgC0ACwA7ACsVrb2Ti6u0Z4-.nZZwaGRMQmJADHKMAD.iNYATAB-AOdAA_",
            soprano:
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PX440SBDAM6CYAfGYACZgEJm42gDw5zAMTMARMtpTa8-GgDKAewAOAOjQAhIWYlgiFEgX54iAEwmDCAVwDmvik88fgI8AEsAO18AWgAWAHYAVjsHUmdXN2ivAj8Aoizg0MiYhMSAGPoYAH.EIgAmAG8Ad6A_",
            "Tenor Down":
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PX44BQPIgDsA9gRgB8ZgAJmAQmaTaAPAXMAxMwBEq2jNqL4aAMrCADgDo0AIQCGAZ3NSwRCiQI2BAEyl3CAVwBzAIofPBsCPABLQQCAWgAWAHYAVicXUncvWN8CQOCibLCI6Lik5IAY-hgAf8QiACYAHwBYIA___",
            "Tenor Up":
                "IgYAwgggzAAAgDGANhyAgaBAMCgAXAUwDsB7AJxgDIAERGAclsQAomq2BSNmugKjYCU3Nozo94cNACMAhgGc5iNjGWq6K9WrpalmxJIDKJAA4A6NACF5pgARgCAGwJSyMwgBMbcvGQCuAc38nLzwZMjwASyJ.AFoAFgB2AFY7R2dXDxjvP0CnLNDwqNjEpIAY9RgAf8QCACYAPwBfoA_",
            bass: "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyJgDIAERGAcjsQApnr2BSd2-gKnYBKHuyb1e8OGhIBDAM5zE7GMtX0V6tfS1LNiKQGUA9gAcAdGgBC8swAIwRCiQIy8RACa25hAK4BzPwovPBkCPABLADs.AFoAFgB2AFZ7R1IXN3cY7wJ.QKJskLCo2MSkgBj1GAB.xCIAJgA.AAWgA__",
        },
        phrygian: {
            "Tenor Up":
                "IgYAwgggzAAAgDGANhyAgaBAMCgAXAUwDsB7AJxgFIAERGAYlsQBImG2BCNgCjYHI2NOgDJBTOHDQAjAIYBnOYjYxlquivVq6WpYkkBlEgAcAdGgBC8kwAIwBADYEpZGYQAm1uXjIBXAOZ-jp54MmR4AJZEfgC0ACwA7ACstg5OLu7RXr4BjpkhYZExCYkAMeowAP-IBABMAN70QA___",
            "Do Alto Up":
                "IgYAwgggzAAAgDGANhyAgaBAM0EMA2ALgPYwCkACIjAMRWIAk9tzAhMwBTMDkzl1AMj704cNACNcAZymJmMeYuoLlS6mrmIxAZWIAHAHRoAQtIMACMAFN8V8QCdchKwBNzUwvYCuAcx-33Qlx7QgBLADsfAFoAFgB2AFZLGztHZxcoj28.W0ygkIjo-ISAGOUYAH.EKwAmAG8AaCA___",
            "Tenor Down":
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3P4YBQPIgHYB7AjAB4zADjMAuFOYAsZgEJmAAmYTaAfE2M4aAMpCADgDo0AIQCGAZzNqwRCiQLX-AEzW3CAVwDm.hTeeNYEeACWAv4AtAAsAOwArI7OpG6eMT4EAUFEWaHhUbGJSQAx9DAA.4hEAEwAXgDwQA",
            soprano:
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3P4Y0SBDAM4CYAPGYAcZgFwJzAFjMAhMwAEzMbQD46xnDQBlAPYAHAHRoAQoNMqwRCiQJ88RACYqBhAK4BzHxQ88PgI8AEsAOx8AWgAWAHYAVlt7UicXVyjPAl9.IkygkIjo-ISAGPoYAH.EIgAmAE8AY6A__",
            "Do Alto Down":
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3P4Y0BDMvAHsYAPGYAcZgFwJzAFjMAhMwAEzMbQD46xnDQBlQQAcAdGgBCvAM4mVYIhRIFeeIgBMVVwgFcA5r4pPPF4CPABLADtfAFoAFgB2AFY7B1JnVzdorwI.AKIs4NDImITEgBj6GAB.xCIAJgAvTSA__",
            bass: "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyJgBoAERGAKjsQGpnH2AKdgenYDp2tegFohzOHDQkAhgGc5idjGWr6K9WvpaliKQGUA9gAd-aAELz-AAjBEKJAjLxEAJtbmEArgHMfFDzwZAjwASwA7HxEAFgB2AFZbe1InF1cRTwJffyIMoJCIqLj4gBj1GAB.xCIAJgAvAEmgA__",
        },
        dorian: {
            "Tenor Down":
                "IgYAwgggzAAAgDGANhyAgaBAAoAYAFwCcBTAIwBtjEAERGumWup-5hlx9rt-GAUHzEAdgHtCMALgsA-CwB4LKXQAEMlgEIWqurLoK6S-GgDKIgA4A6NACEAhgGcLysMUqlCtwQBNl9ogFcAc0DKX3xbQnwASyFAgFoAFgB2AFZnVzIPbzi.QiCQ4hzwyJj45JSAGIYYAH.EYgAmfABnoA___",
            bass: "IgYAwgggzAAAgDGANhyAgaBAAoAYAFwCcBTAIwBtiYBqABERgFp7EAaFmjgOg-YYHpuvDuwZ1ECNKQCGAZ1mIOMJSobK1qhpsUaJaAMoB7AA5c0AITlcABGGKVShafmIATa7KIBXAOY.KHvjShPgAlgB2PowALADsAKy29mROLq6MnoS-.sQZQSERUXHxADFqMAD.iMQATABuAHxAA__",
            "Tenor Up":
                "IgYAwgggzAAAgDGANhyAgaBAAoAoAFwFMA7AewCcYASABERgDI7EBSZ69gcnafoAouPdm3q1ECNACMAhgGdZidjCUr6ytavqbFG8WgDKpAA4A6NACE5JgARhCAG0KTy0ogBNrs.OQCuAcz9HT3xpcnwAS2I.AFoAFgB2AFZbBycXd2ivXwDHTJCwyJiExIAYtRgAf8RCACYANwBVoA__",
            soprano:
                "IgYAwgggzAAAgDGANhyAgaBAAoAYAFwCcBTAIwBtjEAERGumWup-5hlx9rt-GNUgIYBnITAC4LAPgsAeCwl0ABFJYBCFsrrS6cugvhoAygHsADgDo0AIWHnFYYpVKEB-YgBNFQogFcA5n6UXvgChPgAlgB2fgC0ACwA7ACs9o5kLm7uMd6E.oHE2SFhUbGJSQAxDDAAoJHVAI4I2O4AywDnbUA__",
            "Do Alto Down":
                "IgYAwgggzAAAgDGANhyAgaBAAoAYAFwCcBTAIwBtjEAERGumWup-5hlx9rt-GNAQ3L4A9jAC4LAPgsAeCwl0ABFJYBCFsrrS6cugvhoAysIAOAOjQAhfgGczisMUqlC.fMQAmim0QCuAc39Kb3x-QnwASwA7fwBaABYAdgBWBycyV3cPWJ9CAKDiHNDw6Lik5IAYhhgAf8RiACZfADCgA___",
            "Do Alto Up":
                "IgYAwgggzAAAgDGANhyAgaBAAoNBDAGwBcB7GAEgAREYAyaxAUgYpYHIX6aAKdzl5jSqIEaAEZ4AzpMQsYchTXlLFNVbJUi0AZRIAHAHRoAQlIMACMAFMCVsQCc8RKwBNzkovYCuAcx-33Ijx7IgBLADsfAFoAFgB2AFZLGztHZxcoj28.W0ygkIjo-ISAGKUabCsAJgA3AEKgA_",
        },
        locrian: {
            "Do Alto Up":
                "IgYAwgggzAAAgDGANhyAgaBAM0EMA2ALgPYwCUACIjANRWIBU95zAFM09ZdZ4nT827wcAI1wBncYmYwZc6rIXzqy6UsRw0AZWIAHAHRoAQhP0ACMAFN8lkQCdchSwBMz4wnYCuAc2823hLh2hACWAHbeALQALADsAKwW1rYOTs6R7l6-NhmBweFRcfEAMQowAP-IlgBMAGMA50A_",
            bass: "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyJgEoAERGAajsQCpnr2AKdt-2-3oiYD2.eDDQkAhgGcZidjEXL6S1SvoaF6xHDQBlAPYAHAHRoAQrNMACMEQokCUvEQAmNmYQCuAc18UnnhSBHgAlgB2vgC0ACwA7ACsdg6kzq5u0V4EfgFEWcGhkTEJiQAxquIwRABMAGMAk0A___",
            "Tenor Down":
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PX4YBQPIgDsA9gRgBsZgFxmAHGaTaALDkLVtGbXm1F8NAGVhABwB0aAEIBDAM4mABGCIUSBSwIAmd64QCuAcz8KLzxLAjwAS0E.AFoAFgB2AFYHJ1JXD2jvAn9AokyQsMiYhMSAGPoYAH.EIgAmADGAcSA__",
            "Tenor Up":
                "IgYAwgggzAAAgDGANhyAgaBAMCgAXAUwDsB7AJxgEoAERGAalsQComq2AKN1umunxI35s-8GGgBGAQwDOMxGxiLldJapV0NC9YjhoAyiQAOAOjQAhWSYAEYAgBsCEslMIATazLxkArgHM.R088KTI8AEsiPwBaABYAdgBWWwcnF3dor18Ax0yQsMiYhMSAGNUYAH.EAgAmAHHMIA",
            "Do Alto Down":
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PX4Y0BDMngD2MANjMAuMwA4zcbQBYMuctpTas2vPhoAykIAOAOjQAhPgGcjAAjBEKJAnzxEAJtYuEArgHMfFDzw-AjwASwA7HwBaABYAdgBWW3tSJxdXKM8CX38iTKCQiOj4hIAY-hgAf8QiACYAMYBtIA__",
            soprano:
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PX4Y0SBDAM6CYAbGYBcZgBxm42gCwZc5bSm1ZtefDQBlAPYAHAHRoAQkOMACMEQokC.PEQAmVwYQCuAc28V3ePwEeACWAHbeALQALADsAKw2dqSOzi6RHgQ-fkQZgcHhUXHxADH0MAD.iEQATABjAP5AA___",
        },
        aeolian: {
            soprano:
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PXuE0SBDAM6CYALGYAcZgGxmAXEkz5zAHjLaU2rNrjEcNAGUA9gAcAdGgBCQswAIwRCiQL88RACa3BhAK4BzPwovPH4CPABLADs.AFoAFgB2AFZ7R1IXN3cY7wJ.QKJskLCo2MSkgBj6GAB.xCIAJgBlnyA_",
            "Tenor Up":
                "IgYAwgggzAAAgDGANhyAgaBAMCgAXAUwDsB7AJxgAoAERGAKlsQEomYBqNxu1uzugDRt-ibizY1ECNACMAhgGcFiNjFXq6azRro6V2g.DQBlEgAcAdGgBCiiwAIwBADYEZZOYQAm9hXjIArgDmQa6-eHJkeACWREEAtAAsAOwArI4ubh7e8X6BIa65EVGxCSmpADGaMAD.iAQATAArAAZAA_",
            bass: "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyJgAoAERGAKjsQEpmYBqdp-t-r-gBp2AxD1btaiBGhIBDAM4LE7GKvX01mjfR0rtB-GgDKAewAOAOjQAhRZYAEYIhRIE5eIgBMHCwgFcAc0CKXzw5AjwASwA7QIBaABYAdgBWJxdSd08veL8CIJCiPPDI2ISU1IAYzXoACCIAJgAVjiA__",
            "Do Alto Down":
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PXuE0BDMngD2MAFjMAOMwDYzALiSZ85gDxltKbVm1xiOGgDKQgA4A6NACE-AZ1MACMEQokCfPEQAmd64QCuAc38Kbzw-AjwASwA7fwBaABYAdgBWBydSV3cPWJ8CAKCiHNDw6Lik5IAY-hgAf8QiACYAZYBKoA__",
            "Tenor Down":
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PXuEBQPIgDsA9gRgAsZgBxmAbGYBcaXMXMAeKtoza82pMRw0AZWEAHAHRoAQgEMAzuYAEYIhRIEbAgCaO7hAK4A5oEUvng2BHgAloKBALQALADsAKzOrqQe3nF-BEEhRDnhkTHxySkAMfQwAP-IRABMAMsAyUA__",
            "Do Alto Up":
                "IgYAwgggzAAAgDGANhyAgaBAM0EMA2ALgPYwAUACIjAFRWICU9MA1M3dU9W9QDTM9EHRs0qIEaAEa4AzjMTMYi5dSWqV1DQvU74aAMrEADgDo0AIVkmABGACm-O5IBOuQnYAm1mYWcBXAHMAx29CXGdCAEsAOwCAWgAWAHYAVlsHJ1d3DziffyDHXLCImPjklIAY1RgAf8Q7ACYAFbAgA___",
        },
        mixolydian: {
            "Do Alto Down":
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PXuWWE0AhmTwB7GAExmAHGYBsZpNozaAPGYB8ZgAJma2jtoBcOcwBYCxnDQBlEQAcAdGgBCAgM4OtYIhRIEBeEQAJlpuhACuAOaRFKF4AgR4AJYAdpEAtAAsAOwArF4-pP6BQelhBFExRGXxiakZObkAMfQwAP-IRABMAJEAvEA_",
            "Tenor Up":
                "IgYAwgggzAAAgDGANhyAgaBAMCgAXAUwDsB7AJxgAIAERGAYlsQCImq3G6BSNgMjYDkbHnSF0AJG1Z0AhGxqIEaAEYBDAM7rEbGDr11dB.XWPaj5kxbhoAyiQAOAOjQAhDY8pgCAGwLKyqoQAJpTqeGQArgDmUb6heKpkeACWRFEAtAAsAOwArJ4-fgHB6WGRMb6lCUmpGTm5ADEGdACwBABMAFEAnkA",
            "Tenor Down":
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PXuWWEBQPEQB2AewIwAmMwA4zANjNptObQB4zAPjMABMw209tALgLmALCWM4aAMqiADgDo0AIQCGAZyc6wRCiQE7kIAJjqehACuAObRFOF47gR4AJbC0QC0ACwA7ACsvv6kQaEZEQQxcURliclpmbl5ADH0MAD.iEQATACRAGZAA",
            bass: "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyJgHIAERGAKjsQEpnr2n6AadgWnYA6dr3rD6AanZt6ACna1ECNCQCGAZ3WJ2MHXvq6D--se1HzJi3DQBlAPYAHQWgBCGwQAIwRCiQKq8IgATD3VCAFcAc0iKULxVAjwASwA7SL4AFgB2AFYvH1J.QKC-MIIomKJS-MTU9OycgBiDGAB.xCIAJgAogFwgA_",
            soprano:
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PXuWWE0SAQwDOwmAExmAHGYBsZpNozaAPGYB8ZgAJma2jtoBcOcwBYCxnDQBlAPYAHAHRoAQiMdawRCiQKC8RAAmWsKEAK4A5hEUIXiCBHgAlgB2EQC0ACwA7ACsnt6kfgGBaaEEkdFEpXEJKenZOQAx9LQAsEQATACRUkA_",
            "Do Alto Up":
                "IgYAwgggzAAAgDGANhyAgaBAM0EMA2ALgPYwDkACIjAFRWICU95zd1ANMwLTMB0znav2oBqZk2oAKZpUQI0AI1wBnZYmYwNW6pp3bq-9XuMGTcNAGViAB15oAQit4ACMAFN8bhQCdchNwAmzsqE3gCuAOYRnsGEuN6EAJYAdhFcACwA7ACsrh5evv4BXCHhUZ4lcQkpaVnZADE6MAD.iG4ATABRAPxAA",
        },
    },
};
