export const offlineExersizesData = {
    "Type 1": {
        dorian: {
            soprano:
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyJgGoAERGAOjsQBpmYBadgenafrb1-iWgPZcx9UfDhoSAQwDOimAFwacAByIAeBtgwAOPsTq4B43ABsMABABsDTaMmYe84gD4TxJYNnYGj9TDW1ZAGUAewAHBjQAISUGAAIwIgoSAnk8IgATZMVCAFcAcxKKArx5AjwASwA7Eo4AFgB2AFZU9NIsnNyOQoJS8qIBqpqGprb2gBj6RAB.xCIABlUAESA___",
            "Do Alto":
                "  IgYAwgggzAAAgDGANhyAgaBAcBgAXAJwFMAjAGyJgGoAEOADkQCo6A2RACjthgBo3EtOOxgs4PIewAQASm6d5NMSKGMEaAIZk8AexgBcGohgA8I4gD45mAAJrV4wEJ71u8YeIzxw4jhoAyjoADgB0aABCGgDOITZgRBQkBBp4RAAmNlGEAK4A5rkUmXgaBHgAlgB2uQC0ACwA7ACscQmkyalp1VkEeQVEXcWllTUNjQAxxpNoRGgAiwB-QA_",
            tenor: "IgYAwgggzAAAgDGAKByAgaBAMCgAXAUwDsB7AJxgBIAERGAYlsQDImG2BSNmugck7ZI2.Oqzpc6PeACg0AIwCGAZyUwAuNTgAORADxNANkQa4sGAHxNAVkQACQ4ktwjMfabuazAHAevPx.2ofd3VNHTg0ABViADo0ACFlGNswAgAbAjkyBUIAE1slPDIAVwBzUoyCvAUyPABLIlKAWgAWAHYrFPTM7LymwpLyjP7q2obm9qsAGLpENABwnCIcAEccADyAf8RcgFeAfMogA__",
            fa: "IgYAwgggzAAAgDGANhyAgaBAcBgAXAJwFMAjAGyJgBIAEOADkQGI6A2RWudmAMjthgByfhzaJhcAQAoxNAFRiYAajqM4AKDQkAhgGddMALg1EMAHgnEAfEtHbF0zdMPEAHHu3jiOGgDKAewAHADo0ACE9YIACMCIKEgJtPCIAEyjdQgBXAHNsinS8bQI8AEsAO2yAWgAWAHYAVhi40kTklMqMghy8og7C4vKquvqAGNNEAH.EIgAGAGwYIA_",
        },
        phrygian: {
            soprano:
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyJgFIAERGAMjsQApmYBydt-p-gKnYBKdl3oj6PRH0S1EcOGhIBDAM6qYAPBpwAHIgC4O2DAA4OgGyIA2JcTm4VmEbgmAWMcN2tn594dOLibaevBoAMoA9gAOAHRoAEJqsQAEYEQUJATKeEQAJimqhACuAOalFIV4ygR4AJYAdqUAtAAsAOwArGkZpNm5ec1FBGUVREPVtY0tHZ0AMfSIaADhAKANqwCOqwB5CAAweQCHANAADEA___",
            "Do Alto":
                "IgYAwgggzAAAgDGANhyAgaBAcBgAXAJwFMAjAGyJgBoAEOADkQGo6A2RASjthhbh9px2MAFTdEg4WKHM2EuowRoAhmTwB7GAFIaiGADJdiAORGYXPab0AKM1cQ69hvY.hoAyuoAOAOjQAhZQBnHwACMCIKEgJlPCIAE1CgwgBXAHM0iiS8ZQI8AEsAOzSAWgAWAHYAVnDI0hi4-JLkgnTMomacvKLSyqqAGL1EAH.EIlCACoBbIA",
            tenor: "IgYAwgggzAAAgDGANhyAgaBAAoAoAFwFMA7AewCcYBSABERgHI7EAKZmAMndvqfoBJ2AYm7su9HvGxoARgEMAzgpgA8GnAAciANjqAbIgA4-xAFx1sGMbiW1Ns-q2qTViw.vPN8NAGVSABwA6NAAhRUCAAjBCABtCGXI5IgATCIV8cgBXAHNsuLT8OXJ8AEtibIBaABYAdgBWKNj4xJSK9KzcuLbC4rLK2rqAGPpEAH.EQiohbSA",
            fa: "IgYAwgggzAAAgDGANhyAgaBAAoAYAFwCcBTAIwBtiYAaABDgA5EB6egNkQFp7YafEA1O0QAqYTAAU.GGLi8AlNKFwOfRvBhpSAQwDOumADxaiGABwTiALiXztgPi3jpx6YCEtgAQOnluGgBlAHsABwA6NAAhPTDPMGJKUkJtfGIAE09dIgBXAHNcykz8bUJ8AEsAO1zOABYAdgBWOISyZNS0zizCPILiTuLSyur6hoAY00QAf8RiABIAXfsgA___",
        },
        lydian: {
            soprano:
                "IgYAwgggzAAAgDGANByAgaBAMBgAXAJwFMAjAGyJgDIAERGAUjsQGJmYASd2-gcna7029QYn70e8OGhIBDAM7yYAfBpwAHIgAEagGyIAhGtgwdcAKyIAuMcQA8Wyr33nTuPpgO4J1RfhoAZQB7AAcAOjQAIQUwrTAiChICWTwiABMteUIAVwBzXIpMvFkCPABLADtcgFoAFgB2cziE0mTUtOqsgjyCok7i0sqahvMAGPpEBAAIIioSAHEgA_",
            "Do Alto":
                "IgYAwgggzAAAgDGANhyAgaBAM0EMA2ALgPYwD4ACIjAARWICE9tzl1AeM3dU9d4m3hw0AI1wBnceQpwAHIk5xYMADgyAbDAAQAbA2IAuDOVql2vXE3SzMRcspz4aAMrEADgDo0AIQkeaYACm-IEiAE64hIEAJjTihGEArgDmySFxhLhhhACWAHbJALQALADsAKwBwaERUdGF8UmpIQ2Z2flFZeUAMdSIAP-IgQwAiQC.QA__",
            tenor: "IgYAwgggzAAAgDGANhyAgaBAAoAYAFwCcBTAIwBtiYAyABDgA4YAIASnoDZEAKTxAcnqwa9JjABUfGAFohiADRSA1FMVwuM0fBgBQfMQB2Ae0IwA-LUQwAuJcQAcOzAB4Ti1ddXbVgARunflbu8GgAykYADgB0aABCAIYAzlE-YMSUpITx-gAmPolEAK4A5sWU-fjxhPgAlgbF0gAsAOwArKnpZFm50gWEJWXEvZXVdQ0trQAxVjPMxACkAP4A7UA___",
            fa: "IgYAwgggzAAAgDGANhyAgaBAAoAYAFwCcBTAIwBtiYBaABDgA5EAaegNkQCp7Yaev2iANT8AEAEpaiGNzi9WcxHTgcEaUgEMAzlpgB8KYgAEhmAEJTB6QDxLpgLimL0k9Kvw0AZQD2ABwB0aABC2v5GYMSUpIQa-MQAJkZaRACuAOZplEn4GoT4AJYAdmnUACwA7ACs4ZFkMXHx1MmE6ZnETTl5RSUVlQAx0oO4xABkGgDBQA___",
        },
        mixolydian: {
            soprano:
                "IgYAwgggzAAAgDGAPByAgaBAMBgAXAJwFMAjAGyJgHIAERGAKjsQEpmYAKdp-ganYC07ADTsAdO37029LvVqI4cNCQCGAZ3UwABDTgAORADw9ANkQBcPbBgB8a8bOJ7cczCtwbJg4gDYTuwDdTxgaFxtgw2UAZQB7AAcxNAAhDTFtMCIKEgJVPCIAE211QgBXAHNyimK8VQI8AEsAO3KBABYAdgBWDKzSXPyCgRKCCqqiYdr65tbOroAY-kQAf8QiADIGjqA",
            "Do Alto":
                "IgYAwgggzAAAgDGANhyAgaBAAoAYAFwCcBTAIwBtiYByABDgA5EAKe2Gtl-gNkQDJOHOOwBU9AKyI6wrjNoC4vIUwRoAhuXwB7GAAJaiGAHwDiAHimYAHEsBcSxcMnDjxM8QBCS.sRw0AZS0ABwA6NAAhNQBnEN0wYkpSQjV8YgATXSiiAFcAc1zKTPw1QnwASwA7XIBaABYAdnE4hLJk1LTqrMI8guJO4tLKmobxABjDRAB.xGIAYjQAOCA",
            tenor: "IgYAwgggzAAAgDGANhyAgaBAAoAoAFwFMA7AewCcYByABERgCo7EBqZ69gCnYEp236Tet3q1EcOGgBGAQwDOcmAAIacAByIAeKoBsiAPi6tq2DENxTAXCNmb2uHprnTK9fDQBlUgAcAdGgAheV8lMEIAG0IpchkiABMlOXxyAFcAczTIxPwZcnwAS2I0gFoAFgB2AFZQiKiY-OKk1IzIxpy8wpKKyoAY-kQAf8RCAFIAegBsoA__",
            fa: "IgYAwgggzAAAgDGANhyAgaBAAoAYAFwCcBTAIwBtiYByABDgA5EAyegNkQFJ7Yb2WeiOnACsiACSDarOBz6N4MNKQCGAZzUwAmLUQwAWLsQAcIzADYZgLhnTey3sN6diOGgDKAewAOAOjQAQuq-AARgxJSkhCr4xAAmIWpEAK4A5qmUifgqhPgAlgB2qQC0ACwA7CJhEWTRsXHFSYRpGcSN2bmFJRUiADF6iAD.iMTMxADWQA___",
        },
        aeolian: {
            soprano:
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyJgAoAERGAKjsQEpmYBqdp-gGm.Zd6berURw4aEgEMAzrJgBCGnAAciAHgqAbIgAEK2DAD4OxMrhGDcXTC03EAIkMwa1oxfWSAygHsADgB0aABCcoF6YEQUJATSeEQAJnqyhACuAOYZFCl40gR4AJYAdhkAtAAsAOwArJHRpHEJiWWpBJnZRK15BSXl1TUAMfSIAP-IRABkAFYA00A",
            "Do Alto":
                "IgYAwgggzAAAgDGANhyAgaBAAoNBDAGwBcB7GAQgAREYACaxAfAbpapoFwWA8F5m9ono0ARGwZxcAIzwBnWTABYlOAA5EvOLBhctiANgqAbIgA4xgyu3m9Oq4mVrLcE5QCY9pSvVw0AZRIABwA6NAAhOWDaMABTAhipACc8IhiAE1pZIkSAVwBzPPjMojxEogBLADs8gFoAFgB2AFZouITk1LSarNyC-O6SsqraxqaAGJpEAH.EGIASADOAXSA__",
            tenor: "IgYAwgggzAAAgDGANhyAgaBAcBgAXAJwFMAjAGyJgHoAEOADkQGo7YYAaVxAOi-roCsPPgFo-nOG15wAbIlqyYNaXP4N4MAKB4iAOwD2BGAEIaiGACIziAMTWYAUnsASe0.Ovzd81a.3fiKaIcGgAyvoADtxoAEIAhgDO3AAEYEQUJARxOgAmyQmEAK4A5sUU-XhxBHgAlrrFIgAsAOwCqemkWbkiBQQlZUQ9ldV1DS0CADHmiAD.iEQOAHUAwUA",
            fa: "IgYAwgggzAAAgDGANhyAgaBAAoAYAFwCcBTAIwBtiYAKABDgA5EAaegNkTrg5gEp3EAanqwYAchGcBtCdymN4MNKQCGAZzUwAWLUQwAmLsQAcIzAC4ZgNhmAeGdN6benYjhoAygHsADgDo0ACF1PwACMGJKUkIVfGIAE1C1IgBXAHM0yiT8FUJ8AEsAOzSAWgAWAHYAVnDIshi4-JLkwnTM4macvKLSyqqAGL1EAH.EYgAyACsAWSA__",
        },
        locrian: {
            soprano:
                "IgYAwgggzAAAgDGANhyAgaBAAoAYAFwCcBTAIwBtiYBKABERgCp7EBqFmACg-YfYYA0PDnURxsaUgEMAzjJgBsWnAAciAFjLYMAJjKArIgA4ygGwatiJXG1645mJptXlauGgDKAewAOAOjQAIVk.AAIwYkpSQil8YgATUJkiAFcAczTKJPwpQnwASwA7NIBaABYAdn1wyLIYuPiS5MJ0zOImnLyi0sr9ABiGRAB.xGIAMnIBIA__",
            "Do Alto":
                "IgYAwgggzAAAgDGANhyAgaBAAoAYAFwCcBTAIwBtiYBKABDgA5EAKegNkQHJ7YYAyHogCkgmACp6AVkR04HGNzi9WcmfSYI0AQ3L4A9jABEtRDADEJ4ZZgASaxdMDTd0yNMPExxHDQBlPQAOAHRoAEJaAM5BAARgxJSkhFr4xAAm0RFEAK4A5jmUGfhahPgAlgB2OQC0ACwA7JKx8WRJKalVmYS5-cQdRSUV1fWSADGm4wCQxAAYAAYAnUA_",
            tenor: "IgYAwgggzAAAgDGANhyAgaBAMCgAXAUwDsB7AJxgCIAERGAAlsQHwmYA8N1ugXDcbrdEnOjToBiNmPhw0AIwCGAZyUwA2NTgAOYZtgwAWJoBsiADh7ERuKfWWYFuAFZEfOPsf63t6.o3b4NABlEgAHADo0ACFlcPowAgAbAjkyBUIAE3olPDIAVwBzAuTsvAUyPABLIgKAWgAWAHYneKSUtMzanPyi5K6yiuq6pqcAGLpEAH.EAjMAJQBdoA",
            fa: "IgYAwgggzAAAgDGANhyAgaBAAoAYAFwCcBTAIwBtiYBKABDgA5EAKegNkQDJ7YYBSekxgBydlx6IAVGJis4HGoPgw0pAIYBnDTADYtRDAA4-xAFwTMAHgW9B8wesHjB2.DQBlAPYAHAHRoAIU1fAAIwYkpSQjV8YgATEI0iAFcAc1TKRPw1QnwASwA7VIBaABYAdgBWMIiyaNi44qTCNIziJuzcwpKKyoAYg0QAf8RiTgA1ADCgA",
        },
        aionian: {
            soprano:
                "IgYAwgggzAAAgDGANhyAgaBAAoAYAFwCcBTAIwBtiYBKABERgCp7E6GAKFprgai4BouzBm3iY0pAIYBnaYgAQDAETy4ADkQBCVbBgA8VQDZEAAh2IAuEcQAca.vMwA-KoCsiA3GMwr6xC69bRytMHgAWD3sALEcAbFo.ODQAZQB7AAcAOjQAIRlMkzBiSlJCSXxiABMTaSIAVwBzBsoa.ElCfABLADsGgFowgHZXQuKyMorKvtrCRubiabaOnv6h1wAYhkQAf8RiADIACMMgA___",
            "Do Alto":
                "IgYAwgggzAAAgDGANhyAgaBAAoAYAFwCcBTAIwBtiYBKABDgA5EAKegNkQHJ7YYAyHogCkgmACp6AVkR04HGNzi9WcmfSYI0AQ3L4A9jABEtRDADEJ4ZZgASaxdMDTd0yNMPExxHDQBlPQAOAHRoAEJaAM5BAARgxJSkhFr4xAAm0RFEAK4A5jmUGfhahPgAlgB2OQC0ACwA7JKx8WRJKalVmYS5-cQdRSUV1fWSADGm4wCQxAAYAAYAnUA_",
            tenor: "IgYAwgggzAAAgDGANhyAgaBAMCgAXAUwDsB7AJxgCIAERGAAlsQHwmYA8N1ugXDcbrdEnOjToBiNmPhw0AIwCGAZyUwA2NTgAOYZtgwAWJoBsiADh7ERuKfWWYFuAFZEfOPsf63t6.o3b4NABlEgAHADo0ACFlcPowAgAbAjkyBUIAE3olPDIAVwBzAuTsvAUyPABLIgKAWgAWAHYneKSUtMzanPyi5K6yiuq6pqcAGLpEAH.EAjMAJQBdoA",
            fa: "IgYAwgggzAAAgDGANhyAgaBAAoAYAFwCcBTAIwBtiYAqABDgA5EBye2GAMjZfoFZEAFNxis47AJT0AbIgCk0wcNESFNekwRpSAQwDOumABxaiGADwTiALiWjtgPi2Lpm6YAEDp7deJjiOGgAygD2AA4AdGgAQnrhbmDElKSE2vjEACZuukQArgDmeZRZ-NqE-ACWAHZ5ALQALADsvPGJZClp6TXZhPmFxF0lZVW1jbwAMaaTABDpAD8AzwAiQA__",
        },
    },
    "Type 2": {
        dorian: {
            soprano:
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyJgGoAERGAOjsQBpmYBadgenafrb0AVO1oD2XcfTHxMaEgEMAzksQAIOAA5EAXA3aYAPA2wYezFQAsiADgmYagNhqL1mACwNANl32YduB8zDQBWB2dAxGM4UwDTcyoAJii.AAJQhwAiPwB8bxStWz89GMQAQnyYdMiaAGI.ABIaQrg0AGUAewAHBjQAIWUGVLAiChICBTwiABNUpUIAVwBzJYo5vAUCPABLADsljksAdhDh0dIJqemOeYJl1aIbja29g-OQgBj6RDQAcIBQXb.ACO.wAeX9.tMAPsAMoAiUA__",
            "Do Alto":
                "IgYAwgggzAAAgDGANhyAgaBAmBgAXAJwFMAjAGyMQAhEYBqKuADkQDpHYYAqRgNkQZx-3RgFYYVAJQdEPTHQAsAxixgAaKvIBMiALR9l8pSLjj6B9QakyYAChuDhAchkAEHkIGvm8GGgCGZHgA9jAAuK60AHiRiAD4sTAABIkRtACEiQm0KbTZiDG0afBoAMrBAA6saABC.gDOrElgRBQkBP54RAAmSfWEAK4A5kMUfXj-BHgAlgB2Q7oKAOyiza2kHV3duv0Ew6NEOxNTcwvLogAxtNcAUEQAJABtAD5AA_",
            tenor: "IgYAwgggzAAAgDGAKByAgaBAMCgAXAUwDsB7AJxgBIAERGAYlsQDImG2BSNmugck7ZI2.Oqzpc6PeACg0AIwCGAZyWIAEHQC4auAA5EAPB0A2RAHwdsGNrhWjmANQAmczoCsiADg79MAAQmXpaucKb-7obBMBaOLuGhiDYeMN4J0REwRnDJqWE2VgBYgTAAmIHUqVaa1HrwaAAqxAB0aABCyk1-YAQANgRyZAqEACZ-SnhkAK4A5tN9Y3gKZHgAlkTTALQALADsbl29.YMjG-NTs32ni8trm7tuADF0iAD.iAR-ACU7QA___",
            fa: "IgYAwgggzAAAgDGANhyAgaBAAoAYAFwCcBTAIwBtjEAIRGAEmrgA5EBiJgVkUbgDZ2TATADkTWDABk4nk1YwApEJjUAlDJgAKDWMwBqAEyJp.RLr0B2RNrgSAVFzMyACA9Mw9zlvGxpSAQwBnQJgAXGc6AHwIxAA8GLCEgAIE6LoAQlSE-LpwxDg0AGUAewAHADo0ACEg8qSwYkpSQn98YgATJMCiAFcAcz7KLvx.QnwASwA7PoBaABYLTnrGsha29pnuwn7B4k2RsanZhc4AGLpEAFBJy4BHRAAkdoBlgAGAY6A",
        },
        phrygian: {
            soprano:
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyJgFIAERGAMjsQApmYBydt-p-gKnYBKdl3oj6PRH0S1EcTGhIBDAM6rEACHoA8TXAAciALj7YMAFj6AbIgA4Nk.oCsiPXHOnMAagAs9xxgAbE0fAHZEKzhbGFMPAMNIsydogPDEENSYd09AzKMYByyQnwAmJKy48x0aRLg0AGUAewAHADo0ACE1NoACMCIKEgJlPCIAE17VQgBXAHM5iim8ZQI8AEsAOzmAWl8w537B0hGx8Z3pgnnFoguVta3d.ecAGPpEAH.EIgYARwB6oA_",
            "Do Alto":
                "IgYAwgggzAAAgDGANhyAgaBAmBgAXAJwFMAjAGyMQAhEYAaKuADkQGpGA2RACkdhgCUfRACoqmVgBY2wmAHJOiIXH4BSRTABkGsSqWyGcLjF3HlAVh4b2tOgARm8GGgCGZPAHsYqu7U2.EOQCYACJggAJggEJgoNofP2CE-DQAZQ8ABwA6NAAhFwBnLPCwIgoSAhc8IgATcILCAFcAc2aKerwXAjwASwA7ZoBaSQB2cxKy0krqmsGGgha2ojnO7v6h0fMAGNpEAH.EIk0ARwBwIA",
            tenor: "IgYAwgggzAAAgDGANhyAgaBAAoAoAFwFMA7AewCcYBSABERgHI7EAKZmAMndvqfoBJ2AYm7su9HvExoARgEMAzgsQAIegDwVcAByIA2FoBsiTXFgwAOEcQBcLQFZEALGsw7ZxFY9uVmANQATCZa5gZwxj46-iHB4ba-fgDsnjEwBv4ALM6u7ubqNFFwaADKpAAOAHRoAEKKFQAEYIQANoQy5HJEACb1CvjkAK4A5kOtvfhy5PgAlsRDALQZifaNLW0d3fN9gyOtWxNTswtL9gAx9IgA.4iEHGUAckA__",
            fa: "IgYAwgggzAAAgDGANhyAgaBAAoAYAFwCcBTAIwBtjEAIRGAGmrgA5EAKJgNkUblhgCUXRAGomrBk34c43GGNmIAVEwCs7NYiGKYM.kMwiALMuEwA5FI18tZvaLP0ACC3jY0pAIYBnbzAB4TnQAOEGIALhhMKF0APhRkXFRgXSJiPF0KfBoAMoA9gAOAHRoAEI-RQAEYMSUpISe-MQAJpXeRACuAOZdlG34noT4AJYAdl0AtEYA7KrVtWQNTc0T7YTdvcSrA0NjkzOqADF0iAD.iMQAZHkAS0A___",
        },
        lydian: {
            soprano:
                "IgYAwgggzAAAgDGANByAgaBAMBgAXAJwFMAjAGyJgDIAERGAcjsQGJmYASdgUndvqb1eAvsziY0JAIYBnGYgAQ9APgK4ADkQAcNQFYYCgNhqAbIgBYa2DACYCzAGoALIgAYpxHbj6YOuNa8zGABcKwsPGAA8MJD7Z20YyzgzIwjo.0RlGg14NABlAHsABwA6NAAhWRKAAjAiChICKTwiABNqmUIAVwBzHooOvCkCPABLADsegFonAHZdWvrSJpbWqc6CXv6idaGRiem53QAY-kQAf8QiKgAvJyA_",
            "Do Alto":
                "IgYAwgggzAAAgDGANhyAgaBAM0EMA2ALgPYwD4ACIjAARWICE9tzl1AeM3dU9d4m3iY0AI1wBncYgAQ1MtLgAOROwWwYAXGmYA1ABZEAHAUA2AWpjSA2KaMKArIi1x1ALFsxjLp9p0AmFQtNXwNPD3lvaw9Vb3IKJXg0AGViAAcAOjQAIQl0mjAAU3wCkQAnXEICgBMacUJSgFcAcybi2sJcUsIASwA7JoBaPQB2e3yikvLKqoG6xpbi2Y6uvsGR-wAY6kQAf8QCgDIANwAGoA__",
            tenor: "IgYAwgggzAAAgDGANhyAgaBAAoAYAFwCcBTAIwBtjEAIRGAMmrgA4ZqBKJgNkUblhgAKbm06YA1AHZEAKhEwA5EwHD-spgFZEStTDlweMcU1Z7qE6R2XqJAFkTGDiVQMdaYAGnkBaAAgt4GABQfGIAOwB7QhgAfF86AFx4xAAcZJgAPHS4uizE9IACbMLixDg0AGUIgAcAOjQAIQBDAGdagrBiSlJCJtCAEwKWogBXAHMxyiH8JsJ8AEswse9bSQ0OrrJege9hwnHJ4l2ZucXl1Y0AGLpEAH.EYgBSAGCANyA___",
            fa: "IgYAwgggzAAAgDGANhyAgaBAmBgAXAJwFMAjAGyMQAhEYAqKuAVhioEpGA2RAckYA5EDOLHZVMAagBMiABSNY9RixgSBrDnG5KtvBXP0w-kmTABk-sbvNchlzYoA0tmAFoACHEEI0JAIYAzgEwAPjutAAE4YgAhNGh8VG0AHjxYbQAuPFxkWnRcGgAygD2AA4AdGgAQoHlEWBEFCQEfnhEACYRAYQArgDmfRRdeH4EeACWAHZ9rgAsAOxM9Y2kLW3trt0E.YNEmyNjUzMLTAAxtIgA.4hEZgB5AG5AA_",
        },
        mixolydian: {
            soprano:
                "IgYAwgggzAAAgDGAPByAgaBAMBgAXAJwFMAjAGyJgHIAERGAKjsQEpmYAKdp-ganYC07ADTsAdO37029LvVqI4mNCQCGAZ3WIAEPQAE2uAA5EAPEMA2RAHxDAVkQG4sGAFxLN-4gA4HmObgrGF9jRABsQxdfTF4AJkR3Z0QALD8AoPcY-OC0yPC8nKyEvwBMApCrGlskmD0aULg0AGUAewAHMTQAIQ0xPTAiChICVTwiABM9dUIAVwBzOYopvFUCPABLADs5gQAWAHY7fsHSEbHxgWmCecWiS5W1rZ2DuwAY-kUYADQiADIACwAikA__",
            "Do Alto":
                "IgYAwgggzAAAgDGANhyAgaBAAoAYAFwCcBTAIwBtjEAIRGAcmrgA5EAKJ2GAaiYDZEAKn6JGcLhzgCYAUk6IAZPJiSArKOXCp7ZQEpqmbgBYhTVipENLvcadsAEALSWAdPZbwYaAIbl8AexgAAns6AHxQxAA8SJgAHFiAXFiY8NiAYliAIliAQliQxDg0AGV.AAcXNAAhbwBnFyCwYkpSQm98YgATILqiAFcAc0HKXvxvQnwASwA7QccjAHZVJpayds6uxz7CIZHibfHJ2fml1QAYukQAf8RiBQBfAC2gA__",
            tenor: "IgYAwgggzAAAgDGANhyAgaBAAoAoAFwFMA7AewCcYByABERgCo7EBqZ69gCnYEp236Tet3q1EcTGgBGAQwDOcxAAh6AAiVwAHIgB4GgGyIAhBtgx1cAKyIA-AcQXtMPXDN3XupZhYAWRAFx7Zw1rGECPGHdDYLhowO8AdkQAHHsadzNVGi14NABlUgAHADo0ACF5YtUwQgAbQilyGSIAE1U5fHIAVwBzHvr2.BlyfABLYh6AWh8Ey2q6hqbWyY7uvvqVoZHxqZnLABj6RAB.xEIAUgAmABSgA___",
            fa: "IgYAwgggzAAAgDGANhyAgaBAAoAYAFwCcBTAIwBtjEAIRGAcmrgA5EAyJgNkUcwGoA7IgAUXRAFImsGABIpE6vwAs7eQ0V8VMUXG4xJcaXJarDiAMTyACB108rJhGlIBDAM5uYATCt0AWL6IADiBMADYoQC4oSF00f6hPohwaADKAPYADgB0aABC7tkABGDElKSELvjEACZFbkQArgDmzZT1-C6E-ACWAHbNALRKAgCsJWVkldU1gw2ELW3Ec53d.UMjowAxdIgA.4jEbADejUA_",
        },
        aeolian: {
            soprano:
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyJgAoAERGAKjsQEpmYBqdp-gGm.Zt6tRHExoSAQwDO0xAAh6AQnlwAHIgB4qgGyIVcWDAAEqowFxdiAPhWTqgKz6zWu6bh6Yt9a4.PDMDTeTjTuRko0PnBoAMoA9gAOAHRoAEIyScZgRBQkBJJ4RAAmxtKEAK4A5pUUpXiSBHgAlgB2lQC0ACwA7A5ZOaT5hUXtZQRVNUSj9Y2tHT0OADH0iAD.iEQAZAChAFdAA__",
            "Do Alto":
                "IgYAwgggzAAAgDGANhyAgaBAAoNBDAGwBcB7GAQgAREYACaxAfAbpapoFwWA8F5m9ono0ARGwZxMaAEZ4AznMQAIGgCwlcAByJuG2DADYGgGyIOG7TAA4SzAGoATIiNxT1jQFZE614gCYtnYA7IgAGCbOeog2cPpG9gAs3hEwAfYhMOGx0SkubrrZMOa-lLRRFJRa8GgAyiQADgB0aABC8o20YACmBF3SAE54RF0AJrRyRP0ArgDmM73jRHj9RACWAHYzALQJQR6dPX2DwyNbE9NzvWdLKxvbux4AMTSIAP-IXQAkAJcApUA",
            tenor: "IgYAwgggzAAAgDGANhyAgaBAmBgAXAJwFMAjAGyMQAhEYAKKuADkQHJGA2RAakdhgBUjFjAA0fRAFoJMXs0QA6GULhcYSuAFYpVTNwAsicXH7S9h9Y21iZc.hrUB6TkdsSACA8SP38hAFA8IgA7AHsCGABCd1oAIhjEAGIEmAASFIBSFOTaLNocxHj8lKLEaMQ4NABlUIAHBTQAIQBDAGcFAAIwIgoSAmaggBMO1sIAVwBzCYoRvGaCPABLYInJfQB2TS6e0n6hyVGCSemiA7mF5dWNzQAY2kQAf8QiDIB2gHWgA",
            fa: "IgYAwgggzAAAgDGANhyAgaBAAoAYAFwCcBTAIwBtjEAIRGACmrgA5EBSJgNkQBInYYAYi6IAVP0QBKCQyYBWRAHIRMAGTz2M5S0SM43GBziwACOuMwT2g.RM6EaUgEMAzi5gAsE3QCY3xAA4.jAAuMEA2MEAeMFBdJF0XohwaADKAPYADgB0aABCrtkABGDElKSETvjEACZFLkQArgDmzZT1-E6E-ACWAHbNALQALADsciVlZJXVNYMNhC1txPOd3f1DY3IAMXR7JjUAS30A1EA_",
        },
        locrian: {
            soprano:
                "IgYAwgggzAAAgDGANhyAgaBAAoAYAFwCcBTAIwBtiYBKABERgCp7E6GAKFprgai4BouzBm3iY0pAIYBnaYgAQDAETy4ADkQBCVbBgA8VQDZEAAh2IAuEcQAca.vMwA-KoCsiA3GMwr6xC69bRytMHgAWD3sALEcAbFo.ODQAZQB7AAcAOjQAIRlMkzBiSlJCSXxiABMTaSIAVwBzBsoa.ElCfABLADsGgFowgHZXQuKyMorKvtrCRubiabaOnv6h1wAYhkQAf8RiADIACMMgA___",
            "Do Alto":
                "IgYAwgggzAAAgDGANhyAgaBAmBgAXAJwFMAjAGyMQAhEYBKKuADkQApGA2RAUkdhgDkfRAGJOiAGTDBVTAGoALG2kN5AdkQAqRgFZlcfgzhcY7OHpkGt4yxbMm6ABGbwYaAIZk8AexgAiR1oRQJ4QmAASMODaCTDI2m4osIDEODQAZW8ABwA6NAAhdwBnHIACMCIKEgJ3PCIAE1KiwgBXAHM2iia8dwI8AEsAOzaAWgU1HXLK0hq6-pHmgnbOogWevqHR8Z0AGNp9gCQiAAwiACggA__",
            tenor: "IgYAwgggzAAAgDGANhyAgaBAMCgAXAUwDsB7AJxgCIAERGAAlsQHwmYA8N1ugXDcbrdEnOjToBiNmPiY0AIwCGAZyWIAEHQDYauAA5hO2DG1wAbIh6HEALB3mYAHCvG1mANQAWG3cQBMV24A7IgAGD4ucEZOcACsiCb2lpHeZojRRv6pMEn2Jvoc4bbJxtR68GgAyiQADgB0aABCyrX0YAQANgRyZAqEACb0SnhkAK4A5mOdg3gKZHgAlkRjALQegTGtHV09.ctDoxOdezNziytrMQAxdIgA.4gEDgAavkA_",
            fa: "IgYAwgggzAAAgDGANhyAgaBAAoAYAFwCcBTAIwBtjEAIRGASmrgA5EAKJgNkQHImBWdk1gMuvYYgBk1TAGoATIgCkEmAComrUXG4xpcEXwNSZC5ao47E9AAgt4MNKQCGAZ1cwA2DboAcH4gAuAEwAHgh.nTBdOF-Id6IcGgAygD2AA4AdGgAQm6ZAARgxJSkhM74xAAmBa5EAK4A5o2UtfjOhPgAlgB2jQC0ACwA7PxFJWTllVX9dYRNLcSz7Z29AyP8ADF0iAD.iMSSAGoAMEA_",
        },
        aionian: {
            soprano:
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyJgCoAERGAajsQDpmYBadgGna.oD0PPuyb1aiOACg0JAIYBnBYgAQ9ADgq4ADkQBsLbBgAsFZgYAWRAEwtumJrgBWRKbgA2RAFxDiR0dsPb18TLU8YH2c.MMQAAhiHEMijN3DA8IM4I3UaHXg0AGUAewAHFjQAIUUWWLAiChICOTwiABNYhUIAVwBzHooOvDkCPABLADsejgsAdida-tImltaOToJe.qI1oZGJqdmnABj6SRgAFCIAUABlgEygA___",
            "Do Alto":
                "IgYAwgggzAAAgDGANhyAgaBAM0EMA2ALgPYwDEACIjAORWICk9MAZMwFTMCUzb1T1ACTNKiOJjQAjXAGcZiABDUAOArgAORAGw1ANkQA8NbBiq4JnZgDUAFkQAsPYgC4xxGc0xHcfTFc.tNU9vX38TAEwnUzcYSLgAVkDzdwoNeDQAZWIABwA6NAAhWVyAAjAAU3xyyQAnXEJygBMSmUIagFcAc06qlsJcGsIASwA7ToBaGwB2eLLK6rqGxvHWju6qlf7B0Ynp-IAY6kQAf8RywQAfkaA___",
            tenor: "IgYAwgggzAAAgDGANhyAgaBAAoAYAFwCcBTAIwBtjEAIRGAKmrgA5EAKJ2GASmswGoALIkZwAbIgDknRADIZMDuLlMJDBbzhcOAgExTVifgtGseffgHZ2C48sVMArIk1r6ABBbwYAUHzEAOwB7QhgAHHc6AHxIxAA8WJgAXESAQkSAAkSAIkSAYkSYuhS6CMQ4NABlIIAHADo0ACEAQwBnOoywYkpSQmb.ABMM1qIAVwBzccph.GbCfABLAPGAWkFLR07usj7BlZHCCanifdn5pdX1xwAYukQAf8RiAFIAGAA4oA",
            fa: "IgYAwgggzAAAgDGANhyAgaBAAoAYAFwCcBTAIwBtjEAIRGAKmrgA5EByJ2BpgNkQDJO7apgDUAFkQAKXogCkQmABJZMGXC4cN0kRMQBKVeoCsBxTLEAmYdu5w-apqZiH7iegAQW8GGlIBDAGdAmAAcDzoAPAjEAFwYsISAfATouni6AAJUhIzEcMQ4NABlAHsABwA6NAAhIMrMsGJKUkJ.fGIAE0zAogBXAHMByh78f0J8AEsAOwGAWnEAdmNG5rI2js653sJB4eJtsYmZ-aXjABi6RAB.xGJ-AAEAcKA___",
        },
    },
    "Type 3": {
        dorian: {
            soprano:
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyJgGoAERGAOjsQBpnr2BadgKnbfp963egMQjW7Wojgg0JAIYBnJYjT0AuGjgAOGAAgA2NtgwA-NoBsiAHgnEWzFQAsiADjaArAeNxrMDzhYIywXd3sYRyoAJkQLP1tQgHYHbT0QoNTMgNDXSIj4vRg7BPy4b2KrVKc8wNMo2JzsgCwvcN1qqhTK0tbsrWyPGqzTPv86zsaJmAACKrLTIbCFxDHEAEx5vorNhJppjRoOuDQAZQB7AAcGNAAhZQYZsCIKEgIFPCIAExmlQgBXADmgIovzwCgIeAAlgA7QGcZxJTxPF6kd6fL6cP4EIEgohY8GQ2HwxGeAAx9BkMAAaEQACQAHoAQ0A__",
            "Do Alto":
                "IgYAwgggzAAAgDGANhyAgaBAIBgAXAJwFMAjAGyMTURgGo04AOGACAEoGA2RACgYFZEAKi6J6mWgHZhomAHIGsGCLiD2WWgBZeixAokAmRADJZ-qTqYy4Svjb0ajMO0vNPTcbst0wAtLJUlfysYABoNaTpZAHofcM8xAUR47nUQl1YOCW1nH3oE-R8-bId7AAQVL1oyqwQ0AEMyPAB7GABcMpoAPE7EAHxemABCQYGaEZoxxAACUcGemg7EODQAZWaABwA6NAAheoBnLemwIgoSAnq8IgATaYPCAFcAc2eKe7x6gjwASwA7Z6-TSSfgnM6kS7XG6-B4EF5vIgwz7ff6A4H8AAxNGxwCIxgxABQgA ",
            tenor: "IgYAwgggzAAAgDGAKByAgaBAMBgAXAJwFMAjAGyJgBIAERGAYjsQDJnH2BSd2-gci7sk7AfTb1u9XvABQAUDxEAdgHsCiNPQC4aOAA4YACADYu2DAD4ugGyIAeDcQ7MAagDsiADi6DMB3FsYHThzB1cAJiczRAAsRz9453d7eLiQr2iTLBcAFgz0mABMRyyC7wio.SNTAv9zJLyEst0AVkQAAnirVw8YToCoiphvAaDW.MCrWujLbMim2FLA4PNy3MrzNMCR82LRtLaaHacaKrg0ABVlADo0ACEAQwBna.awIgoSAgfFABN2p6EACuAHMQRQAXgHgQ8ABLJQggC0OTcLTeH1I3z-iMBBFB4KIOKhMPhSJRLQAMfREAB.xBEFgAWIAy0A",
            fa: "IgYAwgggzAAAgDGANhyAgaBAAoAYAFwCcBTAIwBtjE1EYASNOADkQDJHYYBSLAagCZEDOADZEPTLwDsQxmJjtmiAOQc2fQTFVxOAKjnqdKvgBZDnYS24GFfGddGy4AVkQBiNfVPjGr2468AiWlDK2F5bU4ACm8tNQAEfQDeeKU4bDRSAEMAZxyYAFx42gB8YsQAPHLC6oACaoBCarLaKtoixDg0AGUAewAHADo0ACFcwdqwYkpSQiz8YgATWpyiAFcAcw3KFfwswnwASwA7DYBaEylnSemyOYXFs9XCTe3iJ72Dk.PL5wAY2iAgCgxDoAE7SEA__",
        },
        phrygian: {
            soprano:
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyJgFIAERGAMjsQApmYBydt-p-gKnYBKdl3oj6PRH0S1EcEGhIBDAM6rEaegDw0cAByIABHoBsiXQcQBcPbBgAcLAGoALIgDYegKyIAWGaITnDmMF6YzgDsQYEwtnC-MJb2thHuSXaesQD4mRlpNj4WefH2TgVxeQEhxTWVEdGOeoYZdfGh5VGFdSZw9smFEQBMtWVFYc3-LiMwAJglscGh1S1LWcNTdV4Jm6GlFjRWcGgAygD2AA4AdGgAQmpXRmBEFCQEynhEACZGqoQArgBzQEUX54ZQEPAASwAdoCALSuSLeJ4vUjvT5feF.AhAkFEbHgyGwhFI7wAGPoVIAMF8AIeAulAA",
            "Do Alto":
                "IgYAwgggzAAAgDGANhyAgaBAIBgAXAJwFMAjAGyMTURgBo04AORAKgYDZEBKBgVkQDUHRPUwCA7IOEwAFA1gwecBWzEAWbvMRyxAJkQByaUOWHpOiZtMwAZFkswApNKUqti-.tkNmMNtdcpOH46F3d.ThghMUk.MODtdx51Vj4gyNoABCZ4GDQAQzI8AHsnTJobcsMqmAAiGoACGoBCGoMaxxrKmk7EODQAZWKABwA6NAAhfIBnUYawIgoSAny8IgATBunCAFcAcz2KLbx8gjwASwA7PYBaNXFeecXSFbX1m-2CfcOiD5Ozq63e68AAxNEQAH.EEQbABsgAqQA__",
            tenor: "IgYAwgggzAAAgDGANhyAgaBAAoAoAFwFMA7AewCcYBSABERgHI7EAKZmAMndvqfoBJ2AYm7su9HvBBoARgEMAzgsRp6APDRwAHIgA4m2DAAEmgGyINcQwHwsAagBMFg4gC49gCx6ziW1beaAKzOmHZeMH46MBqhTjDu.tH2cSZw5hH2AOzO2t6Jlob6cMEwANg-SYnlifqxiNWGCVGW6e6h2TBFUX4lRY3JeYbloeEAWBW1YYjjaQH5NLlwaADKpAAOAHRoAEKKG0ZghAA2hDLkckQAJkYK-OQArgDmjyc3-HLk-ACWxI8AtB5MoEDsdTucrn9bg9nidIe9Pj9.oDAgAY-iIAD.iEIVBYAAYgA__",
            fa: "IgYAwgggzAAAgDGANhyAgaBAAoAYAFwCcBTAIwBtjE1EYAaNOADkQCpGA2RAOkdnr6IA1FiEAmRAzj8A9J0QBaQQMzjhjFgOk9GAVkWiALJOVy4XGCPOIAFMqub2cfTADkyu6uNvlTi3e0YAEojNj1bX2UQ1QkYJ34AzRDAzzUfZkRkhKjQuPDLeXoABAy4bDRSAEMAZ2qYADwi2gAcJsQAXDaYVtoAfC7Gvq6AQi6AAi7-2kH4NABlAHsAB14AIRruMbBiSlJCSvxiABMx6qIAVwBzS8pT.ErCfABLADtLhUMAdl0tnbJ9w5HBRnQhXG7EYH3R6vd5fXQAGNoSN6xAAZABMgCVQA___",
        },
        lydian: {
            soprano:
                "IgYAwgggzAAAgDGANByAgaBAMBgAXAJwFMAjAGyJgDIAERGAcjsQGJmYASdgUndvqb1e9ABTtBifvBBoSAQwDOCxGnoB8NHAAciAISaAbIgC4m2DAB4ZxBswBqAEyIrccwAJNOmPteIP9gBYbTQBWZ0MTT3D7JxgNOCMYDzgwmAAcaxhTGMQM3xgATAiACABsUNysOyCszIzAmDKImAAsKoB2RCLtRvKEyvzsxwHzbsS23yac9KjWzJdzIZq81IWbGh64NABlAHsABwA6NAAhRUO3MCIKEgI5PCIAEzcFQgBXAHMPihe8OQI8ABLAB2HwAtAF2iFLtdSHcHo8wa8CJ9vkQkX8ASDwZCQgAY-iIAD.iCIVAAxQBSoA___",
            "Do Alto":
                "IgYAwgggzAAAgDGANhyAgaBAAoNBDAGwBcB7GAfAAREYACaxAQgbpapoDwXmb6b34uAEZ4AzqMRp-aOAA5EAXBmwYAHBkBWGAAgA2DIBsidXC2S4RmB2XHDia5gDUAFkTkbau1Y9Knr73AqJmZKgfZYjgBMih4AWF4mKr5RtmF6Ef7xcjr6TgDsqZbuYQFJGYXhJVTZcGgAyiQADgB0aABCYs20YACmBD1CAE54RD0AJrSiRIMArgDmc.2TRHiDRACWAHZzALTOeRrdfQPDo2M7U7ML.Rcra1u7-xoAMTSIAP-IPQAMAJ4AI0A__",
            tenor: "IgYAwgggzAAAgDGANhyAgaBAIBgAXAJwFMAjAGyMTURgDI04AORACgdhgBIGA2GACACUvVgwCsienA4ByLAGoALKLh8hCgOwq-MADTtEAKhEx5mxPumIzmeVpjG4E9beUw2V0ybme2rxD4cjmrCqkbmXkyIALQG6p7G.pESMD7M7nHCSR5B4gKhuUlmThYm0QAIUQgAoHhEAHYA9gQwAPjlNAC4HYgAOD0wAHgD7TTDXQMABCNTM4hwaADKjQAOAHRoAEIAhgDOa5NgRBQkBNt1ACaTu4QArgDm9xTXeNsEeACW9ffRihpih2OpDOl2iNwIDyeRDBr3eXx-fzEABiaPNEEQAKQAJIAYUA___",
            fa: "IgYAwgggzAAAgDGANhyAgaBAAoAYAFwCcBTAIwBtjE1EYAyNOADkQApHZ7GWYBSRgGyIGmANQB2RPzhCYAEkYBWRAGIOiBWIAsUpcMEaDfLBP3M26rjMQByE5Kuz25mHbid2225YBUR57AAEACUJjowfnDKMAEwIZaeogBMcaHuutb0AAjmCGikAIYAzkUwAPhZtAAElYgAhLXljQ20AHiNFdUdtXBoAMoA9gAOAHRoAELFI1VgxJSkhAX4xAAmVUVEAK4A5tuU6.gFhPgAlgB22wC0WuKKM3Nki8srlxuEO3vEr4fH51c3igAMbQQQB4Yh0AAFAGQgA",
        },
        mixolydian: {
            soprano:
                "IgYAwgggzAAAgDGAPByAgaBAMBgAXAJwFMAjAGyJgHIAERGAKjsQEpmYAadp-gana592AOgEj2.em3oAKdrURwQaEgEMAzusRp6ATDRwAHIgDYB2DAA4BgKyIAWOdNZeAJkTWjiAHgGAbIgAuP4eLgDsQSEwAAROML5wFsGYvAAsoXB28XEA-LY-UZ7G2XABMGaJoSnu5XHBXlZ1LjUJxZ4WeaUFKREwnWX1xQlJLumNmQWV4xZmKWPtDlHDkXMZWcu1U46rmxbWPZFd2Qcw9WWxU50Wvjv1djRXiNE0XnBoAMoA9gAOwmgAQhphNEwEQKCQCKo8EQACbRdSEACuAHNkRR4XhVAQ8ABLAB2yIAtKkwjYQWDSJDoTDCQiCCi0URaZjsfiiSSbAAY-iIAD.iCIADIAFsAdSAA_",
            "Do Alto":
                "IgYAwgggzAAAgDGANhyAgaBAIBgAXAJwFMAjAGyMTURgHI04AORASgdhgFIGA2RACnassAagAsAoTBG9EAKlkw2cAKyJ6cDgrh8YgncMwiA7JINcpAMincjAJkTXNw8xo6CjEulO279HenszDjZPeQZmJVFTPUVtSI0.aJdImWcYbQ4ZMJgAGgY1AAQAWkUAOkKmeBg0AEMyPAB7GAACQpoAfHbEADxumAAcfoBcfr7O.oBifoAifoBCfrbEODQAZUaABzK0ACFagGcylrAiChICWrwiABMWg8IAVwBzZ4p7vFqCPABLADtnsUxMYVCczqRLtcbsUHgQXm8iDDPt9.oDgSoADE0RAAf8QREsAHKAIlAA",
            tenor: "IgYAwgggzAAAgDGANhyAgaBAIBgAXAJwFMAjAGyMTURgHI04AORASgdhgFIGA2RACnassAagAsAoTBG9EAKlkw2cAKyJ6cDgrh8YgncMwiA7JINcpAMincjAJkTXNw8xo6CjEulO279HenszDjZPeQZmJVFTPUVtSI0.aJdImWcYbQ4ZMJgAGgY1AAQAWkUAOkKmeBgAUDwiADsAewIYAAJCmgB8TsQAPF6YABxBgFxBge7BgGJBgCJBgEJBjsQ4NABlJoAHMrQAIQBDAGcytrAiChICQ.qAEzbjwgBXAHNXike8Q4I8AEsGq9imJjCpzpdSDd7sUngQ3h8iDDvr8AUCQSoADE0RAAf8QREsADKAI5AA",
            fa: "IgYAwgggzAAAgDGANhyAgaBAAoAYAFwCcBTAIwBtjE1EYByNOADkQBJGBWRAUkYDZEAMn6IGmANQB2ISJgBiRrBi84S9hIBMPRYgAUshnAEx9E6fVntVM68qzitMYbYCUBxiyf3zK426PatsISACyBYRZwXPI6MOriESpcAAjOxnTJzPAwaKQAhgDOBTAAmMm0AFjliAA41TAA2PUAuPVltHWVbdVwaADKAPYADgB0aABChSMABGDElKSEefjEACbTBUQArgDmO5Qb-HmE-ACWAHY7ALQhkhyz82RLK6tXm4S7-8RvRycX17cOAAY2iIAD.iGIggAJQADoA_",
        },
        aeolian: {
            soprano:
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyJgAoAERGAKjsQEpnr236AadganZN6XRLURwQaEgEMAzrMRp6ALDRwAHIgA4agGyJVGxADw9iALhY-Adm1rNMU3FgxLcfTAD4VgCyIABGoubh7ezgFWAEyIYS6mmHx-rmYwOgm2ye6IANj2duEwuQlJhgCsiACYKbkFaXzRhUEWeY4plukmKYbBKU7lmfo0gQUAhDRGcGgAygD2AA4AdGgAQnIL.mBEFCQE0nhEACb-soQArgDm5xTHeNIEeACWAHbnALQ-1qUbW6S7-wevE4EC5XIiA273Z5vD6lAAx9EQAH.EEQAOQwABbQA",
            "Do Alto":
                "IgYAwgggzAAAgDGANhyAgaBAM0EMA2ALgPYwAUACIjAKRWIBk9MA5M5dQCTN3VPUdEvRAEp29OCDQAjXAGc5iNNQBYaOAA5EADHWwYAHHUA2RAEwTiNXACsiI3H0BsLAGoALFcswLmVwHYvOFMYAFw9cwiYNT9PQ28LR3tvFz9A-ODEcNtEFyT4vwAmXKjdTJ9vXTTI8od9axDfAKCQ7P0HENTm6PUtDMbvOqC7GC647JCAPHURiZgKAAIogEIKTXg0AGViAAcAOjQAIXk9hbAAU3xz6QAnXEJzgBMFuUIbgFcAc0-rl8JcG6EACWADtPgBadz-GxnS7XO4PR7g14fb5XZH.QGgiFQmwAGOoiAA.4hzgwiQBOoA_",
            tenor: "IgYAwgggzAAAgDGANhyAgaBAIBgAXAJwFMAjAGyMTURgAo04AORAKgdhgDIGA2RAcl6J6mANQB2AUJij2w6QEosE1g2Z1FcjWIBMiJU0Sy4HNnD4wAtMr0wAdFrMWANFtljJMVyfnnVfmAMAVn8LQR8NAIBSLXoA8JDAtXldKQDjDjiLJQ9fFzctVzEAFiM5AAQHAIB6csMEAFA8IgA7AHsCGABCcpoAIl7EAGJBmAASUajRkZopmhnEAfnRpcQexDg0AGU2gAcHACEAQwBnOwACMCIKEgIj5oATc5PCAFcAc3eKZ7wjgjwAJYtd6WYriIKXa6kO6PSwvAgfL5EOG.f5AkFgoIAGJoiAA.4giJwAL8AHqAA_",
            fa: "IgYAwgggzAAAgDGANhyAgaBAAoAYAFwCcBTAIwBtjE04AGRAChoA5EBSGgVkQDIaA2dgN5YA1AHZEAchZC4gmE3mIAlGMmLhMDnFgw-u6WIAsIw9rEAmRAGJZMACRW5ep5lHWYd5Y.W2tMuY6enzupjCB3Jo-TkEmiLGwAAiBCgxJcKwIaKQAhgDO-TAAWEmIMACYZYgAONUwALj1deUAeM31ANj1pYhwaADKAPYADgB0aABCBWMABGDElKSEufjEACaz-UQArgDme5Rb-LmE-ACWAHZ7ALTG4pzzi2Qra-s324T7h8QfJ2dXW73TgAGPKiAA.4hiDwAK8AbSAA_",
        },
        locrian: {
            soprano:
                "IgYAwgggzAAAgDGANhyAgaBAAoAYAFwCcBTAIwBtiYBKABERgCp7EBqFmACg-YbofYNeifvBBpSAQwDO0xGgYBsNHAAciALgqArImVrEALBWwYyzKwBMRk4gB4KgGyaV6mA4sB2RAHwniAAIdX1t3LFYAFhc4XRg.OFMHOGc44LDkxAAcV2iU7K9cxABMUP1TfKtotzL7fxgtAvSU4wS9WgM4NABlAHsABwA6NAAhGQGAsGJKUkJJfGIAEwDpIgBXAHN1ymX8SUJ8AEsAO3WAWgjPbQmpsln5hdOVwg2t4kfd.eOzi-0AGIZEAB.xDEADkcAAHkA",
            "Do Alto":
                "IgYAwgggzAAAgDGANhyAgaBAIBgAXAJwFMAjAGyMTURgEo04AORAcgYDZEBqB2GACg6J6mLgHZEguJxgBSXqwUCsXACzCGAVkVw-AMiXzRAJkQHdG6ZKEwDo9XKVSZ5mW1ETbNwR8syAVCqe9FbKcNowbKE-4pbMkd428hYJ4dahtAAITPAwaACGZHgA9jAARJk0AMSViLK1MAAkDTU0AIQNzTQV1Q098GgAysUADgB0aABC-QDOYwAEYEQUJAT5eEQAJvMzhACuAOYHFDt4-QR4AJYAdgcAtKpimovLpGsbm3e7BIfHRF9nC43e6PTQAGJoiAA.4giCwAFsAeCAA___",
            tenor: "IgYAwgggzAAAgDGANhyAgaBAMCgAXAUwDsB7AJxgCIAERGAAlsQHwmYA8N1ugXDcbrdEnOjToBiNmPgg0AIwCGAZyWI0dANho4ADmHaArIh7aAbIi1xzMAFhYA1AHYLZ.XFgwT7xABwHAFmNtDzsrX2CXTHtA20Nw71iwmABMB2dE6y8PVLgjWKiAJhcEu0LEHL0YP1zi63YIzwa.KJisxFDrao8tFviQuMak5qdiyq9rUO6HIo5XRO7qXXg0AGUSAAcAOjQAIWVN-jACABsCOTIFQgATeiU8MgBXAHMn09u8BTI8AEsiJ4BafyOAyHE5nC7Xf53R4vU5Qj5fX4AoEGAAxdEQAH.EAQAOQASYA50A___",
            fa: "IgYAwgggzAAAgDGANhyAgaBAAoAYAFwCcBTAIwBtjE1EYBKNOADkQGpHYYByRgNkQAUfRADIsrACyIApB0HCYYuJx6ZJ8uAFZRCnsp1qATDMYtucmLP2LxUyxaFx-9BQCpxAdkQMnG7eeshNTs9TjEjE2tw9QD.R2c6AARmeBg0UgBDAGcsmABsRNoAHELEAFxSmAA8SpLaCtoa4sqCxDg0AGUAewAHADo0ACFsvoACMGJKUkIM.GIAE1GsogBXAHM1yiX8DMJ8AEsAOzWAWgkPTXHJshm5-ZPlwnXN4gedvaPT880AGNpEAD.iGIXAA6wAPoA__",
        },
        aionian: {
            soprano:
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyJgCoAERGAajsQBpmYBadp-t-r-gHp2fRADp2AxD0S04ADngAoNCQCGAZw2I09ADhoFiAHiGAbIgNGYAfHMnDAVkQBcQ7Fv2YVj28wMAJkt3RABMLwAsLwN.ABZEKLgLGDc4DwBsEO8sQMRMtLCnYIKYTLjij1NrVMqcoJSsgEIvOxLTcoa4Z08SgAIWnIB2B2t-pJHfHPiYKoyvGod.eoWYROT8jyiO8K68rL0aIzg0AGUAewAHMTQAIU0xXrAiChICNTwiABNejUIAVwA5gCKD88GoCHgAJYAOwBHFig0cj2epDeH0-HF-BEBwKImLBEJhcIRjgAMfREAB.xBEADkIAgQA__",
            "Do Alto":
                "IgYAwgggzAAAgDGANhyAgaBAM0EMA2ALgPYwDEACIjAORWICk9MAZMwFTMCUzb1T1ACTNKiOCDQAjXAGcZiNNQA4aOAA5EAPFUA2RACxVsGAGxdiALhYA1ABYtRxGbh6YKuMbOY7B1QFZEAExzGEMXIJsAdl9wmCsPRHcNUxsAJhjjbVj41xVvaLiQ4ITCkryfUuMw12LXLwr3Kv8nR1CbexhigJSyinV4NABlYgAHADo0ACFZMYACMABTfAXJACdcQgWAE1mZQlWAVwBzI-XdwlxVwgBLADsjgFpbSL95pZX1za2HvcOT5Z-Fyud0ezz8ABjqIgAP-IBY0ADbACggA_",
            tenor: "IgYAwgggzAAAgDGANhyAgaBAIBgAXAJwFMAjAGyMTURgCo04AORAGgdhgEosBqAdkQAKdom6YeAFkT04AViEi6DAGyiG8mAHJFM1TABki7eKkHFwuYkNw9YngCZp5hsy7Pxjt3A5sbiHjq8ngHeiNp-MBa2vAKRKqyKALQuCeKxIXoWHNYcxpJWitwRtAAITPAwAKB4RAB2APYEMAA4JTQA-G2IAHhdMAC4fQCEfQAEfQBEfQDEfZ00gzStiHBoAMr1AA4AdGgAQgCGAM7bo2BEFCQEBzUAJqNHhACuAOYvFA94BwR4AJa1L0SEj4sjOF1I1zuiUeBFe7yI0K-P3-gOBsgAMTREAB.xBEbQAcSAA",
            fa: "IgYAwgggzAAAgDGANhyAgaBAAoAYAFwCcBTAIwBtjE1EYAqNOADkQBpHYYBqRgNkQZx-MAJSMArAL6IA5B0QAyeTDmYuAFkQAKCYuUBSZUrWaYOoYkNxOgyaKwbtRxixXO1AJlnKAxNJhK1pYOXgHKqo72QWYhiGLRPHB2gsLxyf5y0YGcEabZcf50AAjM8DBopACGAM7VMAA4RbQAeE2IALhtDV0A-F2ttJ20AAT9XUOIjYhwaADKAPYADgB0aABCNcvDYMSUpISV-MQAJsPVRACuAOZXlGf4lYT4AJYAdlcAtOoA7OLbu2QDkdjh9zoRrrdiKCHk83p8fuIADG0FEAUGICgAogASoA",
        },
    },
    "Type 4": {
        dorian: {
            soprano:
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyJgGoAERGAOjsQBpnr2BadgKnbfq16ACi792Q-BhIBDAM5zEACESYAuErgAORBsxUALDEwAcTQFZEZuLEwACTQDZEDuJZgB8J4gB4S.QDsxho2uv5UQaaaOjDWtq7OMK6WmF5wiWm2AITRiDnpxgAkmrAwxfoATDA0AMQliIU02lIAygD2AA4MaABC8gx2YEQUJAQyeEQAJnZyhACuAOYLFDN4MgR4AJYAdgucBgHmg8OkYxOTnLMEi8tEl2sbO3sH5gAx9IgA.4hEAOQAVwBdoA__",
            "Do Alto":
                "IgYAwgggzAAAgDGANhyAgaBAaBgAXAJwFMAjAGyMQAhFMBqKuADkQfoHYZMAqRgNkS84AVi4AKRrBgT6AJi4ByRixhK4sHv0FV6AFhhUAlJMQS4AzABoTMaxy4NzrHXU4AEIQJh03zeDDQAQzI8AHsYAFw3RBgAPGjEAHwEmAACFPiY9JiAHBTkmMzEKMQ4NABlUIAHADo0ACFAgGca1LAiChICQLwiABNUpsIAVwBzUYpBvECCPABLADtRgFpddmE2jtJu3r7loYIxiaJ96dnFlbXhABiYxAB.xCIAEgB5uaA__",
            tenor: "IgYAwgggzAAAgDGAKByAgaBAMBgAXAJwFMAjAGyJgBIAERZOxAUkZgDJWByV2-7-ln1YcBPRnDQBQPEQB2AewKIAEIkwBcZXAAciTZgDUAFhiYAOFoBsiC3FiYABFcRPDAdlMB8LbpjfDAEymAHhasDCh7qaadnrKhiYwtgCsiKE6prbhKSFhafEGQRp5MPqFMDRZejQZEgAqcgB0aABCAIYAzo0OYEQUJARtMgAmDh2EAK4A5lMUY3htBHgAlrJTALRGbsk9faSDI-vjBNOzREcLS6sbW8kAMfSIAP-IRJwAuwD9QA_",
            fa: "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyJgGoAERGAOjsQBpnr2Badt-p-2vV6IAlD3aD4GEgEMAznMQAIRJgC4SuAA5EGzFQAsMTABxNAVkRm4sTAAJNANkQO4lzAHwniL9uMabXSV9ACZja1gYax0AKABsbyUEwMwATAtEdLhnKM1IrNsAnL0qMJoI3Ro.ODQAZQB7AAcGNAAheQY7MCIKEgIZPCIAEzs5QgBXAHNJilG8GQI8AEsAO0nOAwB2cy6e0n7Boc4xgimZomP5xdX1rfMAGPpEBBiiABIAKYA3IA",
        },
        phrygian: {
            soprano:
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyJgFIAERGAMjsQApmYBydt-gSnYBU7fvS70m9WojgYSAQwDOCxAAhEmAHgq4ADkRbMAagBMMTAFxtsGJbgBWMwHwriZ3FOaXMA4YAsZ2wcbbQA2MwACbT0YSKN.GDcggCIoiK9I3TMtOGsfU2Cc.RpMmQBlAHsABwA6NAAhRWrwsCIKEgI5PCIAE3CFQgBXAHMhij68OQI8AEsAOyGAWl8Adjtm1tIOru6F.oJh0aJdiam5xZW7ABj6aRgAWG6AQ4AlABOgA__",
            "Do Alto":
                "IgYAwgggzAAAgDGANhyAgaBAaBgAXAJwFMAjAGyMQAhFMAaKuADkQcwGoB2GDxgNkTtGAVh4M4AmGy48hEwVQ4AWHgCpGsGOrixMAWkYsYBna36IDysRrOmYc0VIAIzeDDQBDMngD2MAKROiDAAZEGIAOThodEAFNFhwVHB8cGJiIGIcGgAyj4ADgB0aABCHgDOhQAEYEQUJAQeeEQAJlXlhACuAObdFO14HgR4AJYAdt16SpzCNXWkjc0teh0EPX1EK4PD45PTwgAxwYgA.4hEEQAPAC9AA",
            tenor: "IgYAwgggzAAAgDGANhyAgaBAAoAoAFwFMA7AewCcYBSABERgHI7EAKZmAMndvqfoGJu7LvR7wMAIwCGAZxmIAEIkwA8BXAAciNXFiYA2OoBsiQ5gDUAdhiYAWOq0x7cE5gC462DA8WATDYAcT0QguABWG0MXUwU.G2cvZwjVB21Y839vYJgVGk1xAGVSAAcAOjQAIVlSgAIwQgAbQglyKSIAExqZfHIAVwBzfqau.ClyfABLYn6AWgAWSzC6xubWjpnuvsGmjdHxqdmFsIAY-kQAf8RCKhmAfiA_",
            fa: "IgYAwgggzAAAgDGANhyAgaBAAoAYAFwCcBTAIwBtjEAIRTAUmrgA5FG5ZMAqJ1mHzAGoA7DEwBKJgDZEkoaMwAKaYmXyxAchUwtHMez6N1mACTazQgCxiAxE1gw7cGQ15tq6mGedsACC3hsNFIAQwBnMJgAPF9EGAAcWMQAXCSEtIBsNJi4gHw0gEJstPy4nPg0AGUAewAHADo0ACFw-oACMGJKUkIQ.GIAEzawogBXAHNxymH8EMJ8AEsAO3GAWkthAFYOrrJe.oHVkcIJqeIj2fnltY3NgBi4x4AUAYApgBOAeiA__",
        },
        lydian: {
            soprano:
                "IgYAwgggzAAAgDGANByAgaBAMBgAXAJwFMAjAGyJgDIAERGAcjsQGJmYASdgUndvqb1e9ABTtBifvAwkAhgGd5iABCJMAfGVwAHIk2YA1ACYYmAHhbYMC3ABspgISXETwwBZTAAi0BWRN7tEABxnGAAsLXtMAFxQ2PdTELg.GCTYTAD7GG9DEw1QzUDrApodaQBlAHsABwA6NAAhBVrPMCIKEgJZPCIAE095QgBXAHMRigG8WQI8AEsAOxGAWjcAdh9W9tIunt6lwYJR8aJ9qZmF5bWfABj6RAB.xCIRAFAAKSA_",
            "Do Alto":
                "IgYAwgggzAAAgDGANhyAgaBAM0CMCGAzoTAPgAIiMABJYgIR0wB4TtVjVARG054u0QVEcDAWKIAEIkylJcABxDJmANQAmGJmbzYLFaoAsWgLi7EZtZswAcczDtwArFp1w9OtcZhnniN7CYvgBsFgbGtvIuDvKhsvZyVv4J5IrwaADKAPYADgB0aABCRHnUYACmADbluABO-AAu5QAm1IQNtQCuAObd1W0N-LUNAJYAdt0AtIYA7E5lVTX1Tc2T7V291WuDw-NTs04AMVQiMADI5VwAxwCpQA",
            tenor: "IgYAwgggzAAAgDGANhyAgaBAaBgAXAJwFMAjAGyMQAhFMBaKuADkQblgCgBKRgNhio9MAagDsMTAAo-iaSIAsEgOSNYMFSIBMEgGSMWMPewnS4AVlmrEwmTAYjxmADS2X5iW352qDxG690AAjM8DAAoHhEAHYA9gQwAPiBiDAAuMmIADgZMAB4OUkp6SmFiAAEOQCEORUlGXBoAMoxAA4AdGgAQgCGAM5tZWBEFCQE3ZEAJmW9hACuAObzFNN43QR4AJZR83TyomaDw6Rjk3QzBAtLRGer61s7e2YAMSmvALBESgB.X0A___",
            fa: "IgYAwgggzAAAgDGANhyAgaBAAoAYAFwCcBTAIwBtjEAIRTAKmrgFZFHMBqAFhmwEomsagLgA2GJgC0gxNLgAOCQHoZMFZwBMEgHRNFMXXFgMm4mIxYSAZHsQ2jiAKSm7ABAXwYaUgEMAzn4wAPiuiDAABKGIALhRwXGRYQB4cSFhiYhp8GgAygD2AA7aaABC.trhYMSUpIQ--MQAJuF-RACuAOYdlC34PoT4AJYAdh2SXADszJXVZHUNjZKthJ3dxEt9AyNjk8wAMWGIAP-IxADkAJ9HQA__",
        },
        mixolydian: {
            soprano:
                "IgYAwgggzAAAgDGAPByAgaBAMBgAXAJwFMAjAGyJgHIAERGACjsVvoFJmYAqTgSk4A0nANSce9fvXGJJiJvVbwMJAIYBnNYgAQiTAAItcAByIDmYQCYYmAPiHYMO-auYAePcTvj1gISGArIh-cLBuhgBsnhHWBiGmWuYALNYAxB4wac7WAETpuVmYwQ5-BbEOZsLJjgFBCZYx6RVWNHZxMHo03nBoAMoA9gAOAHRoAELqQ3pgRBQkBCp4RAAmemqEAK4A5psUq3gqBHgAlgB2mwC0iQDs.lMzpPOLS-drBFs7RC.7h6cX1.4AGPoiAA.4giAwAEgAMSAA___",
            "Do Alto":
                "IgYAwgggzAAAgDGANhyAgaBAaBgAXAJwFMAjAGyMQAhFMBqKuAVkQbgDYZMB6R2GXhy4A6PolHMuAGjEwZ9AExc2ADlZV6Adi4AqRpxh7JmABSyzQzDLj95dACzqb4jXW0AEALT7x7uGoQ0AEMyPAB7GAACd0QYAHwYxAA8RJgAHFSAXFSU2ITYgGJUgCJUgEJU6MQ4NABlMIAHYTQAISCAZ2FIsCIKEgIgvCIAE0j2wgBXAHMpijG8III8AEsAOynPe00mbt7SAaHhz3GCadmiY4WltY2tpgAY2MQAf8QiABIAY4ApoA___",
            tenor: "IgYAwgggzAAAgDGANhyAgaBAAoAoAFwFMA7AewCcYByABERgCo7EBqZmACnYEp3b6m9LvX7wMAIwCGAZ2mIAEIkwACeXAAciVZhYAWGJgD4agKyJjcAGwGAuGs0w7cM0bWwYxnfswA8U4j84WBV7LXkvc38YbRYAJhgaC2tomg0xAGVSAAcAOjQAIRkc5TBCABtCcXJJIgATZWl8cgBXAHNWiob8SXJ8AEtiVoBaXQB2ExLyyuq6ocaW9oq57t6B4bGTABj6RAB.xEIAUnUAP6A_",
            fa: "IgYAwgggzAAAgDGANhyAgaBAAoAYAFwCcBTAIwBtjEAIRTAcmrgA5FHMBqAdhkwDImANkQDOAFl4BSJrBjTxvACQzEyliJUxGcAKxTN0uMIZNWW6px4AEAUbZX1CNKQCGAZzcwAmFcQwAWL6IADhBMADYYQC4YaF-Pn6B8UFwaADKAPYADgB0aABC7jkABGDElKSELvjEACbFbkQArgDmLZQN-C6E-ACWAHYtALRiXDql5WRVNbVDjYSt7cRzXT0Dw6M6ADF-iAD.iMQAFNRgQA_",
        },
        aeolian: {
            soprano:
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyJgAoAERGAKjsQEpnr236AadganZN6XRLURwMJAIYBnGYgAQiTAEIFcAByI1cWJgB46gGyJDcAKwxMAAnWwYtzHwBMVgPh3EHpwBYrZyxgzLRtjRFsLKwAiTxgYp1dVWLUEmBoI-xUaTXg0AGUAewAHADo0ACFZEuswIgoSAik8IgATaxlCAFcAc26KdrwpAjwASwA7boBaHwB2cxq60kbmlsmOgh6-ojXB4fGp2fMAGPpEAH.EIioANGsgA__",
            "Do Alto":
                "IgYAwgggzAAAgDGANhyAgaBAM0EMA2ALgPYwAUACIjAKRWIBk9MA5M5dQCTN3VPUdEvRAEp29OBgBGuAM6zEACESYAhIrgAOROrgBWGJgAEGgGyITmANQB2QwHwN2mI-sAmQwDwNsGN-sALIYAuBoGMKFaDmaIrrZeToj-Vh6Ykb6R4Y5wviZw5mphOoruMBR5vqoUUZIAysQADgB0aABCck1GYACm-N1SAE64hN0AJkayhAMArgDms30ThLgDhACWAHazALQBNnpdvf1DI6PbkzPzfefLq5s7e3oAMdSIAP-I3ZwANwCMQA",
            tenor: "IgYAwgggzAAAgDGANhyAgaBAaBgAXAJwFMAjAGyMQAhFMAaKuWGBuANhkwGpGOYe4ADk4AqRszFNOASkbCYsqZkl9JsTADpGAVkRahnVn1bMAtL0QB6cZ33N9HTNakxnsAAh2r7gwjQkAQwBnIJgAQndEGAAiSMQAYjiYABIkgFIkxKiMqIio2KisxALEPPg0AGUAewAHDTQAIWCNAAIwIgoSAgC8IgATFqDCAFcAc1GKQbwAgjwASwA7UdMAFgB2bTaO0m7evtMhgjGJogPp2cXl9e0AGKj7gHgiNIB-kCA",
            fa: "IgYAwgggzAAAgDGANhyAgaBAAoAYAFwCcBTAIwBtjEAIRTACmrgA5FHMBqAFhkwHImsGAM49MAMkGJJnVjEZwhAUikMmANjbVRvAYsR6ArLwWb52jgHYYABD1n6NlvBhpSAQwDOnmACwbiDAAeAGIALihMAD4kQA4kSGB8YEA2JH-iHBoAMoA9gAOAHRoAEJehQAEYMSUpITu-MQAJhWeRACuAOadlK347oT4AJYAdp0AtFyWhlU1ZPWNTeNthF09xMv9g6MTU4YAMYGIAP-IxPQAhAAfQA_",
        },
        locrian: {
            soprano:
                "IgYAwgggzAAAgDGANhyAgaBAAoAYAFwCcBTAIwBtiYBKABERgCp7EBqFmAGg.YYDoeHAOQdmDOojgZSAQwDOcxAAhEmAERK4ADkQbMrAEwxMAQk2wYZ.QBZjAAk0BWRA.1HMAYnOIvb4xrgLAIA2e00dGAc4Z3VvGBDEADw4vUNEM0DdWm14NABlAHsABz40ACF5PjswYkpSQhl8YgATOzkiAFcAcy7KNvwZQnwASwA7LoBaawB2R2rasgam5on2wm7e4lWBobHJmccAGIZJGFpiAAo-AGSgA___",
            "Do Alto":
                "IgYAwgggzAAAgDGANhyAgaBAaBgAXAJwFMAjAGyMQAhFMBKKuADkQcwGoB2GTACkYBsifhwAsPAOSNYMKWJ4AyaYiXzMAUmUxNcAKw8AVFqMduMBnCGzBPCy3NVTwm-YAIzeDDQBDMngD2MABErogwAMShiOpRMAAksZFhAISxCWEhYUmImfBoAMr-AA4AdGgAQt4AziUABGBEFCQE3nhEACa1VYQArgDmfRRdeN4EeACWAHZ9ALSinLr1jaQtbe0z3QT9g0QbI2NTs.O6ADFh5wBIRAAYALYAE0A___",
            tenor: "IgYAwgggzAAAgDGANhyAgaBAMCgAXAUwDsB7AJxgCIAERGAAlsQHwmYA8Nxuzu1umnQC4bADhsA2EzgYARgEMAzosQAIRJgmq4ADkRa4ANhiZ222B1WYA1ACYTQ84kc37mUU5ge4AVhMHjGC0bABZEACxtPxhHOFhMSKMIqzsTAExPDN9.T2DUmESLKV14NABlEgAHADo0ACElavowAgAbAlkyeUIAE3pFPDIAVwBzEfb-vHkyPABLIhGAWhCAdh9mto6u3sWB4bH23amZ-aXVnwAYukQAf8QCegAUgCmgA_",
            fa: "IgYAwgggzAAAgDGANhyAgaBAAoAYAFwCcBTAIwBtjEAIRTASmrgA5FHMBqAdhkwAomANkQC4AVl4AyJrBjS4wzAFImEmCrixMAKiasYuzjwZC2qxLoVmjI0zHoAEFvBhpSAQwDOnmAGwHiDAAOAGIALihMABYkSGBEYEAeLGR.ohwaADKAPYADgB0aABCXvkABGDElKSE7vjEACZlnkQArgDm7ZTN-O6E-ACWAHbtALQALFxiFVVktfUNoy2EHV3ES739w2OTYgAxgekwuMSSAEoDQA_",
        },
        aionian: {
            soprano:
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyJgCoAEOADkQGo7YYAaOgNkQFpvmrRLTg8YLUYgAUQ6gI6yJbEYzgAoNCQCGAZx2IAEIkwBiAw0RnMTAEwxMAInNsn1gCz2AhOYCsib5KYALjOiCEWjqEwrrZeUd7u9gAEvogp1naYAPhROXB-mAB45mLFEQA4UZUZiADYVXSqaADKAPYADgB0aABCup1JYEQUJARaeEQAJkk6hACuAOYLFDN4WgR4AJYAdgu8bgDsPoPDpGMTk7yzBIvLRFdrGzt7hz4AMYifCABokwBLAE2AL1AA",
            "Do Alto":
                "IgYAwgggzAAAgDGANhyAgaBAM0EMA2ALgPYwDEACIjAORWICk9MAZMwFTMCUzb1T1ACTNKiOBgBGuAM7TEACESYAOPLgAORKrgBWGJgB4a2DCMb9AAjUA2RFcwBqAOz6A-Gs0x3uxGdswAXBt9Mz1TeUcAJn0guBMgqP1tE1VEmABsYy0Kc3EAZWIABwA6NAAhGWKLMABTfBqJACdcQhqAEwtpQkaAVwBzPvrOwlxGwgBLADs-gFoAFicdarqG5ta2ma7egfrNkbGp2YWdABjqRAB.xBrBAD-ACqA___",
            tenor: "IgYAwgggzAAAgDGANhyAgaBAaBgAXAJwFMAjAGyMQAhFMAqKuADkQbgFYZMBqRgNkS8eAdi5sBMBiK4BKfojk8ATFwAUjFjHU8ALFwDkjWDENwBmOcwVVpmdWcTbuok.Mk3n1h5IAIVhACgeEQAdgD2BDAAOD6IMAD4sYgAeEkwALhpAIRpqXEARGkAxGmFcZlxMYhwaADKYQAOAHRoAEIAhgDOTQAEYEQUJATtwQAmPZ2EAK4A5jMUE3jtBHgAliEzALQ6wux9A6TDY5uTBLPzRCdLK-tbO-wAMXGIAP-IRACkUQAvQA___",
            fa: "IgYAwgggzAAAgDGANhyAgaBAAoAYAFwCcBTAIwBtjEAIRTAKmrgA5FG4A2GTASiYFZEfTtwDUTVjHGZRAdm7suMdoMwAKJrBgaZAFm4ByTYiN7uAMmMxLLRABImSyzPmYApI8QfbDT8uouQn70AAi2CGikAIYAzjEwADghiDAAeMmIALgZaTkA-DnpKdkpBSkABIU5JYhJiHBoAMoA9gAOAHRoAEKx7eVgxJSkhFH4xAAm5TFEAK4A5nOUU.hRhPgAlgB2cwC0urL8.YNkI2PjO9OE84vEFytrW7v7.AAxKe8A8MTmAOIAGEA___",
        },
    },
    "Type 5": {
        dorian: {
            soprano:
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyJgGoAERGAOjsQBpnr2BadgKnbfp96ASnYBSdqPoDEtRHACgaEgEMAzmsRp6AXDRwAHDAAQAbH2wYAfH0A2RADwLiADj6ArI-cw9mKgBZXYzhYTAACYPsYCLhPTCtIxATDRB1EmCcQ1KwqAHYvLOsPIMK0vwAmAqjfPNd9IxgALG80uCiHYM8YN1KcwIzi7pbgy0b0gEw7RGbYxEm2mBoeyx0aFLg0AGUAewAHBjQAIXUGMLAiChICFTwiABMwtUIAVwBzV4pHvBUCPABLAB2r04.ly7jOF1I11ud04TwIbw-RDh31-gOBoPcABj6IgAP-IIgAcgANwARIA___",
            "Do Alto":
                "IgYAwgggzAAAgDGANhyAgaBABQAYAFwCcBTAIwBtjEAIRTAamrgA5FGGB2GTAKiYDZEfOAFZEACiaxqASimIANAKFo4sGPSz0ALCrUTVrDUzEwApMpgASS5P2zV68VoBMiAOSGYD.TDuwGS3Z6LgAEYUENUJZ4GDQAQ3J8AHsYAFxQxBgAPEzEAHw8mAACIoBCItKswqyqgqLcrIzEODQAZWSABwA6NAAheIBnbuKwYkpSQnj8YgATYsGiAFcAcxXKBfx4wnwASwA7FYBabQ4RUfGyKZnZo8XCVfXiO62dg-PTkQAYrMQAf8QxCsAC2AGdAA",
            tenor: "IgYAwgggzAAAgDGAKByAgaBAMBgAXAJwFMAjAGyJgBIAERGAYjsQDJnH2BSd2-gci7sk7AfTb1u9XvABQAUDxEAdgHsCiABD0AuBriwYAPDRwAbIm1YA1AHZEAHBMAORMbMWTB45isAmD.qIAFgm5kZ6YUF6Bo6BGgDY1gAswSYArA6eMAlZMI4-.jCWcC45gUY05VFwGZj2EQ4NRXoZedHZ8U26VU2xBgCYoak1MDR9FpUucGgAKsoAdGgAQgCGAM7zAARgRBQkBCuKACaba4QArgDmlxSneCsEeACWSpcAtEk2adu7pAfHbzOBCuNyIgPujxe70-aQAMfREAB.xBEKgAHYAmkA",
            fa: "IgYAwgggzAAAgDGANhyAgaBAAoAYAFwCcBTAIwBtjEAIRGAEmrgA5EBiJgVkUbgDZEAcjRxYMAGRYA1ACZEAUhGsYw0YgAUXROKaxqAShFj10uQaNClG3TExSmAmPbsB2GAAQAVA8RT3LeGw0UgBDAGcwmABcdzoAfFjEADxE6NSAAlSEuhS6GMQ4NABlAHsABwA6NAAhcIr0sGJKUkIQ.GIAE3SwogBXAHN-ym78EMJ8AEsAO36AWgAWF04GprJW9o7ZnsIBoeIt0fHpucXOABi6RAB.xGJ6AHWAaKA",
        },
        phrygian: {
            soprano:
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyJgFIAERGAMjsQApmYBydt-p-gKnYBKdl3oj6PRH0S1EcAKBoSAQwDOaxGnoA8NHAAciAAT6AbIj2HEAXH2wYAHCwBqACy37iAFjnEjgAg4CxgbIIBWSy9Q1w8YKwcAbD8nIIdvIKMYuAc9TBcAJk8cnxSdIJCMkuyQ5Osa.1cAdkREiphMcuquyND21OCfTMQAQhTTfJaYMcHs3JprODQAZQB7AAcAOjQAIXVN4zAiChICFTwiABNjNUIAVwBzB4obvBUCPABLADsHgFo3E1wodjqQzhdLn9bgRHs8iFC3h8fv9AeEADH0RAAf8QRA4ABeAOFAA__",
            "Do Alto":
                "IgYAwgggzAAAgDGANhyAgaBABQAYAFwCcBTAIwBtjE1EYAaNOADkQCpGA2RASkYFZEAagAQcLjAAUo2DF5wZ7TIIAsPRjIlZBAJkQByUV0zdRLWdMQBSQ23VqluyYzPt5PC.RsxX4wVoDstmJqcAJObrJaqt78QpyIdAAIzPAwaACG5PgA9jCWibQAZAX6JTAARGUABGUAhGV6ZflFTSVwaADK2QAOAHRoAELpAM69VWDElKSE6fjEACZVw0QArgDma5RL-OmE-ACWAHZrALTK.nzjk2Qzc.Mny4Trm8QPO3tHp-d8ADG0iAB.xDEPQAV4A9EA__",
            tenor: "IgYAwgggzAAAgDGANhyAgaBAAoAoAFwFMA7AewCcYBSABERgHI7EAKZmAMndvqfoBJ2AYm7su9HvFxoARgEMAzgsRp6APDRwAHIgA4m2DAAEmgGyINcQwHwsAagBMFg4gC49gCx6AEHHMxXXwBWRGtfHQDfQxM.UPsAdmdtPRcYNSiYTABsX38cqzdwpP93TDtEmH1kmFs4EMrU0scUgpgsz0QALDMUsq8YbtiA1LUaZLg0AGVSAAcAOjQAIUU5ozBCABtCGXI5IgATIwV8cgBXAHNzraP8OXJ8AEtic4BaD3igtc3t3YOX47Oly2.1u9yer3eQQAMfREAB.xCEKgASgA7kA",
            fa: "IgYAwgggzAAAgDGANhyAgaBAAoAYAFwCcBTAIwBtjEAIRGASmrgFZEAKJgNkQFInYYAMjRwBAciwBqACyJhoxABIRADnZde.diPFSATNoUxlcbjD5w1MMVphsdiCZkkG7qxACoRra9WcB2GExBDSE.F01LRABiJh9FUJ4ABCi4bDRSAEMAZ2yYADwkugAcIsQAXDKYUroAfCrCuqqAQgaq-rpG-DQAZQB7AAcAOjQAIRyhgAIwYkpSQkz8YgATSeyiAFcAcy3KNfxMwnwASwA7LYBaaX9madmyBaXli.XCbd3iF4Ojs8vr5gAMXREAB.xDEMQAd7gQA_",
        },
        lydian: {
            soprano:
                "IgYAwgggzAAAgDGANByAgaBAMBgAXAJwFMAjAGyJgDIAERGAcjsQGJmYASdgUndvt70AFD3ZN6.eAFA0JAIYBnBYgAQiTAHwVcAByItmANQAmGJgB422DEtwAbIgCEV.docqARC5gACNPf0sQwB2RD8AmAAcf2stXURLI1MYAFwVJLNI7yyItLgAVkRouGsUoOTi63CHKO1Cm28NGni4NABlAHsABwA6NAAhRR6fMCIKEgI5PCIAEx8FQgBXAHNlinm8OQI8AEsAO2WAWgAWYPyRsdJJ6ZnDhYIVtaI7ze39o9P8gBj6RAB.xBEIQAcDkQA_",
            "Do Alto":
                "IgYAwgggzAAAgDGANhyAgaBAM0EMA2ALgPYwD4ACIjAARWICE9tzl1AeM09XdW.AFA0AI1wBnMYgAQfKXFhSA2GjgA2RABwVAVhhKV6mOxWwYGuYbJzTx-YgC4WANQAWRLdNa4umPeuIALAtNf0wg70C5AA5EKzsjEwdnNzMdd0TyCjgYuDQAZWIABwA6NAAhcWKaMABTfBrhACdcQhqAExoxQkaAVwBzPvrOwlxGwgBLADs-gFoXAHZtarqG5ta2ma7egfrNkbGp2YXtABjqRAB.xBqACnygA__",
            tenor: "IgYAwIgYAwgggzAAAgDGANhyAgaBABQAYAFwCcBTAIwBtjE1EYAyNOADkQApHYYASRgNhgAQASj5tGAVkEi4.GAGpGLGAHIBcSZlZrZWzHIAsiVXE4NmRrHIBMYk4gBUEi3Zjs9hlRwej5a2MO1EOQAEdVt.EXdw7zDhLxhHKPknGAAaHwBaUJYEbHxiADsAe0IYAHxg2gBcSsQAHFqYADxGitoW6saAAlbu3sQ4NABlIoAHADo0ACEAQwBnca6wYkpSQhn8gBMuuaIAVwBzA8od.BnCfABLAoOM.QB2cSWVsnWtjN3CQ-PiD7OL663B7iAAxtEQAH.EMQAKQALIASEA_",
            fa: "IgYAwgggzAAAgDGANhyAgaBAAoAYAFwCcBTAIwBtjE1EYAyNOADkQCpGBWRACkdgAgAlPziwYAGhEA2Nn0QBqLPIAss0YgC0jGTHnSYmDSJYwjcHZLhcYAOjm6lAdjUXGJveZ4iBg--0wqCpyI4tqaAAjM8DBopACGAM4JMAD44bQABOmIAITZqfl5tAB4-WmZZdlwaADKAPYADnYAQok2GWDElKSEcfjEACYZCUQArgDm45TD-HGE-ACWAHbjGsqOHB1dZL39AxojhBNTxAez88ur6xwAMbSIAP-IxADkAD8Ar0A___",
        },
        mixolydian: {
            soprano:
                "IgYAwgggzAAAgDGAPByAgaBAMBgAXAJwFMAjAGyJgHIAERGAKjsQEpmYAadganbfoAUPPuyH1aiOAFA0JAIYBnBYjT0ABGjgAORABxNAVkQA8TbBgAsM4gDYWbgCZEVuOdNwAbIgC4ACE-Iav5umjow3vZOMPqugZpeMAD4.gnGvpjcAOw-8SbWMHbaepE-.kaYuil66Y62waUBMACY9dG5BSVtATSJ-Wo0RXBoAMoA9gAOAHRoAEKKk2pgRBQkBHJ4RAAmagqEAK4A5gcUO3hyBHgAlgB2BwC0ACyZBovLpGsbm3e7BIfHRN8zhcbvcngYADH0RAAf8QRAEAFQBEA__",
            "Do Alto":
                "IgYAwgggzAAAgDGANhyAgaBABQAYAFwCcBTAIwBtjE1EYByNOADkQEpHYYBSRgNkQAUHNlgDUAFkHCYovogBUACDj9MAGmUsYGuLEwDl.GAbgBWNocQNdUzBIVyY7M4OWdRlmEuauVVx0J2AOwiPjLS8tKydpLajOYACAC0jgB0CT4IaACG5PgA9jAABAm0APiliAB4lTAAOLUAuLU15bUAxLUARLUAhLUliHBoAMr5AA6paABC2QDOqUVgxJSkhNn4xAAmRXNEAK4A5oeUu.jZhPgAlgB2h0niQaZLK2Trm1tJe4RHJ8Rf50ut3uj1MABjaIgAP-IYgAEgAhwBfIA__",
            tenor: "IgYAwgggzAAAgDGANhyAgaBAAoAoAFwFMA7AewCcYByABERgCo7EBqZmACnYEp236m9LvVqI4uNACMAhgGdZiABCJMAAmWJ1mFgBYYmAPiK4AVkRG4ANkQBcYwA5zaOLBgA8LLqcvEAQmeOMHZWmsauNs7W7p4A7N5REXCBbsZRANhhiAA4kbbOZjA5ITQGzq6qNEnwaADKpAAOAHRoAEJyjapghAA2hJLk0kQAJqqy-OQArgDmU72j-NLk-ACWxFMAtDoxJp09fQPD62OTM71HC0urG1smADH0iAD.iIQApDEAqkA__",
            fa: "IgYAwgggzAAAgDGANhyAgaBAAoAYAFwCcBTAIwBtjE1EYByNOADkQBJGBWRAUkYDZEAMn6IGmANQB2ISJgAKRixjcAEHFjy1A-rIUTpMAJSLE4xhsNaYmOWq6a4AzACo1S1xIAsiS-sTPzUyxxbxgAvwAEAFpZADoI5ngYNFIAQwBndJgATAjaACw8xAAcIpgAbDKAXDLS2lyCsob4NABlAHsAB1i0ACEM2IACMGJKUkJU.GIAE0H0ogBXAHMlyjn8VMJ8AEsAOyWoz0kOYdGyCanpqPnCZdXia42tvYOjjgAY2kQAf8RiOQAkAAWoA_",
        },
        aeolian: {
            soprano:
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyJgAoAERGAKjsQEpnr236AadganZN6XRLURwAoGhIBDAM5zEACESYAhErgAORBriwYAPE0A2RAAI0-xAHwsfACwWrBw1YCsiALibPMADim3lZmMJbWRh7BcKGBEeZBMF4hiG5wfnYx0TpGSph8AEy6mgY-WTQJEWo02vBoAMoA9gAOAHRoAELyreZgRBQkBDJ4RAAm5nKEAK4A5jMUE3gyBHgAlgB2MwC0DgDs7r39pEMjo1uTBLPzROdLKxvbe-4AMfSIAP-IRFQAmADTQA__",
            "Do Alto":
                "IgYAwgggzAAAgDGANhyAgaBAM0EMA2ALgPYwAUACIjAKRWIBk9MA5M5dQCTN3VPUdEvRAEp29OAFA0AI1wBneTABYzAJgAIOADZEAHC2wVW3TAC4hxGrRwjyrAGoALPpunrt1zsQBsRwHYvUzMbAFZfGyM9RwAmCM8YAAw3KxN9S2NvTAsEnPCYA28YD1NohPs4fL9MZ0QQouiawPMUig87CjgADng0AGViAAcAOjQAIQVhgAIwAFN8WZkAJ1xCWYATKflCJYBXAHN9ha3CXCXCAEsAO32AWid.UJn5xZW19dvtvcOFz9Pz653B6hAAx1EQAH.ELNOAB3gDcQA__",
            tenor: "IgYAwgggzAAAgDGANhyAgaBAaBgAXAJwFMAjAGyMQAhFMAaKuAVkQcwGoAWGDx2GdlQ4AmHgCpGADkQSOAdh4BKRgDZEy5uNUypPAHSMWMA3Fj1dMBppgBabTAD0Q9gswm1xwzydwPT-TAACO6IDoFw0ggAoHhEAHYA9gQwAISBiDAAROmIAMQ5MAAkBQCkBfkZZRlpGdkZFYh1iDXwaADKCQAOemgAQgCGAM56AARgRBQkBP2xACYjg4QArgDmKxQLeP0EeACWcSs2nHJMYxOk03M2iwSr60TXWzv7h8dMADEZiAD.iEQlAH6ACtAA_",
            fa: "IgYAwgggzAAAgDGANhyAgaBAAoAYAFwCcBTAIwBtjEAIRGACmrgA5EBKJ2TAGiYDZEvOLAb92aOAJgAqLAGoA7OMmIAZBJGzh4zHIBMiLSPoTWMAORMArDEyMVo3UoAIlh.Wct4MNKQCGAM4BMABYznQAmOGIADjRMAC48WF0cXQA2MnRcGgAygD2AA4AdGgAQoHFAARgxJSkhH74xAAmVQFEAK4A5t2U7fh-hPgAlgB23QC0ACwKVjV1ZI3NLZMdhD19xGuDw-NTs1YAMXSnALDE9KoA3kA",
        },
        locrian: {
            soprano:
                "IgYAwgggzAAAgDGANhyAgaBAAoAYAFwCcBTAIwBtiYBKABERgCp7EBqFmACg-YbofYNeifvACgaUgEMAzjMQAIRJgBECuAA5EazKwBMiAITrYMFWjinDWVgBZtF0wAILAVkQBidVpgB8E0aOiC669n5ugZaIALjqAGyIAHjq7jCxmjCYANgBMDm6BjAAWLlZtBlwaADKAPYADgB0aABCsg1OYMSUpIRS-MQAJk4yRACuAObjlMP4UoT4AJYAduMAtLYA7K4dXWS9.QOrI4QTU8RHs.PLa5uuADEMiAhoxJy2APRAA___",
            "Do Alto":
                "IgYAwgggzAAAgDGANhyAgaBABQAYAFwCcBTAIwBtjEAIRTASmrgA5FHMBqAdhkwAomANkQDOAFkQByJrBgAyNHFkBSLBwBMiBUraLhMPnq1qJMVToNH5QxACoZbGwaYBWKTYZNWMdtxFP6AAQWeBg0AENyfAB7GAAiQMQYAGJExGU0mAASTNSkgEJMnKSEpLzEUvg0AGVogAcAOjQAIXCAZwaAAjBiSlJCcPxiABNOtqIAVwBzKcox.HDCfABLADspgFoxLhdu3rIBoeGN8cJp2eIThaW1ze2XABik54AkYgAMaIAWoA",
            tenor: "IgYAwgggzAAAgDGANhyAgaBAM0CMCGAzoTAEQAIiMABJYgPh0wB4TtVrVjVFV7iAYia94AUDxESMABCJMAbGlwAHIkVwAbImZLYMALi7EALCVaYAHDRw98rAGoALCesBWNQ-eWl7mOvMAmGaIFkYGYaaaiPrW5laY9gDsHirRsSnmxg7JfukGntrBMJG25KlwaADKAPYADgB0aABCRPXUYACmADYduABO-AAuHQAm1ISDfQCuAOYzPeOD-H2DAJYAdjMAtI6Jru3dvQPDI1sT03M9Z0srG9u7rgAxVIgIALAdABQA5ABDQA_",
            fa: "IgYAwgggzAAAgDGANhyAgaBAAoAYAFwCcBTAIwBtjEAIRGASmrgA5EBSJ2TAciYFZEvTAGoALIgBkndmjgA2SVmEB2GfMGzWMKXFgwhYxAApZCmACpNGuAJgn1DAAgt4MNKQCGAZy8wA2I50ADiBiAC4oTAAeJERwZEBiHBoAMoA9gAOAHRoAELeWQAEYMSUpIQe-MQAJoVeRACuAOZNlHX4HoT4AJYAdk0AtKLKfMWlZBVV1QP1hM2txDMdXX2Dw3wAMXSIAP-IxBIAEgAzQA__",
        },
        aionian: {
            soprano:
                "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyJgCoAERGAajsQBpmYBadp-2-n1uz6D-Q5nABQaEgEMAznMQAIRJgDESuAA5EGzAwBMiAESbYMAIRo4AVkQACawDZEV24gB418xc0uYALhmiAD4zp5YDADsiAHWOjCO7pbBMB5-oeFpkTEwYXD-cdqIADipQfpG2QWxOaXxiADYkVUAWJp2mGVw5mWVTaklNMVwaADKAPYADgB0aABC8jP2YEQUJAQyeEQAJvZyhACuAObHFPt4MgR4AJYAdsccACxRNitrpJvbOxwHBCdnIi.S7Xe6PF42AAx9EQAH.EEQABQ2AB9QA__",
            "Do Alto":
                "IgYAwgggzAAAgDGANhyAgaBAM0EMA2ALgPYwDEACIjAORWICk9MAZMwFTMCUzb1T1ACTNKiOAFA0AI1wBnWYgAQiTABxFcAByJ1cAKyIAeBtgxdpgAQaAbIgC4JxAHwN2mIbRxbMO1gDUAOxGnt5OngYwFp6mvl6IAJjRiADYnm4AWDYwmA5wMYqYfgBM2eY6BcUpjmYUWvBoAMrEAA4AdGgAQnKtFmAApvh9UgBOuIR9ACYWsoTDAK4A5guD04S4w4QAlgB2CwC0ACwBer0DQ6PjE3sz80uD12sbO.tHegAx1IgA.4h9DHAUIA_",
            tenor: " IgYAwgggzAAAgDGANhyAgaBABQAYAFwCcBTAIwBtjE1EYAqNOADkQBpHYYBKLAagHZEACg6IemXgBZEDOAFZho-gAg4ANhiYA5Ks4640mADJdw1SxgBSVQu5KREgExillxhphb3iiYLvNFdUR9BUwhVQ9wuE4AEgjEIyUvCUNE6Jcg-gAEAIRsfGIAOwB7QhgAHCzaAHwqxAA8OpgAXCaAQiaAAiaAIiaAYiba2lbaSsQ4NABlYoAHADo0ACEAQwBnec6wYkpSQhWCgBNOtaIAVwBzC8oT.BXCfABLQouAWkl-OS2dsn2j19OhEu12IALuD2ebw-cgAMbREAB.xDEISOABZQA___",
            fa: "IgYAwgggzAAAgDGANhyAgaBAAoAYAFwCcBTAIwBtjEAIRGAKmrgA5EByJ2BpgNkQGo0LRPSz8A7IgCUQvjEHCYHOLEyM4c9QFZEACk7sDMKUx0wAZEK4BSMQCZElldNmJrvR9UwTDztR-5vSWMA-gAEYQQ0UgBDAGc4mAAcMLoAPFTEAFxMmAy6AHxc.OzcgAJi3Jy6FMQ4NABlAHsABwA6NAAheLaysGJKUkIY.GIAEzK4ogBXAHNZykn8GMJ8AEsAO1mAWgAWcS0-gbJh0bHtqcI5heIL5dXNnf2tABi6RAB.xGJzAHEAX6AA_",
        },
    },
};
