const blueprint = {
    dorian: {
        up: "",
        down: "",
    },
    lydian: {
        up: "",
        down: "",
    },
    frigian: {
        up: "",
        down: "",
    },
    maxolidian: {
        up: "",
        down: "",
    },
    iolian: {
        up: "",
        down: "",
    },
    ionian: {
        up: "",
        down: "",
    },
    locrian: {
        up: "",
        down: "",
    },
};
export const _oldData: any = {
    dorian: {
        soprano:
            "IgYAwgggzAAAgDGANhyAgaBAAoAYAFwCcBTAIwBtiYASABERgDJ7EByFmAUg4AoP2GzBtwZ0GMFnGxpSAQwDO8xBwniV6tZoYbtiOGgDKAewAOAOjQAhBWYAEYYpVKFZ-YgBNb8ogFcA5n6UXviyhPgAlgB2fgC0ACwA7ACs9o5kLm7uMd6E.oHE2SFhUbGJSQAx4vCI7gBIADoAvUA_",
        bass: "IgYAwgggzAAAgDGANhyAgaBAAoAYAFwCcBTAIwBtjEAERGumWup-5hlx9r-bNUgQwDOgmAFwWAfBYACFgDwWAQhmT5LcdzhoAygHsADgDo0AISGHpYYpVKF--YgBNpgogFcA5h8ov8.QvgAlgB2HgC0ACwA7ACsltZkdg6OYa6Ent7EqX4BIeHRMQAxDHQAEI4AKAA.2EA__",
    },
    lydian: {
        soprano:
            "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyJgDIAERGAcjsQApnr2ASdgUndvoAqdm3pN6A-szgAoNCQCGAZyWJ2MdZvobtWqboP6jcNAGUA9gAcAdGgBCy6wAIwRCiQIK8RACZOlhACuAObBFP54CgR4AJYAdsEAtAAsAOwArC5upJ7ePokBBCFhRAWR0fFJaekAMdrwMACgPgBIPgATQA_",
        bass: "IgYAwgggzAAAgDGANhyAgaBAAoAYAFwCcBTAIwBtjEAERGumWup-5hlx9rtnhNUgIYBnITAD4LAAQsAhCwl0AuCwB482SwDEGutLoL4aAMoB7AA4A6NACFhFyWGKVShAfmIATSUKIBXAOb-lN74AoT4AJYAdv4AtAAsAOwArA5OZK7uHrE-hAFBxDmh4dFxSckAMQx0ANAeAEj4AIVAA",
    },
    frigian: {
        soprano:
            "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyJgFIAERGAYjsQBJnr2AKdgMnYHJ2ten3rD4AKDQkAhgGc5idjGWr6K9WvpaliOGgDKAewAOAOjQAheWYAEYIhRIEZeIgBNbcwgFcA5n4UXngyBHgAlgB2fgC0ACwA7ACs9o6kLm7uMd4E.oFE2SFhUbGJSQAx6vQAoO4ASAB.ALFAA___",
        bass: "IgYAwgggzAAAgDGANhyAgaBAAoAYAFwCcBTAIwBtjEAERGumWup-5hlx9rt-bNUgIYBnITAB4LADgsAuFJYAsFgGxZLCXQD46jkzhoAygHsADgDo0AIWFmABGGKVShAfmIATW0KIBXAOZ-lF74AoT4AJYAdn4AtAAsAOwArPaOZC5u7jHehP6BxNkhYVGxiUkAMQzwMLjuAEikABNAA_",
    },
    maxolidian: {
        soprano:
            "IgYAwgggzAAAgDGANhyAgaBAAoAYAFwCcBTAIwBtiYByABERgCp7EBKFmACg-YYBoOAag4A6DgIa9EwhuwbcGdRHGxpSAQwDOmxBxh6DDfUcMNTuk5bNW4aAMoB7AA4i0AIS0iABGGKVShOr4xAAmXppEAK4A5tGU4fjqhPgAlgB20QC0ACwA7ACsPn5kgcEhmRGEMXHEFYnJ6Vl5-QAxRgwgIQBIAB7AQA_",
        bass: "IgYAwgggzAAAgDGANhyAgaBAAoAYAFwCcBTAIwBtjEAERGumWup-5hlx9rtn11hNKQCGAZxEwAmCwA4LANgsAWDJYA8FgFwWAfDUq6WugrrK6UxHDQBlAPYAHAHRoAQqIcACMMUqlCQ.MQAJu4iRACuAOYRlCH4QoT4AJYAdhEAtAAsAOwArJ7eZH4BgWmhhJHRxKVxCSnp2TkAMQwMgQCouBJAA",
    },
    iolian: {
        soprano:
            "IgYAwgggzAAAgDGANhyAgaBAAoAYAFwCcBTAIwBtiYAKABERgCp7EBKFmAag-YYBoOAWg4CG3BrzYc6iONjSkAhgGdliDjA1aGmndob71e4.DQBlAPYAHAHRoAQipsACMMUqlCi.MQAmz5SIAVwBzEMoA.EVCfABLADsQwQAWAHYAVld3Mi8fX0FAwlDw4gKomISktPSAGJ0GAGhfACQADwBPIA_",
        bass: "IgYAwgggzAAAgDGANhyAgaBAAoAYAFwCcBTAIwBtjEAERGumWup-5hlx9rtnubNUgEMAzsJgAsFgBwWAbBYBcaSwB4LAPirFyuvLqTEcNAGUA9gAcAdGgBCIywAIwxSqUKD8xACYPhRAK4A5oGUvviChPgAlgB2gQC0ACwA7ACsTi5k7p5e8X6EQSHEeeGRsQkpqQAxDPAwANBeAEgAngD7QA___",
    },
    ionian: {
        soprano:
            "IgYAwgggzAAAgDGANhyAgaBAAoAYAFwCcBTAIwBtiYBiABERgFJ7EAyFmAcg-YYAoO3BrzY8OAEg51EcbGlIBDAM5LEHGOs0MN2rQz1rdR-GgDKAewAOAOjQAhZdYAEYYpVKEF-YgBMnSogBXAHNgyn98BUJ8AEsAO2CAWgAWAHYAVhc3Mk9vH0SAwhCw4gLI6PiktPSAGO0GAGgfACQADwApoA_",
        bass: "IgYAwgggzAAAgDGANhyAgaBAAoAYAFwCcBTAIwBtjEAERGumWup-5hlx9rtnubNUgEMAzsJgAcFgDwWAfBYACaSwCEi5XXl0ZdALgtJiOGgDKAewAOAOjQAhEVYVhilUoUH5iAEwXCiAVwBzQMpffEFCfABLADtAgFoAFgB2AFYnFzJ3Ty94v0IgkOI88MjYhJTUgBiGOgBoLwAkAE8AAKA_",
    },
    locrian: {
        soprano:
            "IgYAwgggzAAAgDGANhyAgaBAAoAYAFwCcBTAIwBtiYBKABERgCp7EBqFmAGg4DoOBaDtwZ8Gwth2YM6iONjSkAhgGdliDjA1aGmndob71e4.DQBlAPYAHHmgBCKngAIwxSqUKL8xACZPlRACuAObBlP74ioT4AJYAdsH8ACwA7ACsLm5knt4-.AGEIWHE-ZHR8YmpaQAxOgwA0D4ASADeAApAA__",
        bass: "IgYAwgggzAAAgDGANhyAgaBAAoAYAFwCcBTAIwBtjEAERGumWup-5hlx9rtnubNUgEMAzsJgBsFgBwWAXBYA8FgAIWAfEUrNdeXRl1JiOGgDKAewAOAOjQAhEVeVhilUoUH5iAE2XCiAVwBzQMpffEFCfABLADtAgFoAFgB2AFYnFzJ3Ty94v0IgkOI88MjYhJTUgBiGeBgAcC8AJAAvAFsgA___",
    },
    default: "",
};
const sop_bass = {
    dorian: {
        up: "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyJgGoAERGAWjsQBpnr2A6dp-gei492berURw4aEgEMAzrMTsYSlfWVrV9TYo3i0AZQD2AB05oAQnM4ACMEQokC0vEQAm12YQCuAcx8UPPGkCPABLADsfBgAWAHYAVlt7UicXVwZPAl9.IgygkIiouPiAGLUYAFBwioBHVFcAZYBrgCsgA_",
        down: "IgYAwgggzAAAgDGANhyAgaBAAoAYAFwCcBTAIwBtjEAERGumWup-5hlx9rt-GNUgIYBnITAC4LAPgsAeCwl0ABFJYBCFsrrS6cugvhoAygHsADgDo0AIWHnFYYpVKEB-YgBNFQogFcA5n6UXvgChPgAlgB2fgC0ACwA7ACs9o5kLm7uMd6E.oHE2SFhUbGJSQAxDDAAoJHVAI4I2O4AywDnbUA__",
    },
    lydian: {
        up: "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyJgDIAERGAcjsQApnr2ASdgUndvoBKdm3pN6A-HDQkAhgGd5idjBVr6qjevrblWxNIDKAewAOAOjQAhBeYAEYIhRIFZeIgBM78wgFcA5v4U3niyBHgAlgB2.gC0ACwA7ACsDk6kru4esT4EAUFEOaHh0XFJyQAxGjAAoFE1AI6IAOAeAMsAXwAMQA_",
        down: "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PX440SBDAM6CYAfGYACZgEJm42gFxmAPDnMARDMlrEvAMoB7AA4A6NACEhJiWCIUSBfniIATCYMIBXAObeK7vH4CPABLADtvAFoAFgB2AFYbO1JHZxdIjwIfPyIMwODwqLj4gBj6GABQMIqARwQAKBcANYAegFkgA___",
    },
    frigian: {
        up: "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyJgBoAERGAKjsQGpnH2AKdgcnYFJ2AMgHM4cNCQCGAZxmJ2MRcvpLVK-hokBlAPYAHAHRoAQrMMACMEQokCUvEQAmFmYQCuAc08VXeKQR4AJYAdp4AtAAsAOwArFY2pPaOTuFuBF4-RGn-gaERMbEAMarwMAAQTgDLAB8AI0A_",
        down: "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3EE0SBDAZ34wAeMwA4zALjjmAQmYACZqNoB8ZYzhoAygHsADgDo0AIQGGFYIhRIFeeIgBMF.QgFcA5h4ou8vAngAlgB2HgC0ACwA7ACsltakdg6OYa4Ent5EqX4BIeHRMQAx9DAAoMGlAI4A.4iOAMsArwAzQA___",
    },
    maxolidian: {
        up: "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyJgHIAERGAKjsQEpnr236BqT93-l0QAKdrUQI0JAIYBnWYnYwlK-srWr6mxRoloAygHsADgDo0AITmmABGCIUSBaXiIATG7MIBXAOa-KTzxpAjwASwA7XwBaABYAdgBWOwdSZ1c3aK8CPwCiLODQyJiExIAYtRgAUAiqgEd6NwA1gF6AP6A___",
        down: "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PXuWE0SAhgGchMAJjMAOMwDYzAFhTmAPGYBcZgAJmAfBVLai2hMRw0AZQD2ABwB0aAELDbmsEQokCAvEQAmmoUIAVwBzEIoAvAECPABLADsQgFoAFgB2AFZXd1IvH18kwIJQ8KJCqJiE5PSMgBj6GABQeMaARwQASF8ANYAOgEWgA___",
    },
    iolian: {
        up: "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyJgAoAERGAKjsQEpmYBqdp-gGnYC07fvS70erdrURw4aEgEMAzksTsY6zfQ3at9PWt1H4aAMoB7AA4A6NACFl1gARgiFEgQV4iAEydLCAFcAc2CKfzwFAjwASwA7YIEAFgB2AFYXN1JPbx8BAIIQsKJ8yOj4xNS0gBjtGABQOPqARwB.xB8ANYBBgECgA_",
        down: "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PXuE0SBDAM6CYALGYAcZgGxmAXEnMAeMwD4y-Ytqza4xHDQBlAPYAHAHRoAQkPMACMEQokC.PEQAmdwYQCuAc38Kbzx-AjwASwA7fwBaABYAdgBWBydSV3cPWJ8CAKCiHNDw6Lik5IAY-hgAUCiagEdEAGgPADWAIYBwIA__",
    },
    ionian: {
        up: "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyJgGIAERGAUjsQDJmYBydp-gCm.Zt6PRABJ2tRAjQkAhgGd5idjBVr6qjevrblWqWgDKAewAOAOjQAhBeYAEYIhRIFZeIgBM78wgFcA5v4U3niyBHgAlgB2.gC0ACwA7ACsDk6kru4esT4EAUFEOaHh0XFJyQAxGjAAoFE1AI6IAFAeAGsAw21AA__",
        down: "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PXuE0SBDAM6CYAHGYA8ZgHxmAAknMAhPMW1ZtKbQC4zcYjhoAygHsADgDo0AISEW5YIhRIF-eIgBM5gwgFcA5v4U3nj8BHgAlgB2.gC0ACwA7ACsDk6kru4esT4EAUFEOaHh0XFJyQAx9DAAoFE1AI4IANAeAGsAQwD.QA__",
    },
    locrian: {
        up: "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyJgEoAERGAajsQCpnr2AKdt-gGnYA6drXq9Eo-DDQkAhgGd5idjBVr6qjevrblWxHDQBlAPYAHQWgBCCwQAIwRCiQKy8RACZ35hAK4BzfwpvPFkCPABLADt.AFoAFgB2AFYHJ1JXdw9YnwIAoKIc0PDouKTkgBiNGABQKJqAR0QAcA8ANYBRgGggA_",
        down: "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PX4Y0SBDAM6CYAbGYBcZgBxm42gDwZzJbQAEk5bXnw0AZQD2ABwB0aAEJCTasEQokC.PEQAmawYQCuAc28V3ePwEeACWAHbeALQALADsAKw2dqSOzi6RHgQ-fkQZgcHhUXHxADH0MACgYRUAjggAUC4AawCjAIVAA___",
    },
};
const tenor = {
    dorian: {
        up: "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyJgGoAERGAWjsQBpnr2A6dp-gei492berURw4AUDxEAdgHsCidjBVr6qjevrblW8WgDK8gA6c0AIQCGAZ04ACMEQokCVmQBN7NwgFcA5v4U3nhWBHgAlrL-DAAsAOwArI7OpG6eDD4EAUFEmaHhUTEJiQAxGjCSspIAjgD.iB4AywA3AEVAA__",
        down: "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PX4YBQPIgDsA9gRgBcZgHxmAPGaTaAAmnMAhMxW0ZtebUXw0AZWEAHAHRoAQgEMAzuaVgiFEgRsCAJkruEArgDmARQ-eDYEeACWggEAtAAsAOwArE4upO5esb4EgcFE2WER0XFJyQAx9HyCvACOCABQngDLAI8AEUA__",
    },
    lydian: {
        up: "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyJgDIAERGAcjsQApnr2BSdt-2-gJQ92TPszhwAoHiIA7APYFE7GCrX1VG9fW3KtiOGgDK8gA4A6NACEAhgGdzAAjBEKJAjZkATR3cIBXAHNAil88GwI8AEtZQIBaABYAdgBWZ1dSD284vwIgkKIc8MiY-OSUgBiNGElZSQBHREkvADWAAYB8oA",
        down: "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PX44BQPIgDsA9gRgB8ZgAJmAQmaTaAXGYA8BcwBEc6RsRw0AZWEAHAHRoAQgEMAzmalgiFEgWsCAJlNuEArgHN.Cm88awI8AEtBfwBaABYAdgBWR2dSN08YnwIAoKIs0PCo2MSkgBj6GF5BXgBHAH.EDwA1gB7fIA___",
    },
    frigian: {
        up: "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyJgBoAERGAKjsQGpnH2AKdgcnYFJ2AMgHM4cAKB4iAOwD2BROxjLV9FerX0tcNAGU5ABwB0aAEIBDAM7GABGCIUSBC9IAmtq4QCuAc18UnngWBHgAljK-ALQALADsAKz2jqQu7lFeBH4BRBnBoRHR8QkAMeowAP-IbgBrAL0AkEA__",
        down: "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3EEBQPIgOwD2BGADxmAHGYBcScwCEzAATNxtAPirGcNAGVBABwB0aAEIBDAM5GlYIhRIFzfACZLLhAK4BzbxXd45gR4AJb83gC0ACwA7ACstvakTq4RHgQ-fkRpgcFhkbFxADH0MNz83ACOAP-ILgDLAK8AXkA___",
    },
    maxolidian: {
        up: "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyJgHIAERGAKjsQEpnr236AKT9gaj492tRAgCgeIgDsA9gUTsYSlfWVrV9TYo1i0AZVkAHAHRoAQgEMAziYAEYIhRIFLUgCZ3rhAK4BzPwovPEsCPABLaT8AWgAWAHYAVgcnUlcPaO8Cf0CiTJCwyJiExIAYtRhxaXEARwQ0dwA1gD6AMSA",
        down: "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PXuEBQPIgDsA9gRgACZgGJmAImYBCOcwD4i5bQAkGxEtqTEcNAGVhABwB0aAEIBDAM4XxYIhRIFbAgCbj7hAK4A5oEUvni2BHgAloKBALQALADsAKzOrqQe3nF-BEEhRDnhkTHxySkAMfQwvIK8AI4A.4heAGsAXcJAA",
    },
    iolian: {
        up: "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyJgAoAERGAKjsQEpmYBqdp-gGnYC07fvS70erdrURw4AUDxEAdgHsCidjE3b6W3TvoGN-k.DQBlFQAcAdGgBCAQwDONgARgiFEgUeKAJm7OhACuAOZhFEF4jgR4AJZKYQIALADsAKweXqS-AQLBBOGRRAUxcYnJ6RkAMbowckpyAI6IAND-AGsAgwAWQA_",
        down: "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PXuE0BDMngD2MAFjMAOMwDYzALiTmAPGYB8ZfMW1ZtcYjhoAykIAOAOjQAhPgGczAAjBEKJAnzxEAJvZuEArgDmARQ-eHwEeACWAHYBALQALADsAKyOzqRuHp5xvgSBwUS5YREx8ckpADH0MACg0bUAjgD.iJ4AawBDAJxAA",
    },
    ionian: {
        up: "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyJgGIAERGAUjsQDJmYBydp-gCm.Zt6PRABJ2tRAgCgeIgDsA9gUTsYajfXVbN9Xap1S0AZUUAHAHRoAQgEMAzhYAEYIhRIFbcgCZP7hAFcAcyCKPzxbAjwAS3kggFoAFgB2AFYXN1JPH3j.AmDQolyIqNiElNSAGK0YaXlpAEcAf8RvADWAYYA.oA_",
        down: "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PXuEBQPIgDsA9gRgAcZgDxmAfGYACacwCEi5bXm0ZtALjNJiOGgDKwgA4A6NACEAhgGdLCsEQokCdgQBMFDwgCuAOZBFH54dgR4AJaCQQC0ACwA7ACsLm6knj7x.gTBoUS5EVGxCSmpADH0MLyCvACOAP-I3gBrAMMA5EA__",
    },
    locrian: {
        up: "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyJgEoAERGAajsQCpnr2AKdt-gGh5dB9WogQBQPEQB2AewKJ2MJSvrK1q-psUaxaAMqyADgDo0AIQCGAZxMACMEQokClqQBM71wgFcA5n4UXniWBHgAltJ-ALQALADsAKwOTqSuHtHeBP6BRJkhYZExCYkAMWow4tLiAI6I4u4AawAjADVAA___",
        down: "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PX4YBQPIgDsA9gRgBsZgFxmAHGYBCZgDxmAAkXMA-NLnNJiOGgDKwgA4A6NACEAhgGcLasEQokCtgQBM19wgFcAc0CKXzxbAjwAS0FAgFoAFgB2AFZnV1IPbzi.AiCQohzwyJj45JSAGPo-QV4ARwB.xC8ANYBxgACgA",
    },
};
const doalto = {
    dorian: {
        up: "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyJgGoAERGAWjsQBpnr2A6dp-gei492berURw4aAIZk8Ae0TsYSlfWVrV9TYo3i0AZTkAHTmgBCUgM6cABGCIUSBKXiIATG5cIBXAOa-KTzwpAjwASwA7XwYAFgB2AFY7B1JnVzcGLwI.AKJM4NDI6PiEgBi1GABQCMqARwB.xDcAZYAbgA8gA_",
        down: "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PX4Y0BDMngD2MALjMA-MwB4zcbQAEk5gEJmS2lNqza8-GgDKQgA4A6NACE-AZ1MKwRCiQJ88RACYLrhAK4BzPwovPD4CPABLADs.AFoAFgB2AFZ7R1IXN3cY7wJ.QKJskLCo2MSkgBj6GABQSOqARwB.xHcAZYBHgHGgA___",
    },
    lydian: {
        up: "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyJgDIAERGAcjsQApnr2BSdt-2-gJQ92TPszhw0AQzJ4A9onYwlK-srWr6mxRsSSAynIAOAOjQAhKQGcTAAjBEKJAlLxEAJrauEArgHM.Ci88KQI8AEsAOz8AWgAWAHYAVntHUhc3dxjvAn9AomyQsKjYxKSAGLUYAFBI6oBHAH.EdwA1gAGADqA___",
        down: "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PX440BDMngD2MAPjMABMwCEzcbQC4zAHhzmAIhmS1iXgGUhABwB0aAEJ8AzsYlgiFEgT54iAEwmXCAVwDmPih54fAR4AJYAdj4AtAAsAOwArLb2pE4urlGeBL7-RJlBIRHR8QkAMfQwAKDhlQCOAP-IrgBrAD0AiUA__",
    },
    frigian: {
        up: "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyJgBoAERGAKjsQGpnH2AKdgcnYFJ2AMgHM4cNAEMyeAPaJ2MRcvpLVK-hokBlWQAcAdGgBCkgM4GABGCIUSBSXiIATS2cIBXAOZeKbvJIEeACWAHZeALQALADsAKzWtqQOTs4R7gTevkTpAUFhkbFxADGqMAD.iM4AawDdAI5AA___",
        down: "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3EE0BDMvAPYwAeMwA4zALjjmAQmYACZqNoB8ZYzhoAygIAOAOjQAhHgGcDCsEQokCPPEQAmCs4QCuAc08VXeHgR4AJYAdp4AtAAsAOwArFY2pPaOTuFuBF4-RGn-gaERMbEAMfQwAKAhZQCOCAAQTgDLAK8AGkA__",
    },
    maxolidian: {
        up: "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyJgHIAERGAKjsQEpnr236BqT93-l0QAKdrUQI0AQzJ4A9onYwlK-srWr6mxRoloAynIAOAOjQAhKQGcTAAjBEKJAlLxEAJrauEArgHM.Ci88KQI8AEsAOz8AWgAWAHYAVntHUhc3dxjvAn9AomyQsKjYxKSAGLUYAFBI6oBHAH.EdwA1gD6AdCA___",
        down: "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PXuE0BDMngD2MAATMAxMwBEzAIQzmAfHmLaAEjWIFtcYjhoAykIAOAOjQAhPgGczosEQokCfPEQAmom4QCuAc38Kbzw-AjwASwA7fwBaABYAdgBWBydSV3cPWJ8CAKCiHNDw6Lik5IAY-hgAUCiagEcEAHAPADWALoB-IA__",
    },
    iolian: {
        up: "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyJgAoAERGAKjsQEpmYBqdp-gGnYC07fvS70erdrURw4aAIZk8Ae0TsY6zfQ3at9PWt1H4aAMrKADgDo0AIXkBnKwAIwRCiQLy8RACbOHQgBXAHMQigC8eQI8AEsAOxCBABYAdgBWV3dSLx9fAUCCUPCiAqiYhKS09IAY7RgAUHiGgEdEAGhfADWAQYB5IA",
        down: "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PXuE0BDMngD2MAFjMAOMwDYzALiTmAPGYB8ZfMW1ZtcYjhoAykIAOAOjQAhPgGczAAjBEKJAnzxEAJvZuEArgDmARQ-eHwEeACWAHYBALQALADsAKyOzqRuHp5xvgSBwUS5YREx8ckpADH0MACg0bUAjgD.iJ4AawBDSkA__",
    },
    ionian: {
        up: "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyJgGIAERGAUjsQDJmYBydp-gCm.Zt6PRABJ2tRAjQBDMngD2idjBVr6qjevrblWqWgDKCgA4A6NACEZAZzMACMEQokCMvEQAm9m4QCuAOYBFD54MgR4AJYAdgEAtAAsAOwArI7OpG4ennG-BIHBRLlhETHxySkAMRowAKDRtQCOAP-IngBrAMMA10A",
        down: "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PXuE0BDMngD2MADjMAeMwD4zAASTmAQnmLas2lNoBcZuMRw0AZSEAHAHRoAQnwDO5uWCIUSBPniIATObcIBXAHMAih88PgI8AEsAOwCAWgAWAHYAVkdnUjcPTzjfAkDgolywiJj45JSAGPoYAFBo2oBHAH.ETwA1gGGAZCA_",
    },
    locrian: {
        up: "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyJgEoAERGAajsQCpnr2AKdt-gGnYBydrXq9Eo-DDQBDMngD2idjBVr6qjevrblWxHDQBlBQAcAdGgBCMgM7mABGCIUSBGXiIATB7cIBXAHNAil88GQI8AEsAO0CAWgAWAHYAVicXUndPL3i.AiCQojzwyNiElNSAGI0YAFAYuoBHRABwLwA1gBGAG6A___",
        down: "IgYAwgggzAAAgDGANhyAgaBAMBgAXAJwFMAjAGyMQARFraYbbG6n7mG3PX4Y0BDMngD2MANjMAuMwA4zAITMAeMwAE85gHxJM5uMRw0AZSEAHAHRoAQnwDOZlWCIUSBPniIATFTcIBXAOb-FN54fAR4AJYAdv4AtAAsAOwArA5OpK7uHrE-BAFBRDmh4dFxSckAMfQwAKBRNQCOAP-IHgBrAOMA6kA__",
    },
};
export const testData: any = {
    sop_bass,
    tenor,
    doalto,
};
// C  ionian
// D  dorian
// E  frigian
// F  lydian
// G  maxolidian
// A  iolian
// B  locrian
